### ISSUE TITLE
Large Http/2 streams, may deplete flow control window and stall. 

### ISSUE THREAD

**Issue by yepeng820** [square/okhttp#6749] opened 2021-07-08 13:20 UTC
At present, okhttp connection or steam flow_control_size equals 16MB, I have encountered a timeout problem in a scene：
java.net.SocketTimeoutException: timeout
at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:678)
at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:686)
at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:409)
at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.java:286)
at okio.RealBufferedSource$1.read(RealBufferedSource.java:447)
at java.base/java.io.InputStream.read(InputStream.java:205)
at MockHttpClient$1.run(MockHttpClient.java:77)
at java.base/java.lang.Thread.run(Thread.java:834)
Let me take a short video as an example. If the first video is watched for 5 seconds and about 8.5M of data is downloaded (because exoplayer has a flow control, it will not continue to read, but in fact, because the stream flow control is 16M, the first video stream will continue to download by http2 connection), then the user clicks on the second video, so that the size of the video left for this user is only <7.5M, but the trigger of WINDOW_UDPATE is 16M/2=8M, because the second video has not reached This value is reached, so when the second video downloads the traffic to 7.5M, second stream cannot be triggered WINDOW_UDPATE cause timeout

There are a few issues that need to be discussed
1. Since many applications have flow control policies in HTTP1.1 (exoplayer controls the video download time), but when it comes to http2.0, it actually refuses to do so, refer to 5.2.2 of RFC7540
2. If the default value of OKHTTP Client is modified to connection flow_control_size = N * stream flow_control_size, it will reduce the problems of the application
3. Can OKHTTP develop related APIs to modify connection and stream flow_control_size?

**Comment by swankjesse** [comment] 2021-07-08 13:54
Yikes. Just to clarify:

You have lots of data on steam A that's received but not delivered to the application layer. The application layer has not attempted to read from its stream.

This is stalling stream B, which the application layer is attempting to read.

Yep, that sounds awful. A quick & dirty mitigation is to use separate connections for each video stream. Adding `Connection: close` to a request or response header for video requests will do this.

**Comment by yschimke** [comment] 2021-07-08 17:11
Yeah, doesn't seem like we have an alternate simple solution.  As a bad workaround the client can externally buffer the content, but that isn't great obviously.

In the case of exoplayer, if you get to the point that you want to tune flow control, is this something that cronet offers? It feels like a big project for OkHttp to try to commit to, and by the time we got there I'm guessing (but out of my depth), that some of the clients may even be looking at HTTP/3 (envoy mobile?).

I think OkHttp aims to *just* work in the most generally optimal and secure ways, for either Android or JDK, but isn't built with a ton of tunable knobs to play with.

**Comment by yschimke** [comment] 2021-07-09 05:34
What would a (non optimal?) But working fix for this look like at the level of http/2 frames? Is there a limit we should be applying by default? Or a tuning Param (buffer limit) for a while client?

Or should we warm when this is happening so clients can take alternative approaches like @swankjesse suggests?

**Comment by swankjesse** [comment] 2021-07-09 12:33
Yeah, this is a good question!

For reliability I’m relieved to hear that OkHttp has this problem because it means we aren’t just buffering every byte we can get into memory unbounded.

This use case is real and we’re years overdue in addressing it. Streams can exist that don’t want to consume the ResponseBody as quickly as it becomes available! Our current design implicitly assumes streams won’t do that, and we have this bug that causes streams to harm one another.

With that requirement I think our fix might be simple: we should configure flow control to apply per-stream and not per-connection. We could change our default settings from what we have:

    per-stream:      16 MiB
    per-connection: 16 MiB

...to something where streams cannot interfere with each other. We already have a limit`*` on the number of concurrent streams, so we’re not at risk of exhausting all memory:

    per-stream:      16 MiB
    per-connection: 16 GiB (effectively infinite)

When the application layer sends a call, at that point we permit that call to buffer up to 16 MiBs of unread response data. This memory is scoped to the `Call` (an object the application layer can manage) and not the `Connection` (an implementation detail of HTTP/2 which should be transparent when servers switch from HTTP/1).

Today a bad client that makes Calls but doesn't read their responses or close them will observe very bad behavior: unrelated later calls will stall due to leaked window capacity. This bug is brutal to diagnose because the symptom is very far away from the cause.

With this update we get a much more actionable failure mode: by leaking `Call` objects the application will crash with an `OutOfMemoryError` when it runs out of memory. This crash isn’t ideal, but it's the best way to signal a memory leak and that's what this is.

`*` above I claimed the application limits the number of concurrent streams. Each `Call` is executed either asynchronously or synchronously. Async calls are limited by the `Dispatcher`’ concurrency limits which has user-accessible tuning parameters. Synchronous calls are limited by the application’s thread pool sizes. Those might be unbounded! But in such a case we're not introducing new unbounded memory use we’re merely exacerbating an existing case of this.

Next steps: configure a very  per-connection ceiling here:
https://github.com/square/okhttp/blob/master/okhttp/src/main/kotlin/okhttp3/internal/http2/Http2Connection.kt#L501

**Comment by yepeng820** [comment] 2021-11-03 11:38
//crone thttp_network_session.cc

// The maximum receive window sizes for HTTP/2 sessions and streams.
const int32_t kSpdySessionMaxRecvWindowSize = 15 * 1024 * 1024;  // 15 MB
const int32_t kSpdyStreamMaxRecvWindowSize = 6 * 1024 * 1024;    //  6 MB

**Comment by tzugen** [comment] 2022-07-27 13:00
We (Ultrasonic App) are affected by this.
The HTTP2 spec forbids adding a Connection header:
https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2.2

Will this happen if we use the suggested workaround? Or is the Connection: Close header simply an internal signal for Ok?

**Comment by tzugen** [comment] 2022-07-28 08:35
> Are you also hitting this with exoplayer, or with another client?
> 
> I ask because ExoPlayer interrupts threads which can leave open streams. I have tried to patch the most prevalent case but doubt I've fixed them all.
> 
> I'm wondering if it's similar. It probably isn't as described originally.
> 
> ExoPlayer is pretty good at closing old streams, it's OkHttp that doesn't handle a cancel via interrupts.

Yes, we are using androidx/media3 which is the upcoming version of what used to be Exoplayer.

**Comment by yschimke** [comment] 2022-07-28 10:24
If you have a repro with the latest media3 (beta02), I'd love to dig in, to see what else we can do to make it handle this cleanly. Once I have a repro, it's easier to debug.

**Comment by tzugen** [comment] 2022-07-28 10:39
@nitehu Can you provide a server where yschminke could reproduce the issue?

**Comment by nitehu** [comment] 2022-07-28 13:09
Yep. Unfortunately it can't be reproduced with the Ampache test server anymore, it seems they disabled http2, or just set the stream number on their side. But I've just created a demo server with some free music: https://amp2.qc.to, user: demo, pass: demodemo (enable Force Plain Password).
The problem can be (sometimes) reproduced by:
- Select songs - random, then play all (in upper right corner)
- Ultrasonic buffers the first three songs, tap on the fourth one in the playlist
- The next three is buffered, tap on the fourth again
- Repeat. Sooner or later it will freeze and timeout...

**Comment by tzugen** [comment] 2022-07-29 07:57
And the Code is here: https://gitlab.com/ultrasonic/ultrasonic , use the develop branch

**Comment by tzugen** [comment] 2022-07-30 06:22
Correction, my co-contributor has just merged a change disabling HTTP2 into develop. Here's a branch for you for debugging:
https://gitlab.com/ultrasonic/ultrasonic/-/tags/withHTTP2

**Comment by yschimke** [comment] 2022-07-31 12:53
I wasn't able to reproduce the problem yet.

It looks like you have custom logic for Downloading - Downloader and RESTMusicService.  So fixes to ExoPlayer's Downloader, probably dont help.  Is that a safe assumption?  Do you use any bits from ExoPlayer here?

Can you point me at all the request and cancellation logic, how do you stop the previous streams that are no longer are being consumed? Is it always here in Downloader?

```        @Suppress("LongMethod", "ComplexMethod", "NestedBlockDepth")
        override fun execute() {
...
                if (needsDownloading) {
                    // Attempt partial HTTP GET, appending to the file if it exists.
                    val (inStream, isPartial) = musicService.getDownloadInputStream(
                        downloadFile.track, fileLength,
                        downloadFile.desiredBitRate,
                        downloadFile.shouldSave
                    )
                    ...
            } finally {
                inputStream.safeClose()
```                

I've seen ExoPlayer in other apps stall when seeking around the same track, which is fixed in ExoPlayer, by changing how cancellation was happening. Avoiding any thread.interrupts and cleanly using InputStream.close() or call.cancel().

So I'm trying to reproduce the problem with enough information to show that we are cleanly cancelling in all cases, and so should be sending a RST_STREAM to the server.

**Comment by yschimke** [comment] 2022-07-31 16:20
How testable is the code? Is it feasible to write an instrumentation test and call that code path predictably?

**Comment by nitehu** [comment] 2022-08-01 06:54
> I wasn't able to reproduce the problem yet. But thanks for the branch and the test server. Can I keep using it for a couple of weeks?

Yes, I can leave it online for a few weeks.

>  So fixes to ExoPlayer's Downloader, probably dont help. Is that a safe assumption? Do you use any bits from ExoPlayer here?

I'm not really sure, but it's true that Exoplayer in itself doesn't cause the problem. As you see, during the playback of Exoplayer, we simultaneously start to cache a few songs in Downloader. The Timeout always comes when Exoplayer and Downloader are working at the same time, both downloading streams from the server.
Actually, it seems while Exoplayer is streaming, simple HTTP GET requests (like listing songs) to the server can timeout too sometimes, it's just easier to reproduce with caching songs.

> How testable is the code? Is it feasible to write an instrumentation test and call that code path predictably?

It can be tried, but I'm afraid it's not that deterministic.
[This post is from the original PR where we found this](https://github.com/ultrasonic/ultrasonic/pull/726#issuecomment-1117830856), it has some videos about the problem too. But it doesn't just timeout for the first try. 
The situation even got a little better since those videos were shot (maybe thanks to the Exoplayer guys' fixing something), but it isn't entirely fixed yet.

When we disable Http2, or send the "Connection: close" header (as was suggested above), everything works correctly. Unfortunately according to Http2 docs [that header is invalid](https://github.com/square/okhttp/issues/6749#issuecomment-1196707485) in this version.
One workaround would be if we could tell OkHttp to use a single TCP connection for a single stream, but currently that can't be configured (or at least we didn't found it)

**Comment by yschimke** [comment] 2022-08-01 07:55
This PR landed since then, which hopefully improves the Media3 side of things.

https://github.com/androidx/media/commit/80928e730c53729d147264a910fb327ba88be257

Previously quickly seeking around a track, could cause streams to be created and not closed.

I suggest we try to repro with media3 beta02, and maybe OkHttp 5.0 alpha10?, before spending too much time on this.

There are various ways you can force separate Http/2 connections but all a bit hacky/workarounds.  One is your own client pooling, with say a roundrobin approach. I have a sample of that if it comes to that. 

I might spend the time trying to warn when we get into these situation.

**Comment by yschimke** [comment] 2022-08-06 09:17
@tzugen @nitehu Before I dig into this more, can you let me know if you can reproduce with Media3 beta02? If so I'll dig in, and I'm motivated to get this working.  My work project uses Media3 and OkHttp so I'd like it to be rock solid.

**Comment by nitehu** [comment] 2022-08-06 09:27
Nope, we've just tested it a few days ago with beta2, and the timeout seems to be gone (after clicking through a few hundred songs we couldn't reproduce it).  
If you compare it closely with how Http1.1 worked, it seems to be slower, but every stream is completed eventually without errors. From a usability standpoint, this is good enough for us.

**Comment by yschimke** [comment] 2022-08-06 09:35
Thank you!  Is it slower generally, or just in this case when you are clicking through a lot of songs?
We do end up consuming a lot more from servers in these cases, and cancelling via RST_STREAM. So I'm not surprised, but I'd hope it sorts itself out within a small number of seconds.

If you are motivated enough, you can workaround the OkHttp limitation with some custom Call.Factory implementing a load balancer.  https://github.com/square/okhttp/pull/7280/files

It's a long term goal to support this in OkHttp itself but not clear when or how https://github.com/square/okhttp/issues/4530

**Comment by nitehu** [comment] 2022-08-06 10:12
It is generally slower. Maybe I just see this because I have preconceptions, but it is slower like if it is using a single TCP channel for all the streams :)  
With Http1.1 you can see everything (even 4-5 streams at once) downloading in parallel. With Http2, it starts downloading 1-2 streams, then pauses and loads half of another stream, then finishes a previous, then gets back to a new one...  
Actually I think our users won't even notice this, because everything finishes in a couple of seconds, and noone will inspect the progress this closely. I have a few hours in figuring this out, so maybe I have too keen eyes for it.

The load balancer seems like a simple enough workaround, maybe we'll give it a try.
Thank you for your help!

**Comment by yschimke** [comment] 2022-08-06 10:18
@nitehu No problem, happy to help.  If you can make a clear reproduction, then I can dig in further, even if it's just showing that multiple streams are slower.  If it's faster because you get multiple servers sending content, then only something like load balancing can help.  If it's slower because of contention inside OkHttp, then we should understand it.

**Comment by yschimke** [comment] 2022-08-06 11:03
I'm going to close this unless we can get a new repro since the fixes.

**Closed by yschimke** 2022-08-06 11:03 UTC
Labels: enhancement
