### ISSUE TITLE
how to support the digest authentication

### ISSUE THREAD

**Issue by carson2440** [square/okhttp#2290] opened 2016-01-28 09:32 UTC
dear all . 
the okhttp how to support digest authentication?

**Comment by nithdi** [comment] 2016-01-28 14:40
There is a 3rd party library available: https://github.com/rburgst/okhttp-digest

However, +1 for official support in OkHTTP

**Comment by swankjesse** [comment] 2016-01-28 16:05
Duplicate of https://github.com/square/okhttp/issues/205

**Closed by swankjesse** 2016-01-28 16:05 UTC
