### ISSUE TITLE
5.0.0-alpha.12: java.lang.IllegalStateException: Unable to load /okhttp3/internal/publicsuffix/a.gz resource from the classpath.

### ISSUE THREAD

**Issue by ahagelstein** [square/okhttp#8154] opened 2023-12-21 18:09 UTC
I have created a code sample which shows the issue.

- Android Studio Hedgehog | 2023.1.1
- OkHttp: 5.0.0-alpha.12
- Kotlin: 1.9.21
- Version of Gradle Plugin: id 'com.android.application' version '8.2.0'
- Version of Gradle: gradle-8.5-bin.zip
- OS: Windows 11 22H2

Steps to Reproduce:

Compile and run the following code in release mode (with minifyEnabled = true and shrinkResources = true).

```
class MainActivity : ComponentActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {

        super.onCreate(savedInstanceState)

        PublicSuffixDatabase.get().getEffectiveTldPlusOne("com")
    }
}
```

Result:

```
Caused by: java.lang.IllegalStateException: Unable to load /okhttp3/internal/publicsuffix/a.gz resource from the classpath.
                                                                                                    	at w3.a.a(Unknown Source:479)
                                                                                                    	at de.telekom.testapp.MainActivity.onCreate(Unknown Source:12)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:6975)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
                                                                                                    	at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                                                    	at android.os.Looper.loop(Looper.java:164) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

With Android Studio Hedgehog (or the new Gradle plugin) something within R8 changes. I have also observed changes with obfuscation.
@yschimke: I think your comment that the code is not R8 safe was correct (see https://github.com/square/okhttp/pull/7827).

**Comment by ahagelstein** [comment] 2023-12-22 10:32
@yschimke : Is it possible to load the public suffix database with this line of code ```context.resources.openRawResource(id).buffered().use { GzipSource(it.source()).buffer().use { ... }}``` ??

**Comment by yschimke** [comment] 2023-12-22 18:54
Just tested on a different app with AGP 8.1.4 and also 8.2.0 and both are working.

I'll need to see what is different.

**Comment by yschimke** [comment] 2023-12-22 19:00
Can you commit your repro as a github project, so I can run against it without making assumptions about what differs?

**Comment by yschimke** [comment] 2023-12-22 19:07
8.3.0-alpha17 also working.

**Comment by ahagelstein** [comment] 2023-12-22 23:10
Yes of course, here is the repro: https://github.com/ahagelstein/OkHttpIssue

And please note that the "debug" version is working. But not the "release" version.

**Comment by ahagelstein** [comment] 2023-12-22 23:23
Here are the results of the APK analyzer.
The path to the "PublicSuffixDatabase" is obfuscated.

![image](https://github.com/square/okhttp/assets/7000310/d4241025-7830-45a3-9478-83db13eaf033)

**Comment by yschimke** [comment] 2023-12-23 09:49
Thanks for the repro. My mistake in testing, even setting a CookieManager is not enough! 

But `url.topPrivateDomain()` is enough to trigger the failure.

I'll try to work out a workaround, and then the right fix and discuss timing of the next release with @swankjesse

**Comment by ahagelstein** [comment] 2023-12-23 10:04
I think the problem is the obfuscation for the resource folder. The assets folder is not part of the obfuscation. Is it possible to store to database there?

**Comment by yschimke** [comment] 2023-12-23 10:19
Can you try with these proguard rules?

```
-keeppackagenames okhttp3.internal.publicsuffix.*
-adaptresourcefilenames okhttp3/internal/publicsuffix/PublicSuffixDatabase.gz
```

**Comment by yschimke** [comment] 2023-12-23 10:20
I think the problem is here

```
    val PUBLIC_SUFFIX_RESOURCE = "/okhttp3/internal/publicsuffix/${PublicSuffixDatabase::class.java.simpleName}.gz".toPath()
```

The classname gets updated, but the package name is left, and no longer matches.

**Comment by ahagelstein** [comment] 2023-12-23 10:40
Yes, with the proguard rule `-keeppackagenames okhttp3.internal.publicsuffix.*` the issue is fixed.
The other rule `-adaptresourcefilenames okhttp3/internal/publicsuffix/PublicSuffixDatabase.gz` is already defined here https://github.com/square/okhttp/blob/master/okhttp/src/main/resources/META-INF/proguard/okhttp3.pro

**Comment by ahagelstein** [comment] 2023-12-23 10:43
> I think the problem is here
> 
> ```
>     val PUBLIC_SUFFIX_RESOURCE = "/okhttp3/internal/publicsuffix/${PublicSuffixDatabase::class.java.simpleName}.gz".toPath()
> ```
> 
> The classname gets updated, but the package name is left, and no longer matches.

Yes I think so. My idea was to use the complete full qualified name:

```
val PUBLIC_SUFFIX_RESOURCE = "/${PublicSuffixDatabase::class.qualifiedName?.replace(".", "/")}.gz".toPath()
```

**Comment by yschimke** [comment] 2023-12-23 12:05
Put up a PR with more effective tests.

**Comment by ahagelstein** [comment] 2023-12-23 12:24
Perfect, thanks!!

**Comment by yschimke** [comment] 2023-12-24 08:33
Closing, will be fixed in next release.

For anyone else, add the following proguard config if you need it.

```
-keeppackagenames okhttp3.internal.publicsuffix.*
-adaptresourcefilenames okhttp3/internal/publicsuffix/PublicSuffixDatabase.gz
```

**Closed by yschimke** 2023-12-24 08:33 UTC
Labels: bug
