### ISSUE TITLE
OkHttp + HTTP2 + ExoPlayer (media3): only the first 16 MiB of audio data is audible

### ISSUE THREAD

**Issue by mhelder** [square/okhttp#8418] opened 2024-05-23 11:29 UTC
## Summary
We build and maintain several apps that offer live and on-demand audio playback capabilities. For this, we heavily rely on OkHttp and ExoPlayer (now media3). It took us a while to narrow this down, but in a nutshell we've discovered that there's a combination of **OkHttp**, **ExoPlayer** and (some) hosts serving content over **HTTP2** that causes:
- OkHttp to gradually load audio data until it reaches 16 MiB, after which the request stops.
- Within this 16 MiB of audio data, ExoPlayer will happily play audible audio. Once it gets beyond that 16 MiB, ExoPlayer continues playback, progress keeps progressing, but there will be no audible audio.

We're not 100% sure if it's OkHttp or ExoPlayer, but given our investigation (see further below) so far, we feel this is the best place to start looking into this issue in more detail.

## Reproducer
A sample to reproduce this can be found here: https://github.com/mhelder/okhttp-media3-http2-16mb-issue

Follow these steps:
- Build and deploy sample app
- Hit the button labeled "❌ Player w/ OkHttp stack (HTTP2)"
- Playback will start at high speed. It'll be gibberish, but the point is you can hear audio.
- Wait for a bit for the progress to reach ~17:25 min. <span>@</span>128kbps, this is the 16 MiB mark. (Don't seek/scrub!)
- Playback seemingly continues, but you'll hear no more audio. You can even pause and resume, after which the silence remains.

Also worth mentioning:
- If you run everything through a proxy (e.g. Charles), at around 6:15 min of playback, 16 MiB of data will have been loaded. This is the point where the proxy reports the request as 'completed' normally. But the actual audio file size is ~31.1 MiB (33:57 min), so there's more data to load. The `content-length` header correctly reflects that. (At this point, nothing is reported (yet) when I attach an [`EventListener`](https://github.com/square/okhttp/blob/master/okhttp/src/main/kotlin/okhttp3/EventListener.kt)),
- At around 15:25 min of playback, the buffer indicator on the progress bar jumps all the way till the end. This seems to be the point where the audio is suddenly considered to be 16 MiB in size, instead of the actual 31.1 MiB. With an [`EventListener`](https://github.com/square/okhttp/blob/master/okhttp/src/main/kotlin/okhttp3/EventListener.kt) attached, this is where `responseBodyEnd` -> `connectionReleased` -> `callEnd` are reported. No failures or anything else out of the ordinary seems to happen.
- Seeking or scrubbing affects everything described above. In fact, it's how you - as a user - can 'fix' hearing no more audio.

## Investigation
The sample app contains a few things we've investigated using the same audio file. Each of these options matches one of the buttons in the sample app, so you can also try yourself:
- ❌ Use ExoPlayer with OkHttp, and allow HTTP2 - the default. This doesn't work, as described above.
- ✅ Use ExoPlayer with OkHttp, but limit protocol to HTTP1.1. This works.
- ✅ Use ExoPlayer with default network stack (`UrlConnection`-based, uses HTTP1.1). This works.
- ✅ Use ExoPlayer with [Cronet](https://developer.android.com/media/media3/exoplayer/network-stacks#cronet) (Play services-based): This works.

On top of that, we also verified the following:
- ❌ Use OkHttp5: [`5.0.0-alpha.14`](https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-500-alpha14). Same problem.
- ❌ Use ExoPlayer from before it became Media3. Same problem.
- ❌ Use latest Media3 alpha: [`1.4.0-alpha01`](https://developer.android.com/jetpack/androidx/releases/media3#1.4.0-alpha01). Same problem.
- ✅ Use a different audio file (with same bitrate) from a different host that also serves over HTTP2: [link](https://content.production.cdn.art19.com/validation=1716547227,9e5c1d42-eed0-5c8e-a936-f96522149954,5HPygAGLOC7wi3HKxXCO6eYUdsI/episodes/0eac3472-ea08-470d-8245-2aa7548a6c4a/3b2a6a78ba2351ca51e46e6d096f9227f0baaf126972b924ec3813ddaae196264d4b53f6793f3b1ea7068e30775c712d4091329d5d5d0c9146a2046e389772b2/Bitch_mixdown.mp3). Works! (Note: this file might become unavailable at some point)

And finally, we tried cutting out Media3 and directly use OkHttp to make a request to the audio file:
```kotlin
okHttpClient.newCall(
    Request.Builder().get().url(mediaUrl).build()
).enqueue(object: Callback {
    override fun onFailure(call: Call, e: IOException) { ... }
    override fun onResponse(call: Call, response: Response) {
        // do something
    }
})
```

The result depends on what we do in `onResponse`:
- If we don't read from the response stream, we observe the same behaviour as with Media3: the request completes after ~47 seconds.
- If we do read from the response stream, the whole audio file (all 31.1 MiB) gets downloaded.

## Conclusion (so far)
Given above, what we've been able to establish so far is that it appears to be a combination of OkHttp and HTTP2 on **some** hosts: e.g. it fails for content from tritondigital.com, but not art19.com. Could this imply the host misbehaving, or perhaps timing out because no data is being read for too long? Would that warrant looking into Media3's `OkHttpDataSource`? But since it does work correctly with Cronet, hopefully there also a way to make it work with OkHttp, and still leverage HTTP2.

The workaround we use for now in our apps is to derive an OkHttp instance from our app-wide singleton and force it to HTTP1.1. But we're not really sure where to go from here. Any help, pointers and ideas would be appreciated!

**Comment by yschimke** [comment] 2024-05-23 14:36
Wow, thanks for the detailed repro. I'll take a look briefly on the weekend.

I'm familiar with exoplayer, so hopefully can poke around. The repro with only okhttp looks helpful.

**Comment by yschimke** [comment] 2024-05-23 14:40
OkHttp generally prefers you to consume the responses if you want more data to be read. If you don't read, everything should work but eventually stream flow control should mean the server stops sending fresh data.

But that doesn't explain why it doesn't resume sending after it's evetually consumed.

**Comment by yschimke** [comment] 2024-05-23 16:32
I'm exploring on this branch https://github.com/square/okhttp/pull/8419/files

It shows the logging we have for Http2 frames and also flow control. But probably nothing more until the weekend. And the logging may be confusing.

**Comment by yschimke** [comment] 2024-05-24 10:50
It looks like an issue with the server. 

Testing on an OkHttp branch showed expected behaviour. OkHttp doesn't update the flow control window, as the client hasn't consumed the bytes.  Once the window is exhausted (16mb) the server should stop sending and wait for the client to request more.

```
12:44:59.296  D  >> CONNECTION 505249202a20485454502f322e300d0a0d0a534d0d0a0d0a
12:44:59.297  D  >> 0x00000000     6 SETTINGS      
12:44:59.297  D  >> 0x00000000     4 WINDOW_UPDATE 16711681
...
12:45:01.741  D  << 0x00000005     9 DATA          
12:45:01.741  D  << 0x00000005  4570 DATA          
12:45:01.742  D  >> 0x00000000     4 WINDOW_UPDATE 8389495
12:45:46.441  D  << 0x00000005     0 DATA          END_STREAM
12:45:50.208  D  >> 0x00000005     4 WINDOW_UPDATE 8396084
12:45:50.255  D  << 0x00000005     4 RST_STREAM    
```

But it looks like the server closed the stream cleanly as if the end of the data.

**Comment by yschimke** [comment] 2024-05-24 10:55
A branch with some extra logging. I should have forked but wanted to try to avoid creating lots of repos, it didn't work well.

https://github.com/yschimke/reproduce/tree/okhttp_logging

**Comment by yschimke** [comment] 2024-05-24 10:56
I'm going to close this, but happy to continue the discussion on the closed issue.

Thanks for the great repro, it was amazingly helpful.

**Closed by yschimke** 2024-05-24 10:56 UTC
Labels: bug

**Comment by mhelder** [comment] 2024-07-03 06:57
Apologies for the delayed reply - many thanks for looking into this @yschimke!

Any theories on why we don't see the same happening with Cronet (which will also leverage HTTP2)? Is it related to the size of control flow window? Any other 'controls' that could affect why we're not seeing consistent behaviour with different clients using the same protocol? 
I would love to dig a little deeper and figure out what's different, but wouldn't really know where to start. Is there tooling that would allow me to inspect communication at the protocol layer? Perhaps some sort of proxy?

I've also been trying to get Triton Digital involved, but - as I'd feared - it's proven difficult to get past the first line of support.

**Comment by yschimke** [comment] 2024-07-03 07:57
No, but you should be able to see via Wireshark or NetLog? 

I'd speculate that Cronet's Request Callback means the app is driving the flow control more than OkHttp allows

https://developer.android.com/develop/connectivity/cronet/lifecycle

https://developer.android.com/develop/connectivity/cronet/reference/org/chromium/net/UrlRequest.Callback.html#onReadCompleted(org.chromium.net.UrlRequest,%20org.chromium.net.UrlResponseInfo,%20java.nio.ByteBuffer) 

For tools you want something that can decrypt a TLS connection, and store a PCAP, or hook into Wireshark. Maybe something like https://docs.mitmproxy.org/stable/howto-install-system-trusted-ca-android/ ?
