### ISSUE TITLE
EOFException when there is no HTTP response

### ISSUE THREAD

**Issue by vivekmuniyandi** [square/okhttp#3629] opened 2017-09-25 23:04 UTC
I am getting the following exception when the server is down and there is no response for the request.
```
java.io.IOException: unexpected end of stream on Connection{rh7v-intel64-90-java-stress-4.marklogic.com:8000, proxy=DIRECT hostAddress=rh7v-intel64-90-java-stress-4.marklogic.com/172.18.132.248:8000 cipherSuite=none protocol=http/1.1}
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:205)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at com.burgstaller.okhttp.AuthenticationCacheInterceptor.intercept(AuthenticationCacheInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:674)
	... 13 more
Caused by: java.io.EOFException: \n not found: limit=0 content=…
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSurce.java:211)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	... 32 more

```
Capturing the trace in wireshark shows that the request has been sent but the server doesn't respond, not even a status code. In that case, I am getting this exception which is very misleading. It would be good to have a more appropriate exception for cases where there is no response from the server. Thanks.

**Comment by yschimke** [comment] 2017-09-26 04:47
What would you want as the exception message?  At first reading this exception seems very appropriate to the problem without being worded as a specific help message telling you to contact the webserver owner.

**Comment by sammefford** [comment] 2017-09-26 15:50
I work with Vivek.  I don't think he's looking for a different message as much as a more specific exception so he can catch it and do something in application code to handle it.  Both IOException and EOFException are too generic to handle for this particular situation.  We try to avoid code based on parsing exception messages since that's brittle code.  

As an example of what we'd like, we currently handle SocketException and UnknownHostException by retrying the request on another node.  We'd like to do similar in this situation for idempotent requests, but not for requests with possible unknown side effects.  In other words, we know how we'd like to handle this situation in our code, but we don't have a reliable way to identify this situation based on the generic exception types.  Hoping that helps clarify.

**Comment by yschimke** [comment] 2017-09-30 16:38
If the server just isn't responding you should get a SocketTimeoutException.  e.g.

```
java.net.SocketTimeoutException: timeout
 at okio.Okio$4.newTimeoutException(Okio.java:230)
 at okio.AsyncTimeout.exit(AsyncTimeout.java:275)
 at okio.AsyncTimeout$2.read(AsyncTimeout.java:243)
 at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
 at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
 at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
 at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:187)
 at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
```

Which has a nice exception.  The problem here is that the server is seemingly closing your socket without sending an appropriate response e.g. 503.

I don't think it is appropriate to make the exceptions for badly behaved servers effectively part of the published API.  For expected failure modes (5xx, 4xx, timeout exceptions) they effectively are.

Have you considered checking whether the cause of a generic IOException is more helpful? in this case the EOFException?  I don't promise this won't change, but I don't think we are likely to special case this issue you raised.

**Comment by yschimke** [comment] 2017-09-30 16:57
reopen if you want to discuss further

**Comment by swankjesse** [comment] 2017-10-02 17:47
The server returned fewer bytes than required; this is exactly what `EOFException` is for. When you say “EOFException is too generic” what other situations are you using EOFException for?

**Comment by sammefford** [comment] 2017-10-02 18:09
We're not using EOFException for anything, just as we're not using IOException for anything, since they could mean many things.  I could see EOFException applying to a mal-formed multipart response, a truncated HTTP response, or a failure to write to a temp file ( for an overly large response).  I guess you could tell me "this is the only way we use EOFException, and we will never use it for some different scenario" and we could trust that.  But would you agree that we'd want a different exception if you get a partial response (most notably if we get the HTTP status)?

**Comment by sammefford** [comment] 2017-10-02 18:17
To be clear, the HTTP status would give us a hint if the request was received and processed by the server.   
 For idempotent requests we're going to retry when we get no response.  

But for non-idempotent requests we don't want to retry the request against a different node if there's a chance the first request was received and processed.  If we knew the status was a 500-series we know we could retry against another node.  But if the request was sent and we don't get a response we have to assume the request might have been processed and thus we'll error out rather than retry against another node.

**Comment by swankjesse** [comment] 2017-10-02 18:55
If you get a 5xx response, please don’t interpret that as “the request was not processed”. 5xx means that something broke inside the server, and that thing that broke might not have broken until after the request was processed.

I don’t think it’s a good idea for OkHttp to provide partial response data when the response headers are truncated. Do browser user agents do this?

**Comment by yschimke** [comment] 2017-10-05 05:35
So this doesn't keep hanging, I think the answer is that we don't have plans to make the exact exception types or messages public API such that you can unambiguously separate out these different cases now and with absolute certainty in future versions.

For now you can check for a EOFException in the chain, or the message but this isn't public API.  No plans to change however.

**Closed by yschimke** 2017-10-05 05:35 UTC

**Comment by sammefford** [comment] 2017-10-06 22:57
Thanks, Yuri and Jesse, for the due diligence.

**Comment by Kolyall** [comment] 2018-02-15 14:18
@sammefford @vivekmuniyandi how did you resolve the issue?

**Comment by tarmac-dunamu** [comment] 2025-02-04 00:25
I want to share my experience.
I got similar error message like below
```
IOException
unexpected end of stream on http://<my host>:8080/...

...

EOFException
\n not found: limit=0 content=…
```
and the reason was due to too long url length.
After I changed to shorted request url length, it solved.
I'm not sure if this is same to you guys but try it if you don't have any options.
