### ISSUE TITLE
Feature request: Configurable minimum idle connections

### ISSUE THREAD

**Issue by mxnightingale** [square/okhttp#6663] opened 2021-05-04 23:52 UTC
I have an application that connects to a few different hosts and sends very bursty traffic, often from zero to thousands of requests instantly. After periods of inactivity, my latency graph spikes up and then smooths out when burst traffic starts up again. I suspect I'm burning a bunch of time establishing connections when the load starts.

**Comment by yschimke** [comment] 2021-05-05 12:24
Close to https://github.com/square/okhttp/issues/4530 and https://github.com/square/okhttp/issues/5950

**Comment by mxnightingale** [comment] 2021-06-15 22:17
Update: I implemented EventListener and found this to be the case. Bursts of traffic sometimes back up spending seconds waiting for new connections.

**Comment by yschimke** [comment] 2021-06-18 05:21
OkHttp will collapse these down as soon as it's clear that a single connection can be reused in the case of HTTP/2.  But until then it will start new connections in case.  You can send an earlier warmup HEAD request to /robots.txt or similar to avoid this when the burst comes.

Are you using execute or enqueue? Execute is slightly more aggressive in how it starts new connections, but limits should be being maintained.

Anyway, closing as a duplicate of other bug reports, this is mostly expected behaviour.

**Comment by mxnightingale** [comment] 2021-06-18 14:41
Thanks for the review @yschimke. I understand this may be the current expected behavior but it leads to poor performance in the scenario I outlined, hence the new feature request to add some configurability. Just want to make sure it is understood this is a new feature request and not a bug report.

**Comment by yschimke** [comment] 2023-05-21 09:05
Closing in favour of https://github.com/square/okhttp/issues/4530

**Closed by yschimke** 2023-05-21 09:05 UTC
Labels: enhancement
