### ISSUE TITLE
Call.cancel shouldn't offend strict mode

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#1592] opened 2015-04-29 04:33 UTC
We should document that it doesn't block, and get our friends at AOSP to fix strict mode to not issue a false positive warning.

**Comment by nfuller** [comment] 2015-04-29 07:24
Do you have a stack trace? Is it one of these cases where it calls a potentially blocking POSIX call that, in practice, will never block with the way the sockets are configured?

**Comment by swankjesse** [comment] 2015-04-29 12:05
It's related to this issue, which has come up again: https://github.com/square/okhttp/issues/869

**Comment by nfuller** [comment] 2015-04-29 13:37
I'm not up on conscrypt. From a quick skim of the code: when it closes it looks like it sets the socket into blocking mode, then calls SSL_shutdown, which is documented to potentially block. If that's correct it looks like the call to block guard is at least correct with the current implementation.

What makes you think it's a false positive?

**Comment by swankjesse** [comment] 2015-04-30 03:55
Hmmm . . .  . What I want is to quickly & violently break a socket that isn't needed anymore. This isn't intended to be a clean shutdown that flushes queued bytes; instead it just severs the network. Perhaps for SSL we need to break the underlying socket only, which shouldn't require any blocking.

**Comment by nfuller** [comment] 2015-04-30 15:51
The block guard code for close() appears to be smart enough to check for linger and only complain if they have it set. AFAIK, the HTTP sockets shouldn't have it set, so it will be classed as non-blocking.

**Comment by Wavesonics** [comment] 2015-05-05 17:14
I've got a stack if it helps:

android.os.NetworkOnMainThreadException
            at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1145)
            at com.android.org.conscrypt.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:1009)
            at com.squareup.okhttp.Connection.closeIfOwnedBy(Connection.java:142)
            at com.squareup.okhttp.OkHttpClient$1.closeIfOwnedBy(OkHttpClient.java:71)
            at com.squareup.okhttp.internal.http.HttpConnection.closeIfOwnedBy(HttpConnection.java:136)
            at com.squareup.okhttp.internal.http.HttpTransport.disconnect(HttpTransport.java:135)
            at com.squareup.okhttp.internal.http.HttpEngine.disconnect(HttpEngine.java:507)
            at com.squareup.okhttp.Call.cancel(Call.java:122)
            ...

**Comment by iNoles** [comment] 2015-05-05 17:52
@Wavesonics you supposed to run any network call on background thread.

**Comment by JakeWharton** [comment] 2015-05-05 17:52
@iNoles that is not the issue

**Comment by Wavesonics** [comment] 2015-05-05 17:55
@iNoles the issue is that calling cancel() on a connection from the main thread triggers the OS's block guard. This is a quick call and shouldn't trigger that protection.

**Comment by swankjesse** [comment] 2015-08-02 00:09
Should be pretty straightforward after this PR lands:
https://github.com/square/okhttp/issues/1592

We'll need to keep both the raw socket and the SSL socket. When closing asynchronously we close the raw socket; when cleaning up or closing synchronously we close both.

**Comment by swankjesse** [comment] 2015-08-02 00:10
Also we should be precise around concurrency on access to the transport & connection. Right now it's not safe.

**Comment by swankjesse** [comment] 2015-08-03 01:04
I'm going to punt this to 3.0, only because not involving `HttpURLConnection` will make this much easier.

**Comment by lawloretienne** [comment] 2015-09-15 23:03
Are there any updates on this?  I'm also getting a `android.os.NetworkOnMainThreadException` from `Call.cancel()`

    09-15 15:52:20.205 6069-6069/com.etiennelawlor.loop E/AndroidRuntime: FATAL EXCEPTION: main
    09-15 15:52:20.205 6069-6069/com.etiennelawlor.loop E/AndroidRuntime: Process: com.etiennelawlor.loop, PID: 6069
    09-15 15:52:20.205 6069-6069/com.etiennelawlor.loop E/AndroidRuntime: android.os.NetworkOnMainThreadException
    09-15 15:52:20.205 6069-6069/com.etiennelawlor.loop E/AndroidRuntime:     at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1273)
    09-15 15:52:20.205 6069-6069/com.etiennelawlor.loop E/AndroidRuntime:     at com.android.org.conscrypt.OpenSSLSocketImpl.shutdownAndFreeSslNative(OpenSSLSocketImpl.java:1126)
    09-15 15:52:20.205 6069-6069/com.etiennelawlor.loop E/AndroidRuntime:     at com.android.org.conscrypt.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:1121)
    09-15 15:52:20.205 6069-6069/com.etiennelawlor.loop E/AndroidRuntime:     at com.squareup.okhttp.Connection.closeIfOwnedBy(Connection.java:148)
    09-15 15:52:20.205 6069-6069/com.etiennelawlor.loop E/AndroidRuntime:     at com.squareup.okhttp.OkHttpClient$1.closeIfOwnedBy(OkHttpClient.java:75)
    09-15 15:52:20.205 6069-6069/com.etiennelawlor.loop E/AndroidRuntime:     at com.squareup.okhttp.internal.http.HttpConnection.closeIfOwnedBy(HttpConnection.java:137)
    09-15 15:52:20.205 6069-6069/com.etiennelawlor.loop E/AndroidRuntime:     at com.squareup.okhttp.internal.http.HttpTransport.disconnect(HttpTransport.java:135)
    09-15 15:52:20.205 6069-6069/com.etiennelawlor.loop E/AndroidRuntime:     at com.squareup.okhttp.internal.http.HttpEngine.disconnect(HttpEngine.java:573)
    09-15 15:52:20.205 6069-6069/com.etiennelawlor.loop E/AndroidRuntime:     at com.squareup.okhttp.Call.cancel(Call.java:122)
    09-15 15:52:20.205 6069-6069/com.etiennelawlor.loop E/AndroidRuntime:     at retrofit.OkHttpCall.cancel(OkHttpCall.java:158)
    09-15 15:52:20.205 6069-6069/com.etiennelawlor.loop E/AndroidRuntime:     at retrofit.ExecutorCallAdapterFactory$ExecutorCallbackCall.cancel(ExecutorCallAdapterFactory.java:63)

**Comment by lawloretienne** [comment] 2015-09-25 18:05
I guess I have to wrap the `Call.cancel()` method in an `AsyncTask` until this gets resolved.
            
```java
new CancelTask().execute(call);

private class CancelTask extends AsyncTask < Call, Void, Void > {@
    Override
    protected Void doInBackground(Call...params) {
        Call call = params[0];
        call.cancel();
        return null;
    }
}
```

**Comment by felipecsl** [comment] 2015-09-25 18:22
@lawloretienne you can use the OkHttp dispatcher executor service for it:

```
client.getDispatcher().getExecutorService().execute(new Runnable() {
    @Override
    public void run() {
        call.cancel();
    }
});
```

**Comment by jurenovic** [comment] 2015-10-21 07:20
Any news on this one?

**Comment by ubuntudroid** [comment] 2015-11-22 12:23
Calling `unsubscribeOn(Schedulers.io())` fixed the issue for me for the time being. Found the solution [here](https://github.com/prt2121/RxJava-Android-Samples/commit/1f235bd16821b7ea8139676dae711fae4b38eca4#diff-0eeeebe7aad15345f8833bae4c70056fR103).

**Comment by kzaemrio** [comment] 2015-11-23 15:03
@ubuntudroid Thanks, it works for me

**Comment by Wavesonics** [comment] 2015-11-25 01:25
Unfortunately all of these solutions involve doing it async. I have a use case that requires it to be deterministic so they won't work for me.

I see @swankjesse suggested punting this to 3.0, is that a wait and see about it in 3.0? Or do we expect 3.0 will inherently fix this because it's ditching HURL?

**Comment by swankjesse** [comment] 2015-11-25 01:30
I'm working on it for OkHttp 2.7.

**Comment by Wavesonics** [comment] 2015-11-25 01:42
@swankjesse Outstanding news! Do you have any super rough idea how much longer 2.7 will be in the oven?

**Comment by swankjesse** [comment] 2015-11-25 02:50
4–12 weeks!

**Closed** 2015-11-30 04:15 UTC
Labels: bug
