### ISSUE TITLE
ETAG invalidation

### ISSUE THREAD

**Issue by IvanStepanov** [square/okhttp#1712] opened 2015-06-20 09:02 UTC
Hello,

i'm facing strange behavior and i'm not sure is it a bug or desired behavior according to response headers.

Just doing 4 sequential requests for same resource/uri:
0. Cleanup client cache directory
1. Sending GET request - 200, ETAG was returned with response
2. Sending GET request - 304 (ETAG from 1 response was added to this request)
3. Manually change resource on the server which causes server-side ETAG update
4. Sending same GET request again - 200 (ETAG from 2 response was added to this request), server returns new ETAG in response because content was changed on step 3
5. Sending same GET request again - 200 (ETAG from 2 response was added to this request), i.e. client has not updated own cache for step 4 response. From now all new requests will be send with 'old' ETAG.

I'm using okhttp/2.4.0 and IIS 8.0 (ETAG caching is powered by CacheCow). Also i can confirm that both standard BCL .NET HttpClient and Apache Java Http Client will re-validate cache on 4th step.

Here is headers for all requests/responses (without some not interesting info like user agent, etc)

```
1.
GET http://localhost:5577/api/FeatureClasses HTTP/1.1
Cache-Control: max-age=0
accept: text/json; charset=utf-8
Host: localhost:5577
Connection: Keep-Alive
Accept-Encoding: gzip
--------
HTTP/1.1 200 OK
Cache-Control: public, must-revalidate, max-age=0
Transfer-Encoding: chunked
Content-Type: text/json; charset=utf-8
Content-Encoding: gzip
Last-Modified: Sat, 20 Jun 2015 08:16:44 GMT
ETag: W/"01115072cae94526b5023bae8d28bbd2"
Vary: Accept-Encoding
```
```
2. 
GET http://localhost:5577/api/FeatureClasses HTTP/1.1
Cache-Control: max-age=0
accept: text/json; charset=utf-8
Host: localhost:5577
Connection: Keep-Alive
Accept-Encoding: gzip
If-None-Match: W/"01115072cae94526b5023bae8d28bbd2"
--------
HTTP/1.1 304 Not Modified
Cache-Control: no-cache
Pragma: no-cache
Expires: -1
ETag: "01115072cae94526b5023bae8d28bbd2"
```
```
3.
GET http://localhost:5577/api/FeatureClasses HTTP/1.1
Cache-Control: max-age=0
accept: text/json; charset=utf-8
Host: localhost:5577
Connection: Keep-Alive
Accept-Encoding: gzip
If-None-Match: "01115072cae94526b5023bae8d28bbd2"
--------
HTTP/1.1 200 OK
Cache-Control: public, must-revalidate, max-age=0
Transfer-Encoding: chunked
Content-Type: text/json; charset=utf-8
Content-Encoding: gzip
Last-Modified: Sat, 20 Jun 2015 08:16:50 GMT
ETag: W/"00a90191ec19428abdbe3aedebfbc62e"
Vary: Accept-Encoding
```
```
4.
GET http://localhost:5577/api/FeatureClasses HTTP/1.1
Cache-Control: max-age=0
accept: text/json; charset=utf-8
Host: localhost:5577
Connection: Keep-Alive
Accept-Encoding: gzip
If-None-Match: "01115072cae94526b5023bae8d28bbd2"
--------
HTTP/1.1 200 OK
Cache-Control: public, must-revalidate, max-age=0
Transfer-Encoding: chunked
Content-Type: text/json; charset=utf-8
Content-Encoding: gzip
Last-Modified: Sat, 20 Jun 2015 08:16:50 GMT
ETag: "00a90191ec19428abdbe3aedebfbc62e"
Vary: Accept-Encoding
```

NOTE: it seems for me that weak etags is not an origin of such behavior.

**Comment by swankjesse** [comment] 2015-06-20 12:42
Are you reading the complete response body in step 4? OkHttp needs you to consume the response body to trigger the cache to be updated.

**Comment by swankjesse** [comment] 2015-06-20 14:51
I've created a test case for your scenario here:
https://github.com/square/okhttp/pull/1713/files

The test passes. If you'd like to provide a different test case that fails, please do. Otherwise I'm closing this bug because I cannot reproduce the problem.

**Closed** 2015-06-20 15:33 UTC

**Comment by IvanStepanov** [comment] 2015-06-21 04:19
Actually i have not readed/closed 304 responses body (some kind of optimization to not waste time on deserialization) so it cause such behavior. 
Thank you for your help.
