### ISSUE TITLE
NoSuchElementException

### ISSUE THREAD

**Issue by Spring-Xu** [square/okhttp#2160] opened 2015-12-27 03:10 UTC
java.util.NoSuchElementException
com.squareup.okhttp.internal.http.RouteSelector.com.squareup.okhttp.Route next()(SourceFile:79)
com.squareup.okhttp.internal.http.StreamAllocation.com.squareup.okhttp.internal.io.RealConnection findConnection(int,int,int,boolean)(SourceFile:164)
com.squareup.okhttp.internal.http.StreamAllocation.com.squareup.okhttp.internal.io.RealConnection findHealthyConnection(int,int,int,boolean,boolean)(SourceFile:126)
com.squareup.okhttp.internal.http.StreamAllocation.com.squareup.okhttp.internal.http.HttpStream newStream(int,int,int,boolean,boolean)(SourceFile:95)
com.squareup.okhttp.internal.http.HttpEngine.com.squareup.okhttp.internal.http.HttpStream connect()(SourceFile:283)
com.squareup.okhttp.internal.http.HttpEngine.void sendRequest()(SourceFile:224)
com.squareup.okhttp.Call.com.squareup.okhttp.Response getResponse(com.squareup.okhttp.Request,boolean)(SourceFile:286)
com.squareup.okhttp.Call$ApplicationInterceptorChain.com.squareup.okhttp.Response proceed(com.squareup.okhttp.Request)(SourceFile:243)
com.squareup.okhttp.Call.com.squareup.okhttp.Response getResponseWithInterceptorChain(boolean)(SourceFile:205)
com.squareup.okhttp.Call.com.squareup.okhttp.Response access$100(com.squareup.okhttp.Call,boolean)(SourceFile:35)
                         java.lang.String access$200(com.squareup.okhttp.Call)
com.squareup.okhttp.Call$AsyncCall.void execute()(SourceFile:171)
com.squareup.okhttp.internal.NamedRunnable.void run()(SourceFile:33)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
java.lang.Thread.run(Thread.java:818)

**Comment by swankjesse** [comment] 2015-12-27 03:47
Duplicate of #2151. Needs immediate investigation & probably a patch release.

**Closed by swankjesse** 2015-12-27 03:47 UTC
