### ISSUE TITLE
Support HTTP status 102 Processing

### ISSUE THREAD

**Issue by rfc2822** [square/okhttp#2257] opened 2016-01-17 15:15 UTC
There's a HTTP interim status code **102 Processing**. It's [defined in RFC 2518](http://tools.ietf.org/html/rfc2518#section-10.1) and can be found in the [HTTP Status Code Registry](http://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml).

Funnily, it has been [dropped in the revised WebDAV RFC 4918](http://tools.ietf.org/html/rfc4918#section-21.4), so I don't know whether it's worth dealing with it (RFC 4918 is from 2007 and 2518 from 1999!). However, it's still in the status code registry, and I have just encountered a quite large WebDAV service which uses this status code ([original case](https://forums.bitfire.at/topic/939/multiple-calendars-not-syncing/)).

It could be exactly treated as status code 100, so I guess adding it in Http1xStream would be enough?

```
// HTTP_PROCESSING: 102

 if (statusLine.code != HTTP_CONTINUE || statusLine.code != HTTP_PROCESSING)
// instead of
 if (statusLine.code != HTTP_CONTINUE)
```

What do you think about that?

**Comment by swankjesse** [comment] 2016-01-17 17:19
Works for me.

**Comment by rfc2822** [comment] 2016-01-17 17:40
Cool. :sunglasses: RFC 2616 even says:

> **A client MUST be prepared to accept one or more 1xx status responses prior to a regular response**, even if the client does not expect a 100 (Continue) status message. Unexpected 1xx status responses MAY be ignored by a user agent.

So maybe not only 102 should be added, but all 10x status codes. But as RFC 2616 is only a rough recommendation, I don't know whether this would be wise.

**Comment by swankjesse** [comment] 2016-01-17 17:44
The spec we care about is here:
http://tools.ietf.org/html/rfc7231#section-6.2

I think it’s a good idea to generalize our current `100` behavior to handle all 1xx codes.

**Comment by JakeWharton** [comment] 2016-01-18 03:54
There's an issue tracking 100's as #1337.

**Comment by JakeWharton** [comment] 2016-02-03 23:28
Closing as a dupe of #1337 and renaming it to say "1XX".

**Comment by guillerodriguez** [comment] 2018-06-27 09:50
Just came across this. See my comment in issue #1337. It was closed as a dupe of #675, which only added support for response code 100, but not for 102 (which was the original topic for this one).

**Comment by swankjesse** [comment] 2018-06-30 11:48
Agreed!

**Comment by yschimke** [comment] 2021-11-27 11:21
@nowkarol You seem to have put a lot of thought into how to make the change.  Please submit a PR.

We normally discourage external contributions because we try to keep the scope of the library tight and have very opinionated ideas about the APIs and so on.  It can be frustrating for new contributors.

So please take any feedback with this in mind :) And thanks for offering and putting so much thought into how to do it correctly.

**Comment by nowkarol** [comment] 2021-12-15 22:58
@yschimke Sure, will keep that in mind. So will try with very small chunks. [First one](https://github.com/square/okhttp/pull/6960) is about testing current MockWebServer behavior while using EXPECT_CONTINUE. Probably some of behaviors should be changed to comply with [RFC](https://datatracker.ietf.org/doc/html/rfc7231#section-5.1.1). After that I will be able to test and implement enqueuing of follow-up responses needed to test 102 Processing support.

**Comment by reschke** [comment] 2022-09-08 10:52
@yschimke - sorry for not checking before and submitting a dupe.

That said, this really needs to be treated as "bug", not an "enhancement".

**Closed** 2023-01-28 14:58 UTC
Labels: enhancement
