### ISSUE TITLE
Detect competing access to DiskLruCache; explode

### ISSUE THREAD

**Issue by kaciula** [square/okhttp#680] opened 2014-04-09 12:58 UTC
I'm getting crash reports from users of my Android app with the following stacktrace:

```
java.lang.RuntimeException: java.io.IOException
       at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:175)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)
Caused by: java.io.IOException
       at com.squareup.okhttp.internal.DiskLruCache.renameTo(DiskLruCache.java:390)
       at com.squareup.okhttp.internal.DiskLruCache.rebuildJournal(DiskLruCache.java:372)
       at com.squareup.okhttp.internal.DiskLruCache.access$300(DiskLruCache.java:86)
       at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:171)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)
```

Right now, all affected users are on Android 4.3

All I am doing is using a OkHttpClient singleton with a HttpResponseCache attached.

**Comment by abaotic** [comment] 2015-02-04 07:18
Hi!

Since yesterday my app is crashing due to this issue. I am using the 2.2.0 version. I too have multiple RestAdapters. I can remove the caching on all but one, but that seems like a workaround, not crashing the app seems too extreme in case of cache manipulation failure.
Crash distribution attached, hope you can make use of it.
![crashlytics](https://cloud.githubusercontent.com/assets/2296793/6036524/65a17f1e-ac46-11e4-860e-33ce38428464.png)

**Comment by JakeWharton** [comment] 2015-02-04 07:26
Just use the same `OkHttpClient` instance across all of them.

**Comment by rockerhieu** [comment] 2015-05-12 08:31
#646

**Comment by crossle** [comment] 2015-09-06 06:31
same issue

**Comment by yyjdelete** [comment] 2015-12-08 03:17
Why not just disable the cache instead of crash the app with RuntimeException when rebuildJournal failed with IOException?
Some times it's unavoidable and not able to fix, for example: `disk is full`, `android.system.ErrnoException: open failed: EROFS (Read-only file system)`(When directory( on FAT FS) is removed by cleaner while file is open, something cause an file lock before reboot)

**Comment by swankjesse** [comment] 2015-12-08 04:22
@yyjdelete that's the plan, we just need to implement it.

**Comment by dave-r12** [comment] 2016-02-03 13:20
Was going to try my hand at implementing this

**Comment by swankjesse** [comment] 2016-02-03 20:18
Please do! What’s the strategy? Pid lock?

**Comment by dave-r12** [comment] 2016-02-03 21:10
Not sure yet still researching, will look into pid locks.

**Comment by swankjesse** [comment] 2016-02-03 22:41
Cool. Trick is finding some way to tell the host OS that the current process owns the directory, in such a way that future processes can take over if that process dies.

**Comment by JakeWharton** [comment] 2016-02-03 22:47
There's also the possibility of competing access in-process. Nothing
prevents me from pointing two OkHttpClient instances at a single folder and
having journals that clobber each other constantly, I think.

**Comment by dave-r12** [comment] 2016-02-04 22:36
Got it, thanks. 

I started looking at using File#createNewFile() to atomically create a "lock" file. If it succeeds, we can take ownership of the cache directory, and any subsequent tries to create the same file would return false, meaning a separate process/thread already owns the directory. The issue is that the lock file needs to be cleaned up afterwards. We can guarantee that with a proper close() call, and even use File#deleteOnExit() as a backstop. But that only works for normal process termination. So I think that approach if off the table.

As an alternative, I was looking at java.nio.channels.FileLock. I've never used this API before, but it seems like a feasible approach. From what I saw, it's using fnctl() to acquire the file lock. My thinking is that we'd create a lock file in the cache directory, then attempt to acquire an exclusive file lock. If we can't acquire the lock, we can assume a separate thread/process has it and then explode. It feels like this would add a fair bit of complexity. Given the value returned and risk, I'm not sure it's worth it. Thoughts?

**Comment by swankjesse** [comment] 2016-02-05 00:12
I haven’t used FileLock. Seems like this would be using that exactly as intended.

**Comment by dave-r12** [comment] 2016-02-05 00:46
Alright, I'm going to study the internals more deeply and then I'll take a swipe at writing the code

**Comment by dave-r12** [comment] 2016-02-05 14:29
Ok, so there is at least one fundamental problem with FileLock, caused by fcntl(). In the case of multiple processes, FileLock works great.

Things break down in the case of a single process, notably from FileLock javadoc:
> On some systems, closing a channel releases all locks held by the Java virtual machine on the underlying file regardless of whether the locks were acquired via that channel or via another channel open on the same file. It is strongly recommended that, within a program, a unique channel be used to acquire all locks on any given file.

and from documentation on fcntl:
>record locks are automatically released when the process terminates or if it closes any file descriptor referring to a file on which locks are held. This is bad: it means that a process can lose the locks on a file like /etc/passwd or /etc/mtab when for some reason a library function decides to open, read and close it.

In the case of a single instance of OkHttp loaded in the VM, I think a workaround would be to use a class level lock.

When there are multiple instances loaded, the class level lock doesn't work. I'm thinking this might be an OSGi environment, concurrent versions of OkHttp in the same VM, or possibly the same version loaded multiple times (i.e. application server.) I'm not sure how to get around this one.

And all this to detect competing access! :)

**Comment by swankjesse** [comment] 2016-02-05 19:55
The case I’m most interested in is when an Android app has multiple processes, and because the two processes are configured identically they both attempt to open the cache simultaneously.

**Comment by swankjesse** [comment] 2016-02-05 19:55
...which is two processes competing with each other. I think that case is far harder for app developers to deal with than the same process fighting itself.

**Comment by JakeWharton** [comment] 2016-02-05 20:02
In-process competing could be as easy as a static AtomicBoolean on Cache
that was CAS'd to true when opened and false when closed and throwing on an
unexpected state.

**Comment by JakeWharton** [comment] 2016-02-05 20:03
Actually, I guess it'd have to be a synchronized Set or something of File
paths, since multiple instances can be open, just not pointing at the same
place.

**Comment by dave-r12** [comment] 2016-02-05 20:27
Right, and I believe a third case is, via a custom class loader, I load multiple instances of the OkHttp library into the same VM. This is the one I'm struggling with. It's possible, but unlikely?

If we can constrain this to, multi-process and single loaded instance of OkHttp library, then I believe the combination of FileLock + synchronized Set will work.

**Comment by dave-r12** [comment] 2016-02-05 20:43
Actually, never mind - if someone did try to load multiple copies of OkHttp into the same VM, it will also explode, which should prompt the developer to change their configuration. Apologies for the confusion

**Comment by swankjesse** [comment] 2016-02-05 21:23
I think if you’re doing fancy OSGi things you can get multiple copies of static fields. You need something like [ClassLoaderBuilder.](https://android.googlesource.com/platform/libcore/+/refs/heads/master/support/src/test/java/tests/util/ClassLoaderBuilder.java).

But I don’t think we care. If you shoot yourself in the foot by having multiple OkHttpClient instances in the same process, you have only yourself to blame. But if the user launches two instances of your process they shouldn't corrupt each other, as we do now.

**Comment by dave-r12** [comment] 2016-02-08 13:34
I took a pass at implementing this, but hit a snag while testing it on android. Can someone validate my understanding? According to the javadocs, I believe calling tryLock() should return null if an exclusive lock cannot be obtained, http://developer.android.com/reference/java/nio/channels/FileChannel.html#tryLock()

This works as expected on the desktop/server. But on android, I'm getting an IOException with this stack trace,

```
java.io.IOException: fcntl failed: EAGAIN (Try again)
  at java.nio.FileChannelImpl.basicLock(FileChannelImpl.java:123)
  at java.nio.FileChannelImpl.tryLock(FileChannelImpl.java:181)
  at java.nio.channels.FileChannel.tryLock(FileChannel.java:584)
  at com.daveroberge.multi_process.Main2Activity$1.run(Main2Activity.java:35)
Caused by: android.system.ErrnoException: fcntl failed: EAGAIN (Try again)
  at libcore.io.Posix.fcntlFlock(Native Method)
  at libcore.io.ForwardingOs.fcntlFlock(ForwardingOs.java:70)
  at java.nio.FileChannelImpl.basicLock(FileChannelImpl.java:121)
  at java.nio.FileChannelImpl.tryLock(FileChannelImpl.java:181) 
  at java.nio.channels.FileChannel.tryLock(FileChannel.java:584) 
  at com.daveroberge.multi_process.Main2Activity$1.run(Main2Activity.java:35) 
```

I think the code in question is here,
https://android.googlesource.com/platform/libcore/+/android-6.0.1_r16/luni/src/main/native/libcore_io_Posix.cpp#777
https://android.googlesource.com/platform/libcore/+/android-6.0.1_r16/luni/src/main/native/libcore_io_Posix.cpp#192

I think this might be a bug? Regardless, I guess this will need to be special cased

**Comment by dave-r12** [comment] 2016-02-10 01:07
I entered 2 issues on AOSP:
https://code.google.com/p/android/issues/detail?id=200586
https://code.google.com/p/android/issues/detail?id=200670

Hopefully they can bring some clarity to the situation.

**Comment by dave-r12** [comment] 2016-02-13 18:26
I wanted to note the current state of this. The good people over at AOSP confirmed the two bugs related to FileLock, and have known about them since 2014. Due to competing priorities, the complexity involved in testing fixes for the bugs, and lack of developer uproar around this API, it has been pushed to the back of the queue. It's possible they might get fixed with the move to OpenJDK.

Where does that leave us? On Android, it means the following:
* _No easy way to detect intra-process conflicting locks_. This isn't a big deal because most Android app's aren't doing fancy class loading and we're not as concerned about developers shooting themselves in the foot.
* _Detecting inter-process conflicting locks is fragile_. The conflicting lock will be detected, but is signaled to us via an IOException. This makes things difficult because we have to distinguish between a conflicting lock IOException and a real IOException. If we can assume the various Android implementations don't change core library classes, then it might mean the message in the IOException is consistent across devices.

My feeling is that the FileLock approach has become a 'best-effort' solution rather than a complete solution on Android. Is that good enough?

Given the limitations of FileLock, I was looking around for other ways to accomplish the same thing. I had 2 ideas, but both are platform specific.
* Leverage http://developer.android.com/reference/android/os/FileObserver.html to monitor a lock file.
* Leverage http://developer.android.com/reference/android/net/LocalServerSocket.html to open a unique UNIX-domain socket per cache

Both approaches would increase the complexity as we'd need to abstract out the strategy for detecting competing access.

**Comment by swankjesse** [comment] 2016-02-15 02:27
Thanks for the deep investigation on this. I don’t think any of our existing options are particularly compelling – they increase complexity & runtime which punish applications that don’t currently suffer this problem.

I’m tempted to suggest punting this issue to our icebox. The solution isn’t a clean win, and none of our users are actively complaining about this.

**Comment by dave-r12** [comment] 2016-02-15 12:57
Gotcha, makes sense. Thanks for the help BTW.

**Comment by clhols** [comment] 2016-06-15 13:45
Then I would like to complain a little. This bug is the cause of 47% of app crashes on our latest version.

**Comment by swankjesse** [comment] 2016-06-15 13:56
@clhols if you’re only the disk cache from one process, then that’s a separate issue. Could you please open a bug with steps to reproduce? Also include which OkHttp version you’re using.

**Comment by yschimke** [comment] 2020-01-05 08:16
Closing out as I don't think we see a lot of reports here.

**Closed by yschimke** 2020-01-05 08:16 UTC
Labels: enhancement, needs info
