### ISSUE TITLE
OkHttp3.4.1 can't cancel request by tag like release 2.4.0

### ISSUE THREAD

**Issue by brycegao** [square/okhttp#2777] opened 2016-08-08 06:29 UTC
In 2.4.0 release,  I can cancel a request by calling method cancel.  But in release 3.4.1, there is no this method.  Why？   I wan't to cancel some requests in the queue, but there is no way! 

OkHttp2.4.0:
OkHttpClient.java:
public OkHttpClient cancel(Object tag) {
    getDispatcher().cancel(tag);
    return this;
  }

Dispatcher.java:
 /** Cancel all calls with the tag {@code tag}. */
  public synchronized void cancel(Object tag) {
    for (AsyncCall call : readyCalls) {
      if (Util.equal(tag, call.tag())) {
        call.cancel();
      }
    }

    for (AsyncCall call : runningCalls) {
      if (Util.equal(tag, call.tag())) {
        call.get().canceled = true;
        HttpEngine engine = call.get().engine;
        if (engine != null) engine.disconnect();
      }
    }

    for (Call call : executedCalls) {
      if (Util.equal(tag, call.tag())) {
        call.cancel();
      }
    }
  }

**Comment by swankjesse** [comment] 2016-08-08 12:31
Duplicate of
https://github.com/square/okhttp/issues/2205

**Closed by swankjesse** 2016-08-08 12:31 UTC
