### ISSUE TITLE
LINK method is not working.

### ISSUE THREAD

**Issue by abhibhosale** [square/okhttp#2301] opened 2016-01-30 11:14 UTC
I have written below code to call LINK method.

OkHttpClient client = new OkHttpClient();

MediaType mediaType = MediaType.parse("application/octet-stream");
RequestBody body = RequestBody.create(mediaType, "{\r\n\"sid\":\"gyyxy2yo\",\r\n\"start time\" : [\"2016\"]\r\n}");
Request request = new Request.Builder()
  .url("http://172.17.28.132:8080/cgi-bin/DJ2Station/channel/client/schedule/1")
  .method("LINK", body)
  .addHeader("cache-control", "no-cache")
  .addHeader("postman-token", "e235ac63-76c1-b924-d488-3af6082766ff")
  .build();

Response response = client.newCall(request).execute();

But it is not working, as I am getting method LINK must not have a request body.

**Comment by JakeWharton** [comment] 2016-01-30 15:45
LINK is a custom HTTP method so this is a dupe of #229.

**Comment by JakeWharton** [comment] 2016-01-30 15:45
Basically: bodies aren't currently supported with custom HTTP methods.

**Closed by JakeWharton** 2016-01-30 15:45 UTC
