### ISSUE TITLE
Fatal Exception: java.io.IOException: failed to rename...

### ISSUE THREAD

**Issue by oproulx** [square/okhttp#6467] opened 2020-12-11 15:36 UTC
Hello,

We are still seeing this crash on version 4.9.0.

```
Fatal Exception: java.io.IOException: failed to rename /data/user/0/OURAPP/cache/57ad8dd5e5e0a9c6b5f4b00d66f8e3c6.0.tmp to /data/user/0/OURAPP/cache/57ad8dd5e5e0a9c6b5f4b00d66f8e3c6.0
       at okhttp3.internal.io.FileSystem$Companion$SystemFileSystem.rename(FileSystem.java:90)
       at okhttp3.internal.cache.DiskLruCache.completeEdit$okhttp(DiskLruCache.java:532)
       at okhttp3.internal.cache.DiskLruCache$Editor.commit(DiskLruCache.java:901)
       at okhttp3.Cache$RealCacheRequest$1.close(Cache.java:406)
       at okio.internal.RealBufferedSinkKt.commonClose(RealBufferedSinkKt.java:203)
       at okio.RealBufferedSink.close(RealBufferedSink.java:286)
       at okhttp3.internal.cache.CacheInterceptor$cacheWritingResponse$cacheWritingSource$1.read(CacheInterceptor.java:190)
       at okio.internal.RealBufferedSourceKt.commonRead(RealBufferedSourceKt.java:39)
       at okio.RealBufferedSource.read(RealBufferedSource.java:189)
       at okio.internal.RealBufferedSourceKt.commonExhausted(RealBufferedSourceKt.java:49)
       at okio.RealBufferedSource.exhausted(RealBufferedSource.java:197)
       at okio.GzipSource.read(GzipSource.java:88)
       at okio.internal.RealBufferedSourceKt.commonRead(RealBufferedSourceKt.java:39)
       at okio.RealBufferedSource.read(RealBufferedSource.java:189)
       at okio.ForwardingSource.read(ForwardingSource.java:29)
       at retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read(OkHttpCall.java:288)
       at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.java:158)
       at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:288)
       at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:351)
       at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:180)
       at java.io.InputStreamReader.read(InputStreamReader.java:184)
       at okhttp3.ResponseBody$BomAwareReader.read(ResponseBody.java:211)
       at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:1295)
       at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1333)
       at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:538)
       at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
       at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:40)
       at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
       at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
       at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:121)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:519)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```

Any help is greatly appreciated!

Olivier

**Comment by yschimke** [comment] 2020-12-11 17:42
Closing this as a dupe of #6123 , nothing obvious to go off on this report above and beyond the other issue.  So we should continue the discussion on the other bug.  It was closed because there wasn't anything actionable for us to do, I think that's still the same unfortunately.

**Closed by yschimke** 2020-12-11 17:42 UTC
Labels: bug
