### ISSUE TITLE
Expected URL scheme 'http' or 'https' but no colon was found okhttp3.HttpUrl$Builder.parse

### ISSUE THREAD

**Issue by Telzhanov** [square/okhttp#6494] opened 2020-12-30 09:26 UTC
Hi! The crush happens during making request via okhttp3. I checked correctness of url, which is used to make request. We couldn't reproduce current bug. But, some users continue crashing. 
Also, I notice from stacktrace that the crash happens when url is got from cache.
okhttp3.HttpUrl$Builder.parse (HttpUrl.java:1333)
okhttp3.HttpUrl.get (HttpUrl.java:916)
okhttp3.Request$Builder.url (Request.java:165)
okhttp3.Cache$Entry.response (Cache.java:706)
okhttp3.Cache.get (Cache.java:214)
okhttp3.Cache$1.get (Cache.java:145)

**Comment by yschimke** [comment] 2020-12-30 09:46
Dupe of https://github.com/square/okhttp/issues/6453

**Closed by yschimke** 2020-12-30 09:46 UTC
Labels: bug
