### ISSUE TITLE
Network Error Logging Support in OkHttp

### ISSUE THREAD

**Issue by tuberd** [square/okhttp#6413] opened 2020-11-12 18:28 UTC
Hey OkHttp folks,
Was wondering if there was any plans to support [Network Error Logging](https://www.w3.org/TR/network-error-logging/) natively in OkHttp.  It's supported in [cronet through experimental features](https://source.chromium.org/chromium/chromium/src/+/master:components/cronet/url_request_context_config.cc;l=138;drc=4cd506f8d178ede30acc775708218ed960dfa873) but in talking to a handful of app teams, it would be great to be able to see reachability data via okhttp as well.

Thanks so much!

**Comment by yschimke** [comment] 2020-11-12 20:00
A few thoughts

1) This doesn't feel like something we would turn on by default for all clients.  
2) Similar complexity additional features tend to be implemented as separate libraries like https://github.com/babylonhealth/certificate-transparency-android
3) Detecting the specific errors is really awkward across so many different platforms (Android versions, JDK versions, Providers).  

On the last point it seems like a lot of work to correctly root cause every error type automatically, this is a look at just one class of errors

https://github.com/square/okhttp/issues/6411

And with Conscrypt - we've asked for ways to cleanly understand causes of handshake failures but it isn't something cleanly supported at the moment https://github.com/google/conscrypt/issues/847 

If we could even do 3) reliably, I think we could wrap more exceptions into ones with something like a public API for errors, even without the reporting aspect.  Make it possible for clients to catch those and explain to end users why the connection is faulty.

**Comment by swankjesse** [comment] 2020-11-13 03:05
Yeah I think you could probably do this with OkHttp, but I don’t think it’s a good fit within the library.

**Comment by swankjesse** [comment] 2020-11-13 03:06
But one thing we could do, which would be pretty nice, is to report our errors using the taxonomy here:
https://www.w3.org/TR/network-error-logging/#predefined-network-error-types

**Comment by yschimke** [comment] 2020-11-13 07:00
Let's reopen and define not as an interceptor but a gradual move to errors containing enough structured data to sometimes report these.

Maybe work with Conscrypt folk to make this happen a layer lower also.

**Comment by yschimke** [comment] 2020-11-21 19:14
Put an exploration in the PR above.

**Comment by yschimke** [comment] 2021-01-25 20:52
Also wondering how it could relate to https://www.chromium.org/developers/design-documents/network-stack/netlog

Which are effective as a much more user friendly (cooperative) version of wireshark pcaps. chrome://net-export/

**Comment by yschimke** [comment] 2021-01-25 21:28
Or if we wait long enough

https://tools.ietf.org/html/draft-marx-qlog-main-schema-02#section-4.3.3
https://tools.ietf.org/html/draft-marx-qlog-event-definitions-quic-h3-02

**Comment by yschimke** [comment] 2023-05-21 08:53
Closing as low priority and unlikely to be picked up.

WireShark is working with JDK 11

**Closed by yschimke** 2023-05-21 08:53 UTC
Labels: enhancement
