### ISSUE TITLE
HEAD request times out

### ISSUE THREAD

**Issue by stigkj** [square/okhttp#3590] opened 2017-09-08 21:25 UTC
I am trying to do HEAD requests against some URLs before doing the actual download, but the requests just times out. An example URL:

http://www.sunhotels.net/SunHotels.net/HotelInfo/hotelImage.aspx?full=1&id=528422

I have made a failing test here: https://gist.github.com/stigkj/fce1239ae09a3327b88bf134c77ef1d1

`curl -I` against the URL does not hang. OkHttp version is 3.9.0.

**Comment by yschimke** [comment] 2017-09-09 05:56
hmmm.... this should be fixed in 3.9.0 https://github.com/square/okhttp/pull/3572

I'll take a look

**Comment by yschimke** [comment] 2017-09-09 06:08
I think we are missing some of curl's special handling of broken Web Servers.

This hangs
```
curl -v -X HEAD 'http://www.sunhotels.net/SunHotels.net/HotelInfo/hotelImage.aspx?full=1&id=528422'
Warning: Setting custom HTTP method to HEAD with -X/--request may not work the
Warning: way you want. Consider using -I/--head instead.
```

This works
`curl -v -I 'http://www.sunhotels.net/SunHotels.net/HotelInfo/hotelImage.aspx?full=1&id=528422' `

BOTH do HEAD requests

**Comment by yschimke** [comment] 2017-09-09 06:17
@stigkj Thanks for the test

We end up blocked trying to do an 8K read in RealBufferedSource

"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.net.SocketInputStream.socketRead0(SocketInputStream.java:-1)
	  at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	  at java.net.SocketInputStream.read(SocketInputStream.java:171)
	  at java.net.SocketInputStream.read(SocketInputStream.java:141)
	  at okio.Okio$2.read(Okio.java:139)
	  at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	  at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
	  at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
	  at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
	  at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:187)
	  at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	  at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	  at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	  at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	  at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	  at okhttp3.RealCall.execute(RealCall.java:77)
	  at okhttp3.OkHttpBug.test(OkHttpBug.java:19)

**Comment by yschimke** [comment] 2017-09-09 06:20
With Connection: close, I think it turns into the real error


```
        Request request = new Request.Builder()
            .header("Connection", "close")
                .head()
                .url("http://www.sunhotels.net/SunHotels.net/HotelInfo/hotelImage.aspx?full=1&id=528422")
                .build();
```

Fails with

```
java.io.IOException: unexpected end of stream on Connection{www.sunhotels.net:80, proxy=DIRECT hostAddress=www.sunhotels.net/81.93.148.144:80 cipherSuite=none protocol=http/1.1}

	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:203)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at okhttp3.OkHttpBug.test(OkHttpBug.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.io.EOFException: \n not found: limit=0 content=…
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:187)
	... 38 more
```

**Comment by yschimke** [comment] 2017-09-09 07:05
I'm trying to understand why we don't think we get any response bytes back from the server, can sort of replicate with nc.

```
$ echo -ne "HEAD /robots.txt HTTP/1.1\r\nHost: www.twitter.com\r\n\r\n" | nc www.twitter.com 80
HTTP/1.1 200 OK
content-length: 26
content-type: text/plain;charset=utf-8
date: Sat, 09 Sep 2017 07:01:37 GMT
server: tsa_f
set-cookie: personalization_id="v1_uwlgj3Ppn17yblDrtw+9rQ=="; Expires=Mon, 09 Sep 2019 07:01:37 UTC; Path=/; Domain=.twitter.com
set-cookie: guest_id=v1%3A150494049706759371; Expires=Mon, 09 Sep 2019 07:01:37 UTC; Path=/; Domain=.twitter.com
x-connection-hash: 1d7b7b70536295b12b02b48cabd7a55d
x-response-time: 99

$ echo -ne "HEAD /SunHotels.net/HotelInfo/hotelImage.aspx?full=1&id=528422 HTTP/1.1\r\nHost: www.sunhotels.net\r\n\r\n" | nc www.sunhotels.net 80
```

**Comment by yschimke** [comment] 2017-09-09 07:27
Disabling gzip makes it pass

        Request request = new Request.Builder()
                .head()
                .url("http://www.sunhotels.net/SunHotels.net/HotelInfo/hotelImage.aspx?full=1&id=528422")
                .header("Accept-Encoding", "identity")
                .build();

**Comment by yschimke** [comment] 2017-09-09 07:31
I think it's a server bug, curl also hangs with gzip encoding.

```
$ curl -v -I -H "Accept-Encoding: gzip" 'http://www.sunhotels.net/SunHotels.net/HotelInfo/hotelImage.aspx?full=1&id=528422'
*   Trying 81.93.148.144...
* TCP_NODELAY set
* Connected to www.sunhotels.net (81.93.148.144) port 80 (#0)
> HEAD /SunHotels.net/HotelInfo/hotelImage.aspx?full=1&id=528422 HTTP/1.1
> Host: www.sunhotels.net
> User-Agent: curl/7.54.0
> Accept: */*
> Accept-Encoding: gzip
>
```

**Comment by yschimke** [comment] 2017-09-09 07:36
$ curl -v -I -H "Accept-Encoding: gzip" -H "Connection: close" 'http://www.sunhotels.net/SunHotels.net/HotelInfo/hotelImage.aspx?full=1&id=528422'
*   Trying 81.93.148.144...
* TCP_NODELAY set
* Connected to www.sunhotels.net (81.93.148.144) port 80 (#0)
> HEAD /SunHotels.net/HotelInfo/hotelImage.aspx?full=1&id=528422 HTTP/1.1
> Host: www.sunhotels.net
> User-Agent: curl/7.54.0
> Accept: */*
> Accept-Encoding: gzip
> Connection: close
>
* Empty reply from server

**Closed** 2017-09-09 07:37 UTC

**Comment by stigkj** [comment] 2017-09-09 10:37
That was fast! Thank you very much! I'll just disable gzip then.

**Comment by wmjwmj828** [comment] 2017-09-15 03:50
... don't work for me

**Comment by yschimke** [comment] 2017-09-15 05:12
@wmjwmj828 Are you also making requests to www.sunhotels.net?  This error is caused by a badly behaved web server, so doesn't apply generally, just to this server.
