### ISSUE TITLE
java.lang.IllegalArgumentException: port out of range:-1

### ISSUE THREAD

**Issue by Mahdibenamor** [square/okhttp#7531] opened 2022-11-29 11:22 UTC
We are facing this crash in our mobile app: 
We are using xamarin as a tool to develop our app, and we are referencing some packages that use the bindings for the okhttp. 
example of packages : 
 - Xamarin.Firebase.Components
 - Xamarin.GooglePlayServices.Basement
 - Xamarin.Firebase.Common
 - etc, ......
the stack trace :  
java.net.InetSocketAddress.checkPort InetSocketAddress.java:144
java.net.InetSocketAddress.createUnresolved InetSocketAddress.java:269
sun.net.spi.DefaultProxySelector$1.run DefaultProxySelector.java:315
sun.net.spi.DefaultProxySelector$1.run DefaultProxySelector.java:219
java.security.AccessController.doPrivileged AccessController.java:43
sun.net.spi.DefaultProxySelector.select DefaultProxySelector.java:218
okhttp3.internal.connection.RouteSelector$resetNextProxy$1.invoke RouteSelector.kt:106
okhttp3.internal.connection.RouteSelector.resetNextProxy RouteSelector.kt:113
okhttp3.internal.connection.RouteSelector.<init> RouteSelector.kt:53
okhttp3.internal.connection.ExchangeFinder.findConnection ExchangeFinder.kt:202
okhttp3.internal.connection.ExchangeFinder.findHealthyConnection ExchangeFinder.kt:106
okhttp3.internal.connection.ExchangeFinder.find ExchangeFinder.kt:74
okhttp3.internal.connection.RealCall.initExchange$okhttp RealCall.kt:255
okhttp3.internal.connection.ConnectInterceptor.intercept ConnectInterceptor.kt:32
okhttp3.internal.http.RealInterceptorChain.proceed RealInterceptorChain.kt:109
okhttp3.internal.cache.CacheInterceptor.intercept CacheInterceptor.kt:95
okhttp3.internal.http.RealInterceptorChain.proceed RealInterceptorChain.kt:109
okhttp3.internal.http.BridgeInterceptor.intercept BridgeInterceptor.kt:83
okhttp3.internal.http.RealInterceptorChain.proceed RealInterceptorChain.kt:109
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept RetryAndFollowUpInterceptor.kt:76
okhttp3.internal.http.RealInterceptorChain.proceed RealInterceptorChain.kt:109
io.intercom.android.sdk.api.ShutdownInterceptor.intercept ShutdownInterceptor.java:35
okhttp3.internal.http.RealInterceptorChain.proceed RealInterceptorChain.kt:109
io.intercom.android.sdk.api.RetryInterceptor.intercept RetryInterceptor.java:21
okhttp3.internal.http.RealInterceptorChain.proceed RealInterceptorChain.kt:109
io.intercom.android.sdk.api.UserIdentityInterceptor.intercept UserIdentityInterceptor.java:28
okhttp3.internal.http.RealInterceptorChain.proceed RealInterceptorChain.kt:109
okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp RealCall.kt:201
okhttp3.internal.connection.RealCall$AsyncCall.run RealCall.kt:517
java.util.concurrent.ThreadPoolExecutor.runWorker ThreadPoolExecutor.java:1137
java.util.concurrent.ThreadPoolExecutor$Worker.run ThreadPoolExecutor.java:637
java.lang.Thread.run Thread.java:1012

**Comment by yschimke** [comment] 2022-11-29 11:28
Dupe of https://github.com/square/okhttp/issues/7153, this is outside of OkHttp.

**Comment by Mahdibenamor** [comment] 2022-11-29 11:28
@yschimke  can we have a fix as soon as possible, the situation is critical for us and for our business

**Closed by yschimke** 2022-11-29 11:28 UTC
Labels: bug

**Comment by yschimke** [comment] 2022-11-29 11:31
You can set your own ProxySelector to avoid this.

https://github.com/square/okhttp/blob/b515117984e198fd710e85005ee7a520e236e3f3/okhttp/src/jvmMain/kotlin/okhttp3/OkHttpClient.kt#L749

But not a bug for OkHttp to fix.
