### ISSUE TITLE
ava.lang.NullPointerException: throw with null exception 	at java.net.Socket.getInputStream(Socket.java:900)

### ISSUE THREAD

**Issue by yy1300326388** [square/okhttp#3289] opened 2017-04-17 02:24 UTC
java.lang.NullPointerException: throw with null exception
	at java.net.Socket.getInputStream(Socket.java:900)
	at okio.Okio.source(Okio.java:220)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:226)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:146)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:186)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:776)

**Comment by yy1300326388** [comment] 2017-04-18 06:54
Android 7.0

**Comment by 15characterlimi** [comment] 2017-04-20 16:15
This is a duplicate of https://github.com/square/okhttp/issues/3245

**Comment by JakeWharton** [comment] 2017-04-20 16:19
Thanks! I knew it looked familiar but hadn't had time to find the other issue.

**Closed** 2017-04-20 16:19 UTC
