### ISSUE TITLE
Specific "User-Agent " header value fails request via Proxy

### ISSUE THREAD

**Issue by DmitriyYakovlev** [square/okhttp#3806] opened 2018-01-31 09:16 UTC
I have next code (for receiving data via proxy). I have Authenticator. I have some request headers. 
if header **"User-Agent"** has **"Mozilla/5.0 (Linux; Android 7.0; SM-T813 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/62.0.3202.84 Safari/537.36")**
I can see double triggering of callback method in Authenticator and then exception with java.io.IOException: unexpected end of stream on null.
When I set, for example
 **"User-Agent" as "Linux"** all works correctly. (callback method in Authenticator and then successful finishing of a request)
version: 3.9.1
Please, help me to define how to achieve workable state with using my headers, but without exception. Thanks.

    HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
    logging.setLevel(HttpLoggingInterceptor.Level.BODY);
 
    Authenticator proxyAuthenticator = (route, response) -> { 
        String credential = Credentials.basic(USERNAME, PASS); 
 
        // Triggers twice when headers are present 
        // and once when they are absent 
        Request.Builder nReq = response.request().newBuilder(); 
        return nReq.header("Proxy-Authorization", credential).build(); 
    }; 
 
    Proxy proxy = new Proxy(Proxy.Type.HTTP, 
        new InetSocketAddress(HOSTNAME, 22225));
 
    OkHttpClient client = new OkHttpClient().newBuilder()
        .addInterceptor(logging)
        .proxy(proxy) 
        .proxyAuthenticator(proxyAuthenticator) 
        .build(); 
 
    Headers headers = buildRequestHeaders();
 
    Request req = 
        new Request.Builder().url(URL) 
            .headers(headers) // problem with headers there
            .build(); 
 
    Call call = client.newCall(req);
 
    Response response;
    try { 
        response = call.execute();
        // if request headers are absent, all works fine  
        Timber.d("Finished"); 
    } catch (Exception e) {
        // triggers with "java.io.IOException: unexpected end of stream on null" if headers was set 
        e.printStackTrace();
    } 

```
private Headers buildRequestHeaders() {
    Headers.Builder headersBuilder = new Headers.Builder();
    headersBuilder.add("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8");
    headersBuilder.add("User-Agent", "Mozilla/5.0 (Linux; Android 7.0; SM-T813 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/62.0.3202.84 Safari/537.36");
    headersBuilder.add("Upgrade-Insecure-Requests", "1");
    return headersBuilder.build();
}
```

**Comment by DmitriyYakovlev** [comment] 2018-01-31 15:46
The problem is related to a situation that OkHTTP does not support proxy for HTTPS.
https://github.com/square/okhttp/issues/3787
This code gives redirect to HTTPs page from HTTP page, because "User-Agent" contains word "Android" and site redirects to mobile version of site. Then, OkHTTP tries to redirect internally and throws crash. "java.io.IOException: unexpected end of stream on null"

**Comment by DmitriyYakovlev** [comment] 2018-01-31 15:48
Will be great to have HTTPS supported, but at least will be great to have meaningful exception thrown.
I mean,  OkHttp can give a hint in thrown exception that HTTPS not supported instead of '"java.io.IOException: unexpected end of stream on null". This exception hides real root of the problem.

**Comment by swankjesse** [comment] 2018-02-18 18:50
Unclear what action to take here. I think most of this is a dupe of #3787.

**Closed by swankjesse** 2018-02-18 18:50 UTC
