### ISSUE TITLE
Can't do Pre-Emptive Proxy Authentication to HTTPS endpoints

### ISSUE THREAD

**Issue by bsia** [square/okhttp#4099] opened 2018-06-28 22:13 UTC
I'm trying to connect to an HTTPS endpoint via a Proxy.  My proxy requires basic auth.  To optimize my http requests, I would like to do pre-emptive authentication where I pre-compute the base64-encoded auth token and include a Proxy-Authorization header as part of the Http request.  My code is as follows:

```
    public InputStream getData(final String url) throws IOException {
        Request request = new Request.Builder()
                .url(url)
                .header("Proxy-Authorization", "<precomputed-token>")
                .build();

        Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("myspecialproxy.com", 3128));
        
        OkHttpClient client = new OkHttpClient.Builder()
                                    .proxy(proxy)
                                    .build();
        
        Response response = client.newCall(request).execute();
        return response.body().byteStream();
    }
```

If my endpoint is `http`, say 'http://httpbin.org/get', I can see the Proxy-Authorization header show up in the Http Proxy request (to myspecialproxy.com).  However, if the endpoint is `https`, then I don't see the Proxy-Authorization at all.  Instead, if I trace it manually, I can actually see the Proxy-Authorization being set in the tunneled Http request (to httpbin.org).

Looking at the okhttp code, in `RealConnection.createTunnelRequest`, it looks like a separate Request is created for the outer Http Proxy request:

```
    private Request createTunnelRequest() {
      return new Request.Builder()
          .url(route.address().url())
          .header("Host", Util.hostHeader(route.address().url(), true))
          .header("Proxy-Connection", "Keep-Alive") // For HTTP/1.0 proxies like Squid.
          .header("User-Agent", Version.userAgent())
          .build();
    }
```

Is it possible to provide an api to explicitly set custom Http Proxy request headers?

**Comment by swankjesse** [comment] 2018-07-05 00:12
Duplicate of https://github.com/square/okhttp/issues/2435

**Closed by swankjesse** 2018-07-05 00:12 UTC
Labels: enhancement
