### ISSUE TITLE
java.lang.NullPointerException: ssl_session == null

### ISSUE THREAD

**Issue by hpuhsp** [square/okhttp#3705] opened 2017-12-01 02:24 UTC
Fatal Exception: java.lang.NullPointerException: ssl_session == null
       at com.android.org.conscrypt.NativeCrypto.SSL_SESSION_cipher(NativeCrypto.java)
       at com.android.org.conscrypt.OpenSSLSessionImpl.getCipherSuite(OpenSSLSessionImpl.java:320)
       at okhttp3.Handshake.get(Handshake.java:49)
       at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:268)
       at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:237)
       at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:148)
       at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:186)
       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
       at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at com.custom.android.networks.retrofit.OfflineCacheControlInterceptor.intercept(OfflineCacheControlInterceptor.java:35)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)

**Comment by NightlyNexus** [comment] 2017-12-01 02:34
Duplicate of #3301

**Closed** 2017-12-01 03:13 UTC

**Comment by hpuhsp** [comment] 2018-05-23 02:54
@NightlyNexus got it.thanks
