### ISSUE TITLE
If framed connnection is shutdown, existing connection goes in a forever retry loop

### ISSUE THREAD

**Issue by bhuvanrawal** [square/okhttp#7616] opened 2023-01-02 07:48 UTC
We observed in our production environment, 3 threads getting stuck with high CPU usage doing no network I/O activity, choking our server. When we debugged the stacktrace of thread, it was found that there is a while loop at RealCall::sendResponse()::244, and later in the trace FramedConnection.newStream() if shutdown is set then IOException would be sent, therefore a forever retry is happening.

This if validated is a major issue as application needs redeployment and new connections are not possible too.

What I cannot pinpoint at this stage is the exact reason for shutdown, but that seems irrelevant to this issue.

`"http-nio-9069-exec-19" #391 daemon prio=5 os_prio=0 tid=0x00007f90d502a000 nid=0x2a3e runnable [0x00007f907fde0000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.Throwable.fillInStackTrace(Native Method)
        at java.lang.Throwable.fillInStackTrace(Throwable.java:784)
        - locked <0x00000000ef446500> (a java.io.IOException)
        at java.lang.Throwable.<init>(Throwable.java:266)
        at java.lang.Exception.<init>(Exception.java:66)
        at java.io.IOException.<init>(IOException.java:58)
        at okhttp3.internal.framed.FramedConnection.newStream(FramedConnection.java:259)
        - locked <0x00000000ccc10610> (a okhttp3.internal.framed.FramedConnection)
        - locked <0x00000000ccc10a38> (a okhttp3.internal.framed.Http2$Writer)
        at okhttp3.internal.framed.FramedConnection.newStream(FramedConnection.java:245)
        at okhttp3.internal.http.Http2xStream.writeRequestHeaders(Http2xStream.java:135)
        at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:748)
        at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:613)
        at okhttp3.RealCall.getResponse(RealCall.java:244)
        at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
        at com.assist.commons.retrofit.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:148)
        at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
        at com.assist.core.interceptor.OfbAuthenticationInterceptor.intercept(OfbAuthenticationInterceptor.java:55)
        at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
        at com.assist.core.interceptor.RequestHeadersInterceptor.intercept(RequestHeadersInterceptor.java:56)
        at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
        at okhttp3.RealCall.execute(RealCall.java:57)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)`

**Comment by yschimke** [comment] 2023-01-02 08:07
Are you using 4.10.0?

This looks like a very old version, so want to make sure it is still happening in latest versions.

**Comment by yschimke** [comment] 2023-01-03 03:58
This must be around version 3.5.0, closing until issue is confirmed on 4.10.

**Closed by yschimke** 2023-01-03 03:58 UTC
Labels: bug, needs info
