### ISSUE TITLE
Unable to shutdown serve when setResponseCode(HttpURLConnection.HTTP_CLIENT_TIMEOUT)

### ISSUE THREAD

**Issue by prabintim** [square/okhttp#2534] opened 2016-05-04 22:34 UTC
I am trying to simulate network timeout using code,
```
        server.enqueue(new MockResponse()
                .setResponseCode(HttpURLConnection.HTTP_CLIENT_TIMEOUT)
                .setBody(RestServiceHelper.getStringFromFile(getInstrumentation().getContext(), "login.json")));

```
Error: **java.io.IOException: Gave up waiting for executor to shut down**

server.getRequestCount() = 2 when timeout response is set for execution. 500 and 200 are fine. 

On the bright side, it actually simulated timeout.

**Comment by swankjesse** [comment] 2016-05-05 02:06
Could you give me a full test case?

**Comment by prabintim** [comment] 2016-05-05 16:36
@Before
    public void setUp() throws IOException {
        server = new MockWebServer();
        server.start(1234);
        NetworkServiceHelper.init(String.valueOf(server.url("/")));
    }

    @Test
    @LargeTest
    public void login_timeout_access_denied() throws IOException {
        server.enqueue(new MockResponse()
                .setResponseCode(HttpURLConnection.HTTP_CLIENT_TIMEOUT)
                .setBody(RestServiceHelper.getStringFromFile(getInstrumentation().getContext(), "login.json")));

        // (Removing this still gives error)
        ProgressBar progressBar = (ProgressBar) mActivity.getActivity().findViewById(R.id.login_progress);
        IdlingResource idlingResource = new WaitForViewToBe(View.GONE, progressBar);
        registerIdlingResources(idlingResource);

        onView(LoginActivityPage.userNameInputBox).perform(typeText(Data.username), closeSoftKeyboard());
        onView(LoginActivityPage.passwordInputBox).perform(typeText(Data.password), closeSoftKeyboard());
        onView(LoginActivityPage.signInButton).perform(click()); // Service call

        onView(LoginActivityPage.passwordInputBox).check(matches(MatcherHelper.withError(mActivity.getActivity().getString(R.string.error_incorrect_username_or_password))));

        unregisterIdlingResources(idlingResource);
    }


    @After
    public void tearDown() throws IOException {
        server.shutdown();
    }

**Comment by swankjesse** [comment] 2016-05-05 21:10
Thanks! Could you change your test case to be self-contained? Make it as easy as possible for us to fix your bug!

**Comment by prabintim** [comment] 2016-05-05 21:51
I have updated the code above. Also, I am using retrofit and rxjava. My guess with time out is that retrofit is making one more call to server when the first one times out. 

Stacktrace:
```
java.io.IOException: Gave up waiting for executor to shut down
at com.squareup.okhttp.mockwebserver.MockWebServer.shutdown(MockWebServer.java:411)
at com.accolade.mobile.tests.TimeoutTest.login_timeout_access_denied(TimeoutTest.java:47)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:270)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
```

**Comment by JakeWharton** [comment] 2016-05-05 22:01
Retrofit does not retry automatically

**Comment by JakeWharton** [comment] 2016-05-05 22:02
Seems like a dupe of #2521.

**Comment by prabintim** [comment] 2016-05-05 23:39
Yup.

**Comment by JakeWharton** [comment] 2016-05-06 03:33
Closing this then. Let's consolidate any efforts on that issue.

I'll take a quick look at this tonight.

**Closed by JakeWharton** 2016-05-06 03:33 UTC
