### ISSUE TITLE
Duplicate entry okhttp3/Address.class

### ISSUE THREAD

**Issue by krishnameena** [square/okhttp#2242] opened 2016-01-14 16:35 UTC
I have updated the OKHTTP API version from okhttp3.0.0-RC1 to okhttp-3.0.0. Now I am getting the following error while building the APK

Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: okhttp3/Address.class

**Comment by swankjesse** [comment] 2016-01-14 23:49
Duplicate of https://github.com/square/okhttp/issues/2243

**Closed by swankjesse** 2016-01-14 23:49 UTC

**Comment by nhatvm** [comment] 2017-03-30 03:40
I had the same issue. And I tried to add this line
android {
configurations {
        all*.exclude group: 'com.squareup.okhttp3', module: 'okhttp'
    }
}
And It works fine for me. Please try to do it.
