### ISSUE TITLE
Crash in OkHttp with Facebook SDK

### ISSUE THREAD

**Issue by ankur-j9** [square/okhttp#2888] opened 2016-09-29 06:18 UTC
Could not reproduce this issue but this is happening alot when we see crashlytics logs. Crashlytics link : http://crashes.to/s/845f72a220f

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
       at com.android.okhttp.internal.Util.rjil_playstore_download_case(Util.java:309)
       at com.android.okhttp.HostResolver$1.getAllByName(HostResolver.java:31)
       at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:232)
       at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:124)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:310)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:249)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:397)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:347)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:515)
       at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
       at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
       at com.facebook.GraphResponse.fromHttpConnection(SourceFile:253)
       at com.facebook.GraphRequest.executeConnectionAndWait(SourceFile:1266)
       at com.facebook.GraphRequest.executeBatchAndWait(SourceFile:1164)
       at com.facebook.GraphRequest.executeBatchAndWait(SourceFile:1130)
       at com.facebook.GraphRequest.executeBatchAndWait(SourceFile:1114)
       at com.facebook.GraphRequest.executeAndWait(SourceFile:1089)
       at com.facebook.GraphRequest.executeAndWait(SourceFile:983)
       at com.facebook.internal.Utility.getAppSettingsQueryResponse(SourceFile:869)
       at com.facebook.internal.Utility.access$100(SourceFile:76)
       at com.facebook.internal.Utility$1.run(SourceFile:798)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Comment by caseykulm** [comment] 2016-09-30 03:21
This is a surprising line in your stack trace.

```
com.android.okhttp.internal.Util.rjil_playstore_download_case(Util.java:309)
```

Even though you say, 

> Though this issue is occurring mostely on LGE devices(97%) but it is happening on other manufacturer's devices as well.

in #2526, the fact is that this rjil_playstore_download_case method does not exist in this project, so an issue ticket here cannot solve the issue. If you have any ability to swap out the version of OkHttp it's using with a version from Maven Central, or to communicate with the people who wrote the rjil_playstore_download_case method, those are two viable routes to move past this problem.

**Comment by 15characterlimi** [comment] 2016-09-30 18:11
This is a duplicate of https://github.com/square/okhttp/issues/2526

This is a bug in one manufacturer's version of Android Lollipop, not in OkHttp, so please don't bother the OkHttp developers with it :)

**Closed** 2016-10-01 16:07 UTC
