### ISSUE TITLE
IllegalArgumentException reading Cache Entry

### ISSUE THREAD

**Issue by awenger** [square/okhttp#4322] opened 2018-10-18 09:59 UTC
We see infrequent crashes (only reports for a fraction of users, could not reproduce locally) that seem to happen when okhttp loads a cached response:
```
Fatal Exception: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
       at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1325)
       at okhttp3.HttpUrl.get(HttpUrl.java:916)
       at okhttp3.Request$Builder.url(Request.java:165)
       at okhttp3.Cache$Entry.response(Cache.java:702)
       at okhttp3.Cache.get(Cache.java:211)
       at okhttp3.Cache$1.get(Cache.java:145)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:54)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at // some Interceptor that simply adds a "User-Agent" header
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

While reading the changelog I noticed:
> Fix: Don't corrupt the response cache when a 304 (Not Modified) response overrides the stored "Content-Encoding" header.

could this be related to a corrupted cache? If yes do we need to wipe the cache or will that recover by itself?

**Comment by awenger** [comment] 2018-10-18 10:01
OkHttp version is 3.11.0 and platform is Android

**Comment by jpage4500** [comment] 2018-11-01 18:07
I'm also seeing this happen fairly frequently. We tried catching the IllegalArgumentException and logging it to Crashlytics as a non-fatal exception with the URL and there's nothing wrong with the URL formatting.

We're also using 3.11.0 as well:
```
    api 'com.squareup.okhttp3:okhttp:3.11.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.11.0'
```

```
Non-fatal Exception: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
       at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1325)
       at okhttp3.HttpUrl.get(HttpUrl.java:916)
       at okhttp3.Request$Builder.url(Request.java:165)
       at okhttp3.Cache.okhttp3.Cache$Entry.response(Cache.java:2702)
       at okhttp3.Cache$1.get(Cache.java:145)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:54)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at // our custom interceptor
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
       at okhttp3.RealCall.execute(RealCall.java:77)
       at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
       at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:91)
...
```

**Comment by awenger** [comment] 2018-11-02 16:40
Changelog for 3.10.0:
https://github.com/square/okhttp/blob/master/CHANGELOG.md

**Comment by awenger** [comment] 2018-11-02 16:45
I also was unable to find the issue/PR that reported/fixed this problem. So I can't say what exactly was fixed and what the problem was.
My assumption is that there are corrupted entries in the cache (introduced with an earlier version of okhttp).  And that okhttp crashes while reading these corrupted entries.

**Comment by swankjesse** [comment] 2018-11-04 00:33
Yeah, looks like a corrupt cache.

**Comment by swankjesse** [comment] 2018-11-04 00:34
Duplicate of https://github.com/square/okhttp/issues/3251

**Closed by swankjesse** 2018-11-04 00:34 UTC

**Comment by swankjesse** [comment] 2018-11-07 08:18
At the moment it does not recover gracefully.

**Comment by awenger** [comment] 2018-11-07 10:47
thanks for the info, is it save to just delete all files in the caching dir? Or is there some better way to *un-brick* affected devices?

**Comment by swankjesse** [comment] 2018-11-07 10:53
Yeah, that’ll work. Sigh.

**Comment by hugosvent** [comment] 2019-03-08 08:36
anyone know how to gracefully handle the corrupted cache?

should I use interceptor to try catch the chain.proceed and force it to use network when it return IllegalArgumentException?

**Comment by MrDatastorage** [comment] 2019-04-09 10:03
Same error, cleaning the cache, after auth in the app. It crash on this error.

**Comment by MrDatastorage** [comment] 2019-04-09 10:04
React Native 59+

**Comment by awenger** [comment] 2019-04-15 19:45
We switched to a fresh caching directory for OkHttp, as suggested by @swankjesse. However this did not fix the problem for us. We still see this issue as our 3. most frequent crash. It also seem to hit users on average 2 times (affected sessions vs user ratio). So it seems to not corrupt the cache permanently.

The only thing that changed since a long time is that it today happened on my device while working on unrelated things. After the crash, the app started normally and all http/https requests were executed normally (I think it was triggering the same http requests as during the session that crashed). Interestingly, directly after the crash another log appeared (1ms after the logged exception that then killed the app):
```
2019-04-15 18:12:59.574 17009-17199/our.app E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: our.app, PID: 17009
    java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
        at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1325)
        at okhttp3.HttpUrl.get(HttpUrl.java:916)
        at okhttp3.Request$Builder.url(Request.java:165)
        at okhttp3.Cache$Entry.response(Cache.java:702)
        at okhttp3.Cache.get(Cache.java:211)
        at okhttp3.Cache$1.get(Cache.java:145)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:54)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:213)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at // some Interceptor that simply adds a "User-Agent" header
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
        
2019-04-15 18:12:59.575 17009-17197/our.app E/sc: 6184 ms: Thing.that.attaches.a.rxjava.onErrorReturn.to.the.Single.from.retrofit.for.the.get.call.and.logs: error fetchSource https://some.server.tld/some/url?with=query with java.io.IOException: ID1ID2: actual 0x00000000 != expected 0x00001f8b
    java.io.IOException: ID1ID2: actual 0x00000000 != expected 0x00001f8b
        at okio.GzipSource.checkEqual(GzipSource.java:205)
        at okio.GzipSource.consumeHeader(GzipSource.java:120)
        at okio.GzipSource.read(GzipSource.java:73)
        at okio.RealBufferedSource.read(RealBufferedSource.java:47)
        at okio.ForwardingSource.read(ForwardingSource.java:35)
        at retrofit2.OkHttpCall$ExceptionCatchingRequestBody$1.read(OkHttpCall.java:290)
        at okio.RealBufferedSource.request(RealBufferedSource.java:68)
        at okio.RealBufferedSource.rangeEquals(RealBufferedSource.java:418)
        at okio.RealBufferedSource.rangeEquals(RealBufferedSource.java:402)
        at okhttp3.internal.Util.bomAwareCharset(Util.java:469)
        at okhttp3.ResponseBody$BomAwareReader.read(ResponseBody.java:256)
        at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:1295)
        at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1333)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:549)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:205)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:39)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
        at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:122)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:217)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:116)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```
I'm not sure if the two are related or not, however being only 1ms second apart it could be a good lead.

**Comment by awenger** [comment] 2019-04-15 19:54
Another, maybe relevant thing, that happened shortly before the crash are a few reports from the `okhttp3.logging.HttpLoggingInterceptor.Level.BASIC` about requests being canceled:

```
2019-04-15 18:12:59.547 17009-17199/our.app V/sc: 6156 ms: <-- HTTP FAILED: java.io.IOException: Canceled
2019-04-15 18:12:59.549 17009-17197/our.app V/sc: 6157 ms: --> GET https://some.server.tld/some-other/a/url
2019-04-15 18:12:59.550 17009-17197/our.app V/sc: 6159 ms: <-- HTTP FAILED: java.io.IOException: Canceled
2019-04-15 18:12:59.552 17009-17199/our.app V/sc: 6161 ms: --> GET https://some.server.tld/some-other/b/url
2019-04-15 18:12:59.554 17009-17199/our.app V/sc: 6163 ms: <-- HTTP FAILED: java.io.IOException: Canceled
2019-04-15 18:12:59.556 17009-17195/our.app V/sc: 6165 ms: <-- HTTP FAILED: java.io.IOException: Canceled
2019-04-15 18:12:59.557 17009-17197/our.app V/sc: 6166 ms: --> GET https://some.server.tld/some-other/c/url
2019-04-15 18:12:59.558 17009-17197/our.app V/sc: 6167 ms: <-- HTTP FAILED: java.io.IOException: Canceled
2019-04-15 18:12:59.559 17009-17199/our.app V/sc: 6168 ms: --> GET https://some.server.tld/some-other/d/url
2019-04-15 18:12:59.560 17009-17199/our.app V/sc: 6169 ms: <-- HTTP FAILED: java.io.IOException: Canceled
2019-04-15 18:12:59.561 17009-17195/our.app V/sc: 6170 ms: --> GET https://some.server.tld/some-other/e/url
2019-04-15 18:12:59.562 17009-17195/our.app V/sc: 6171 ms: <-- HTTP FAILED: java.io.IOException: Canceled
2019-04-15 18:12:59.562 17009-17197/our.app V/sc: 6171 ms: --> GET https://some.server.tld/some/url?with=query          // this is the one that will be reported
2019-04-15 18:12:59.565 17009-17199/our.app V/sc: 6174 ms: --> GET https://some.server.tld/some/similar-url?with=query
2019-04-15 18:12:59.567 17009-17202/our.app V/sc: 6176 ms: <-- HTTP FAILED: java.io.IOException: Canceled
2019-04-15 18:12:59.568 17009-17199/our.app V/sc: 6177 ms: <-- HTTP FAILED: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
2019-04-15 18:12:59.569 17009-17200/our.app V/sc: 6178 ms: <-- HTTP FAILED: java.io.IOException: Canceled
2019-04-15 18:12:59.569 17009-17190/our.app V/sc: 6178 ms: <-- HTTP FAILED: java.io.IOException: Canceled
```

**Comment by Antim4tter** [comment] 2020-05-11 21:52
I know is been almost 1 year after this crash but I',m using 3.10.0 version, did you find a way to reproduce it?
Thanks in advance
