### ISSUE TITLE
okhttp sse support stream response content-type:application/x-ndjson

### ISSUE THREAD

**Issue by MABIY** [square/okhttp#8511] opened 2024-08-16 01:45 UTC
when use okhttp sse reqeust stream [ollama api ](https://github.com/ollama/ollama/blob/main/docs/api.md) reponse content-type:application/x-ndjson. current okhttp sse not support.

use okhttp version:
okhttp version: 4.9.3
okhttp sse version: 4.9.3

exception stack:
```java
java.lang.IllegalStateException: Invalid content-type: application/x-ndjson
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:60) ~[okhttp-sse-4.9.3.jar:na]
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46) ~[okhttp-sse-4.9.3.jar:na]
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) ~[okhttp-4.9.3.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```
exception thrown from:
![image](https://github.com/user-attachments/assets/178668e0-997a-4fe7-9dc2-ebc08fd4e6de)

**Comment by JakeWharton** [comment] 2024-08-16 01:46
Duplicate of #8510. Please don't file duplicate issues.

**Closed by JakeWharton** 2024-08-16 01:46 UTC
Labels: enhancement
