### ISSUE TITLE
java.io.IOException: unexpected end of stream on okhttp3.Address

### ISSUE THREAD

**Issue by WanYouZhi** [square/okhttp#3006] opened 2016-11-25 02:23 UTC
it's get method ,the response back is http1.0 
 Caused by: java.io.EOFException: \n not found: size=0 content=…
at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:215)
at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
at ... 24 more

**Comment by JakeWharton** [comment] 2016-12-02 03:58
Dupe of #1517.

**Closed by JakeWharton** 2016-12-02 03:58 UTC

**Comment by xybCoder** [comment] 2017-01-03 08:23
I have the same problem. the bug is fix?

**Comment by juliovera78** [comment] 2017-01-20 14:55
the same happen to me.. ;(
