### ISSUE TITLE
Fatal exception java.lang.NullPointerException "ssl == null" in OutputStreamSink.java line 56

### ISSUE THREAD

**Issue by TheDukerChip** [square/okhttp#7431] opened 2022-09-01 07:30 UTC
Getting this exception in production app with at least 10+ occurrences per month.
Also we are unable to reproduce this issue.

### Exception Stacktrace
```
Fatal Exception: java.lang.NullPointerException: ssl == null
       at com.android.org.conscrypt.NativeCrypto.SSL_write(NativeCrypto.java)
       at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:824)
       at okio.OutputStreamSink.write(OutputStreamSink.java:56)
       at okio.AsyncTimeout$sink$1.write(AsyncTimeout.java:103)
       at okio.RealBufferedSink.flush(RealBufferedSink.java:247)
       at okhttp3.internal.http2.Http2Writer.applyAndAckSettings(Http2Writer.java:79)
       at okhttp3.internal.http2.Http2Connection$ReaderRunnable.applyAndAckSettings(Http2Connection.java:759)
       at okhttp3.internal.http2.Http2Connection$ReaderRunnable$settings$$inlined$execute$1.runOnce(Http2Connection.java:218)
       at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.java:115)
       at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.java:41)
       at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.java:64)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)

```

### Device Info

- OS: Android 7.1.2

Kindly let me know if any more details required and how to resolve this one

**Comment by yschimke** [comment] 2022-09-01 07:36
Dupe of https://github.com/google/conscrypt/issues/1083

**Closed by yschimke** 2022-09-01 07:36 UTC
