### ISSUE TITLE
Execution failed for task ':app:transformClassesWithDexBuilderForDevDebug'

### ISSUE THREAD

**Issue by liumulingyu** [square/okhttp#5327] opened 2019-08-03 09:43 UTC
open advanced profiling
run project:
Execution failed for task ':app:transformClassesWithDexBuilderForDevDebug'

**Comment by JakeWharton** [comment] 2019-08-05 17:05
Dupe of #5185, not an OkHttp issue.

**Closed by JakeWharton** 2019-08-05 17:05 UTC
Labels: bug
