### ISSUE TITLE
When retryOnConnectionFailure is enabled, failed requests do not terminate

### ISSUE THREAD

**Issue by bryanstern** [square/okhttp#2884] opened 2016-09-26 23:37 UTC
**Bug Report**

**Steps to Reproduce**

1. Set up a proxy, such as Charles Proxy, to intercept network requests.
2. With an `OkHttpClient` with `retryOnConnectionFailure` set to true (which it is by default), start a POST request with a callback. E.g. `Call call = okHttpClient.newCall(request); call.enqueue(callback);`
3. While the request is being sent, terminate it in Charles Proxy.

**Expected Behavior**
Once OkHttp stops retrying, `Callback#onFailure` should be called with
`okhttp3.internal.framed.StreamResetException: stream was reset: INTERNAL_ERROR`

**Actual Behavior**
Neither `Callback#onFailure` nor `Callback#onResponse` are called.

**Work Around**
```java
Call call = okHttpClient.newBuilder().retryOnConnectionFailure(false).newCall(request); 
call.enqueue(callback);
```

**Investigation**
Apologies for the lack of a test to demonstrate the issue. I'm having trouble figuring out how to repro it with a `MockWebServer` and am trying to wrap my head around the `RetryAndFollowUpInterceptor` and `StreamAllocation` classes enough to write a relevant test to try to expose the issue.

**Comment by swankjesse** [comment] 2016-10-16 15:57
Fix in progress here: https://github.com/square/okhttp/pull/2889

**Comment by swankjesse** [comment] 2016-10-16 15:57
Duplicate of https://github.com/square/okhttp/issues/2756

**Closed by swankjesse** 2016-10-16 15:57 UTC
