### ISSUE TITLE
NullPointerException in okio/okhttp3

### ISSUE THREAD

**Issue by steelbytes** [square/okhttp#3991] opened 2018-05-08 04:36 UTC
got following crash in google play dev console using okhttp3.10 okio1.14
(only once but some hardening would be nice)

java.lang.NullPointerException: 
  at com.android.org.conscrypt.NativeCrypto.SSL_read (NativeCrypto.java)
  at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read (OpenSSLSocketImpl.java:789)
  at okio.Okio$2.read (Okio.java)
  at okio.AsyncTimeout$2.read (AsyncTimeout.java)
  at okio.RealBufferedSource.request (RealBufferedSource.java)
  at okio.RealBufferedSource.require (RealBufferedSource.java)
  at okhttp3.internal.http2.Http2Reader.nextFrame (Http2Reader.java)
  at okhttp3.internal.http2.Http2Connection$ReaderRunnable.execute (Http2Connection.java)
  at okhttp3.internal.NamedRunnable.run (NamedRunnable.java)
  at java.lang.Thread.run (Thread.java:762)

Samsung Galaxy J7 Prime (j7popeltemtr), 2048MB RAM, Android 7.0

**Comment by yschimke** [comment] 2018-05-09 06:56
@swankjesse I know this is Android bug, but given it's not in app code either, should we consider handling in key places similarly to RealConnection.connectSocket?

```
    // The following try/catch block is a pseudo hacky way to get around a crash on Android 7.0
    // More details:
    // https://github.com/square/okhttp/issues/3245
    // https://android-review.googlesource.com/#/c/271775/
    try {
      source = Okio.buffer(Okio.source(rawSocket));
      sink = Okio.buffer(Okio.sink(rawSocket));
    } catch (NullPointerException npe) {
      if (NPE_THROW_WITH_NULL.equals(npe.getMessage())) {
        throw new IOException(npe);
      }
    }
```

Maybe this could be handled across the whole codebase by a Okio wrapper?

**Comment by swankjesse** [comment] 2018-05-09 11:30
It mostly depends on frequency. If this impacted one device once we should ignore it.

If it impacts many devices we should attempt to get the root cause fixed, and then perhaps paper over the problem if people aren't able to get that fix.

In this case we're still without a root cause. Might be something specific to this app, like a bad JNI library that is scribbling over the managed heap.

**Comment by yschimke** [comment] 2018-06-16 10:28
Closing as a one off, I don't think we are planning a fix unless you see a significant number of these errors, especially with a rising android version e.g. 8.1.0

**Closed by yschimke** 2018-06-16 10:28 UTC
