### ISSUE TITLE
Runtime dependency conflicts

### ISSUE THREAD

**Issue by aaron-ai** [square/okhttp#7373] opened 2022-07-10 09:02 UTC
I used maven enforcer plugin to scan the dependencies in my project, and found `kotlin-stdlib` conficts.

![image](https://user-images.githubusercontent.com/19537356/178138250-2c6ef3e0-47c7-4542-96b2-5271575db948.png)

**Comment by yschimke** [comment] 2022-07-10 09:05
Working as intended. Given kotlin's strong versioning story, this is not an issue, and impossible to avoid when kotlin is an implementation dependency for multiple projects released independently.

Discussion here. https://github.com/square/okhttp/issues/7328

**Closed by yschimke** 2022-07-10 09:05 UTC
Labels: bug
