### ISSUE TITLE
Network connection Issue in emulator 

### ISSUE THREAD

**Issue by unnamedw** [square/okhttp#6338] opened 2020-10-23 10:04 UTC
`private fun startUpdate() = viewModelScope.launch {
        isUpdating = true
        while (isUpdating) {
            try {
                bithumbRepository.update()
            } catch (e: Exception) {
                e.printStackTrace()
            }
            delay(3000)
        }
    }`

The above codes is wrote in my viewmodel, and it works well in normal.

But when I disconnect mobile data and connect wifi in emulator (or switch both network connection more repeatedly), 
requests stuck and I can't receive any responses from server side.
I also checked logs using okhttp log interceptor, it just return following line and no response.
`D/OkHttp: --> END GET`

The most tricky point is that it has no problem in real device.

Is threre any point in the change of network state in emulator or retrofit&okhttp?

**Comment by yschimke** [comment] 2020-10-24 05:26
Closing as a duplicate of 

https://github.com/square/okhttp/issues/4079
https://github.com/square/okhttp/issues/3278

The emulators behave differently than real devices and we don't hook in with the Android APIs that would let us discover network changes other than socket disconnects.

**Closed by yschimke** 2020-10-24 05:26 UTC
Labels: bug
