### ISSUE TITLE
Flaky WebSocketHttpTest.throwingOnClosingClosesImmediatelyAndFails test

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#3507] opened 2017-08-06 14:25 UTC
https://api.travis-ci.org/jobs/261536643/log.txt?deansi=true

```
INFO: [WS client] onFailure
java.lang.RuntimeException
	at okhttp3.internal.ws.WebSocketHttpTest.throwingOnClosingClosesImmediatelyAndFails(WebSocketHttpTest.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:113)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:85)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:54)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:134)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

**Comment by jaredsburrows** [comment] 2017-08-24 05:48
@yschimke Since @swankjesse merged the PR, you can now close this issue.

**Comment by yschimke** [comment] 2017-08-24 07:44
I've seen this failure since.  Specifically it failed again for me on this PR yesterday https://github.com/square/okhttp/pull/3535

**Comment by yschimke** [comment] 2017-08-25 05:38
Saw this again, so probably high priority to fix again before a release.  Unless it's well known.

**Comment by yschimke** [comment] 2017-08-25 05:49
Testing in CI with https://github.com/square/okhttp/pull/3539

**Comment by jaredsburrows** [comment] 2017-08-28 23:23
@yschimke CI passed?

**Comment by yschimke** [comment] 2017-08-29 05:24
@jaredsburrows yes, it's a flaky test.  I haven't seen it again, but I'm convinced it is still there :) . My white whale.

**Comment by swankjesse** [comment] 2017-08-30 19:02
Dupe of https://github.com/square/okhttp/issues/3138

**Closed by swankjesse** 2017-08-30 19:02 UTC
Labels: bug, tests
