### ISSUE TITLE
IllegalStateException in Connection.closeIfOwnedBy()

### ISSUE THREAD

**Issue by felipecsl** [square/okhttp#1805] opened 2015-08-13 20:40 UTC
Been seeing a few of these, mostly on Lollipop 5.0.x
Offending line is `if (isFramed()) throw new IllegalStateException();`
```
at com.squareup.okhttp.Connection.closeIfOwnedBy(Connection.java:137)
at com.squareup.okhttp.OkHttpClient$1.closeIfOwnedBy(OkHttpClient.java:75)
at com.squareup.okhttp.internal.http.HttpEngine.disconnect(HttpEngine.java:577)
at com.squareup.okhttp.Call.cancel(Call.java:122)
at retrofit.OkHttpCall.cancel(OkHttpCall.java:158)
at retrofit.ObservableCallAdapterFactory$CallOnSubscribe$1.call(ObservableCallAdapterFactory.java:92)
at rx.subscriptions.BooleanSubscription.unsubscribe(BooleanSubscription.java:72)
at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
at rx.Subscriber.unsubscribe(Subscriber.java:81)
at rx.internal.operators.OperatorUnsubscribeOn$2$1.call(OperatorUnsubscribeOn.java:66)
at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
```

**Comment by swankjesse** [comment] 2015-10-31 01:48
Yikes. Can fix.

**Comment by bjorkmann** [comment] 2015-11-14 20:26
Would also love to see a fix for this. Catching IllegalStateException is making me sad.

**Comment by thest1** [comment] 2015-11-20 02:04
Also have a lot of these. Can confirm it happens only in Android 5+.

**Comment by swankjesse** [comment] 2015-12-01 04:10
Fixed by https://github.com/square/okhttp/pull/2045

**Closed** 2015-12-01 04:18 UTC
Labels: bug

**Comment by leofirespotter** [comment] 2016-03-07 22:12
So for some reason, this issue seems to be back for me as of 3.1.2. Any possibility that this regressed? It definitely went a way for a little while.

**Comment by swankjesse** [comment] 2016-03-09 12:30
@leofirespotter able to reproduce?

**Comment by leofirespotter** [comment] 2016-03-09 18:54
@swankjesse no I have not been able to reproduce. But here is the [crash report](http://crashes.to/s/6fd196ded59) on crashlytics. Version 2.3 of my app was released back in early Nov and was using okhttp 2.5. And then the issue went away in version 2.4 of my app using okhttp 2.7. And now its back, version 3.0 is using okhttp 3.1.2

**Comment by swankjesse** [comment] 2016-03-10 00:53
That crash report suggests some part of your app is using OkHttp 2.x. The package name in OkHttp 3.1.2 is `okhttp3`, not `com.squareup.okhttp`.

**Comment by leofirespotter** [comment] 2016-03-10 01:48
@swankjesse damn good point. Fresco hasn't updated so it was still using the old version. That is probably why it regressed, I went from using 2.7 everywhere, to using 3.1.2 in my app, but Fresco is probably still using 2.5. Thanks for the help.
