### ISSUE TITLE
DiskLruCache line 683 okhttp3.internal.cache.DiskLruCache.trimToSize

### ISSUE THREAD

**Issue by zahidgirnar** [square/okhttp#3778] opened 2018-01-15 08:51 UTC
DiskLruCache line 683
okhttp3.internal.cache.DiskLruCache.trimToSize

Fatal Exception: java.util.NoSuchElementException
       at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:349)
       at java.util.LinkedHashMap$ValueIterator.next(LinkedHashMap.java:370)
       at okhttp3.internal.cache.DiskLruCache.trimToSize(SourceFile:683)
       at okhttp3.internal.cache.DiskLruCache$1.run(SourceFile:176)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

**Comment by yschimke** [comment] 2018-01-15 09:16
Is this a once off or happening regularly? Can you provide more information e.g. it looks like this is with an older version of okhttp based on line numbers.

**Comment by zahidgirnar** [comment] 2018-01-15 09:21
http://crashes.to/s/4723371f419

[image: border] [image: border] [image: border] [image: border] [image:
border]


[image: CarDekho] <http://www.cardekho.com/>

  [image: facebook]
<https://www.facebook.com/pages/CarDekho/179167414600>   [image:
twitter] <https://twitter.com/CarDekho>   [image: google plus]
<https://plus.google.com/+cardekho>   [image: youtube]
<https://www.youtube.com/user/CarDekhoChannel>


[image: Location]
*Zahid Naqvi | Senior Architect (Mobile Apps)Skype: arcsoft_zahid |
+91-823-333-2828*
Girnar Software Pvt. Ltd., JTM, Model Town, Near Jagatpura Flyover,
Jaipur-302017, Rajasthan, India

    Office Ph: 0141- 6666 625


CarDekho.com <http://www.cardekho.com/>   GirnarSoft.com
<http://www.girnarsoft.com/>   Gaadi.com <http://www.gaadi.com/>
Zigwheels.com <http://www.zigwheels.com/>   BikeDekho.com
<https://www.bikedekho.com/>

TrucksDekho.com <http://trucks.cardekho.com/>   TyreDekho.com
<http://tyres.cardekho.com/>   CarBay.com <http://www.carbay.com/>
PriceDekho.com <http://www.pricedekho.com/>   CollegeDekho.com
<http://www.collegedekho.com/>
[image: Wave Image]   [image: Wave Image]

**Comment by swankjesse** [comment] 2018-02-18 18:57
Something in the cache is getting corrupted, so that the cache is empty but doesn’t know it. An executable test case would help to reproduce.

**Comment by stepforward** [comment] 2019-06-06 02:57
I have the same bug report in okhttp:3.12.0
and this bug has been reported too many times.

![image](https://user-images.githubusercontent.com/6511474/59003737-bb6d3f80-8849-11e9-993c-55e5479c3ad4.png)


java.util.NoSuchElementException: empty message
java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:759)
java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:785)
okhttp3.internal.cache.DiskLruCache.trimToSize(DiskLruCache.java:684)
okhttp3.internal.cache.DiskLruCache$1.run(DiskLruCache.java:177)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
java.lang.Thread.run(Thread.java:764)

**Comment by sososeen09** [comment] 2020-03-06 08:06
I have the same bug with okhttp:3.12.1，has it fixed in 3.12.x version？

**Comment by redmanit** [comment] 2020-08-26 08:25
I got more than 150 crashes everyday because of this issue

Fatal Exception: java.util.NoSuchElementException
       at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:759)
       at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:785)
       at okhttp3.internal.cache.DiskLruCache.trimToSize(DiskLruCache.java:652)
       at okhttp3.internal.cache.DiskLruCache$cleanupTask$1.runOnce(DiskLruCache.java:180)
       at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.java:115)
       at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.java:41)
       at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.java:64)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

**Comment by swankjesse** [comment] 2020-08-26 11:12
@redmanit do you mind opening a new tracking bug?

**Comment by redmanit** [comment] 2020-12-23 02:07
This bug is my top 1 crash on Crashlytics. Any update on this?
My app have more than one process, all of them use okhttp. Not sure if this behavior causes the issue.

**Comment by yschimke** [comment] 2020-12-23 08:54
Nope. From https://github.com/square/okhttp/issues/6453 the best advice is make extra sure you never create two Cache instances pointing at the same directory. But since this is failing on java collection iteration, not file corruption, even that seems unlikely.  So probably a separate issue.

@redmanit any contextual information you can provide? device types, OS versions, okhttp version?  If you are not on 3.12.12 or 4.9.0 please upgrade to one of those.

**Comment by redmanit** [comment] 2020-12-25 09:13
> Nope. From #6453 the best advice is make extra sure you never create two Cache instances pointing at the same directory. But since this is failing on java collection iteration, not file corruption, even that seems unlikely. So probably a separate issue.
> 
> @redmanit any contextual information you can provide? device types, OS versions, okhttp version? If you are not on 3.12.12 or 4.9.0 please upgrade to one of those.

As I said my app has more than one processes and all of them use Glide so there are more than one Cache instance pointing at the same directory. This is expected behavior so I can't change that.
I'm using okhttp 4.3.1 (with Retrofit), will update soon but I don't think it will fix this very old issue.

About the crashes: 93% Android 10, 4% Android 9, 3 % Android 8...; 75% Samsung, 12% HMD Global, 3% Xiaomi...

**Comment by yschimke** [comment] 2020-12-25 09:42
I don't think we can really support multiple processes using same cache. So if it works then stick with it, but if not then separate them out.

**Comment by redmanit** [comment] 2021-02-01 10:55
> I don't think we can really support multiple processes using same cache. So if it works then stick with it, but if not then separate them out.

You don't need to support mutiple processes, just don't crash.

**Comment by swankjesse** [comment] 2021-02-01 13:03
Unfortunately it's difficult to determine if there are multiple processes. For example, Firefox uses a PID file but it may refuse to launch after a crash.

**Comment by ravikwynk** [comment] 2021-03-03 06:54
Facing the same issue on version 3.14.9.
Fatal Exception: java.util.NoSuchElementException
       at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:759)
       at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:785)
       at okhttp3.internal.cache.DiskLruCache.trimToSize(DiskLruCache.java:678)
       at okhttp3.internal.cache.DiskLruCache$1.run(DiskLruCache.java:177)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)

**Comment by yschimke** [comment] 2021-07-28 08:36
Going to close this out as OkHttp 5, uses the Okio filesystem abstraction.  We can reopen with a reproducing test case or more logging from OkHttp 5 alpha.

**Closed by yschimke** 2021-07-28 08:36 UTC
Labels: bug, needs info

**Comment by parasgupta93** [comment] 2021-11-09 12:10
I am also facing the same issue on version 3.11.0. Does anyone know the root cause?
Fatal Exception: java.util.NoSuchElementException
       at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:759)
       at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:785)
       at okhttp3.internal.cache.DiskLruCache.trimToSize(DiskLruCache.java:684)
       at okhttp3.internal.cache.DiskLruCache$1.run(DiskLruCache.java:177)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
