### ISSUE TITLE
SIGSEGV crashes on Samsung Devices w/ OkHttp 2.3

### ISSUE THREAD

**Issue by JaredBanyard** [square/okhttp#1561] opened 2015-04-16 16:07 UTC
This is the stacktrace we are getting back from the Crittercism native bug reporting client.  It is pretty cryptic, but it looks very similar to the other SIGSEGV faults on Samsung devices.

0	libc.so + 0x11884
1	libc.so + 0x49ffe
2	libc.so + 0xdd23
3	libcrypto.so + 0x82485
4	libssl.so + 0x2aafb
5	libssl.so + 0x33317
6	libssl.so + 0x33317
7	libcrypto.so + 0x124ac6
8	libssl.so + 0x16bdb
9	libjavacrypto.so + 0xa5db
10	libssl.so + 0x196dd
11	libjavacrypto.so + 0xbc15
12	dalvik-heap (deleted) + 0x1279259a
13	libssl.so + 0x24fc9
14	libjavacrypto.so + 0xe2bb
15	dalvik-LinearAlloc (deleted) + 0x22d46
16	dalvik-LinearAlloc (deleted) + 0x2b0afe
17	libdvm.so + 0x20ece

**Comment by swankjesse** [comment] 2015-04-16 23:35
Know anything about the Android version on the impacted devices?

**Comment by JaredBanyard** [comment] 2015-04-17 00:19
Model - OS:
SCH-I545 - 4.4.2 x 2
SGH-I337 - 4.4.4 x 2
SM-G900A - 4.4.4
SM-G900V - 4.4.4 x 2
SM-N900T - 4.4.2
SN-G870A - 4.4.4

**Comment by JaredBanyard** [comment] 2015-04-17 00:22
Also getting a SIGABRT crash on these same phones:

0	libc.so + 0x22144
1	libssl.so + 0x33317
2	libssl.so + 0x33317
3	libc.so + 0x1319b
4	libc.so + 0x133af
5	libc.so + 0x120e5
6	dalvik-heap (deleted) + 0x7d45b50
7	libc.so + 0x219fa
8	dalvik-mark-stack (deleted) + 0x6945545
9	libc.so + 0x12bcb
10	libc.so + 0x40155
11	libc.so + 0xf2d7
12	libc.so + 0x40155
13	libc.so + 0x43d3f
14	libc.so + 0x101e3
15	libc.so + 0xff83
16	libssl.so + 0x33317
17	libcrypto.so + 0x127e32
18	libc.so + 0xdd0f
19	libcrypto.so + 0x12af4e
20	libcrypto.so + 0x81e39
21	libcrypto.so + 0x81e2f
22	libcrypto.so + 0x822d3
23	libssl.so + 0x33317
24	libssl.so + 0x2ab0d
25	libssl.so + 0x33317
26	libssl.so + 0x33317
27	libcrypto.so + 0x124ac6
28	libssl.so + 0x16bdb
29	libjavacrypto.so + 0xa5db
30	libssl.so + 0x196dd
31	libjavacrypto.so + 0xbc15
32	dalvik-heap (deleted) + 0x127924ad
33	libssl.so + 0x24fc9
34	libjavacrypto.so + 0xe2bb
35	dalvik-LinearAlloc (deleted) + 0x22d46
36	dalvik-LinearAlloc (deleted) + 0x2b0afe
37	libdvm.so + 0x20ece
38	conscrypt.odex + 0x3924b
39	dalvik-zygote (deleted) + 0x17690e
40	dalvik-zygote (deleted) + 0x168cce
41	libdvm.so + 0x51b71
42	conscrypt.odex + 0x39243
43	libjavacrypto.so + 0xe1c3
44	libdvm.so + 0xcceae
45	dalvik-heap (deleted) + 0x6
46	libdvm.so + 0x2103e
47	libdvm.so + 0xcceae
48	dalvik-zygote (deleted) + 0x168cce
49	dalvik-heap (deleted) + 0x9f6936
50	dalvik-heap (deleted) + 0x9f6936
51	libdvm.so + 0x775e9
52	libdvm.so + 0xc6c06
53	libdvm.so + 0xcceae
54	libdvm.so + 0x2d51a
55	dalvik-mark-stack (deleted) + 0x6945545
56	dalvik-zygote (deleted) + 0x168cce
57	dalvik-mark-stack (deleted) + 0x6945545
58	conscrypt.odex + 0x26eaa
59	dalvik-zygote (deleted) + 0x17690e
60	libdvm.so + 0x2103e
61	dalvik-zygote (deleted) + 0x168cce
62	libdvm.so + 0x2a362
63	libdvm.so + 0x317c2
64	dalvik-LinearAlloc (deleted) + 0x5eee
65	dalvik-heap (deleted) + 0x8cabe6
66	libdvm.so + 0x31812
67	libdvm.so + 0x317c2
68	libdvm.so + 0x2eeaa
69	dalvik-heap (deleted) + 0x412ffe
70	dalvik-LinearAlloc (deleted) + 0x5eee
71	core.odex + 0x1f9777
72	libdvm.so + 0x63fdf
73	libdvm.so + 0x739c1
74	libdvm.so + 0xcceae
75	libc.so + 0x4c2ea
76	libdvm.so + 0x64003
77	libdvm.so + 0x58cd5
78	dalvik-mark-stack (deleted) + 0x9e6ef6e
79	libwebviewchromium.so + 0x5cd42b
80	dalvik-heap (deleted) + 0x1eb6a266
81	dalvik-mark-stack (deleted) + 0x6945545
82	libdvm.so + 0x58c33
83	libdvm.so + 0x58c33
84	libc.so + 0xd28a
85	libc.so + 0xd422
86	dalvik-mark-stack (deleted) + 0x6945545

**Comment by swankjesse** [comment] 2015-04-17 00:26
Are you able to reproduce this reliably?

**Comment by JaredBanyard** [comment] 2015-04-17 00:37
Unfortunately, no.  It seems to happen very occasionally.  I will update this report if I can get some users to report any causes or patterns.

**Comment by swankjesse** [comment] 2015-04-17 00:39
It would be really handy to know what the app is doing when it crashes. Sometimes native crashes contain native stacktraces; with this it's difficult to see whether it's failing in NPN or something else.

**Comment by swankjesse** [comment] 2015-04-19 01:09
Closing since there's no clear actions for us to take on this. If you can figure out how to reproduce, please let me know and I'll reopen.

**Closed by swankjesse** 2015-04-19 01:09 UTC
