### ISSUE TITLE
java.lang.NullPointerException: Deflater has been closed

### ISSUE THREAD

**Issue by Layneboy** [square/okhttp#6719] opened 2021-06-18 01:38 UTC
java.lang.NullPointerException: Deflater has been closed
	at java.util.zip.Deflater.ensureOpen(Deflater.java:551)
	at java.util.zip.Deflater.deflate(Deflater.java:426)
	at java.util.zip.Deflater.deflate(Deflater.java:352)
	at okio.DeflaterSink.long okio.Buffer.size()()
                      void deflate(boolean)
                      void okio.Buffer.setSize$okio(long)
                      void deflate(boolean)
                      void deflate(boolean)
	at okio.DeflaterSink.void write(okio.Buffer,long)(:2)
	at okhttp3.internal.ws.WebSocketWriter.void okhttp3.internal.ws.MessageDeflater.deflate(okio.Buffer)(:7)
                                        void writeMessageFrame(int,okio.ByteString)
	at okhttp3.internal.ws.RealWebSocket.boolean writeOneFrame$okhttp()(:7)
	at okhttp3.internal.ws.RealWebSocket$WriterTask.long runOnce()()
	at okhttp3.internal.concurrent.TaskRunner.void runTask(okhttp3.internal.concurrent.Task)(:3)
                                           void access$runTask(okhttp3.internal.concurrent.TaskRunner,okhttp3.internal.concurrent.Task)
	at okhttp3.internal.concurrent.TaskRunner$runnable$1.void run()(:7)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

**Comment by yschimke** [comment] 2021-06-18 05:15
Can you provide a bug reproduction, it isn't clear from the stacktrace what type of behaviour will trigger this bug.

**Comment by IvanShafran** [comment] 2021-06-21 23:23
Hello!

I'm getting precisely the same problem on version 4.9.1. Unfortunately, I can't reproduce this. My guess was about the concurrency issue during simultaneous shutdown and writing. More specifically, shutdown should be caused by some failure because I have another problem that may be connected to this: https://github.com/square/okhttp/issues/6723

I had run a stress test with lots of send operations and fail during onMessage callback, but I got nothing from this. Everything was fine.

Is there any chance that two WebSockets with the same endpoint may share Deflater? RealWebSocket code shows that it creates it for every instance. But maybe I missed something.

Thank you for any help or feedback! I'm stuck on this problem for a while.

```
Fatal Exception: java.lang.NullPointerException: Deflater has been closed
       at java.util.zip.Deflater.ensureOpen(Deflater.java:583)
       at java.util.zip.Deflater.deflate(Deflater.java:458)
       at java.util.zip.Deflater.deflate(Deflater.java:384)
       at okio.DeflaterSink.deflate(DeflaterSink.kt:91)
       at okio.DeflaterSink.write(DeflaterSink.kt:64)
       at okhttp3.internal.ws.MessageDeflater.deflate(MessageDeflater.kt:45)
       at okhttp3.internal.ws.WebSocketWriter.writeMessageFrame(WebSocketWriter.kt:155)
       at okhttp3.internal.ws.RealWebSocket.writeOneFrame$okhttp(RealWebSocket.kt:527)
       at okhttp3.internal.ws.RealWebSocket$WriterTask.runOnce(RealWebSocket.kt:620)
       at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
       at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
       at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by yschimke** [comment] 2021-06-27 18:11
Like #6723 we are probably blocked reproducing this without a leap in insight, so might be worth us focusing on how to avoid the cases we are worried about like thread unsafety (#6725)

**Comment by yschimke** [comment] 2021-07-28 08:30
Going to close this unless we can get a reproduction. Any failing test case, or example code that triggers it would be helpful.

**Closed by yschimke** 2021-07-28 08:30 UTC
Labels: bug, needs info

**Comment by vitorpamplona** [comment] 2023-09-01 12:09
We have been getting many crash reports in the same line. 

It's difficult to reproduce, but extremely common error. The worst is that it just crashes the entire app/server. Could this be a malformed compression from the WS server? 

```java
Exception java.lang.NullPointerException: Deflater has been closed
  at java.util.zip.Deflater.ensureOpen (Deflater.java:583)
  at java.util.zip.Deflater.deflate (Deflater.java:458)
  at java.util.zip.Deflater.deflate (Deflater.java:384)
  at okio.DeflaterSink.deflate (DeflaterSink.kt)
  at okio.DeflaterSink.write (DeflaterSink.kt)
  at okhttp3.internal.ws.MessageDeflater.deflate (MessageDeflater.kt)
  at okhttp3.internal.ws.WebSocketWriter.writeMessageFrame (WebSocketWriter.kt)
  at okhttp3.internal.ws.RealWebSocket.writeOneFrame$okhttp (RealWebSocket.kt)
  at okhttp3.internal.ws.RealWebSocket$WriterTask.runOnce (RealWebSocket.kt)
  at okhttp3.internal.concurrent.TaskRunner.runTask (TaskRunner.kt)
  at okhttp3.internal.concurrent.TaskRunner.access$runTask (TaskRunner.kt)
  at okhttp3.internal.concurrent.TaskRunner$runnable$1.run (TaskRunner.kt)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1137)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:637)
  at java.lang.Thread.run (Thread.java:1012)
```

**Comment by vitorpamplona** [comment] 2023-09-01 14:09
This seems to be correlated with an onFailure event 

```
    java.net.ProtocolException: Control frames must be final.
      	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:130)
      	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:102)
      	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
      	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
      	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:539)
      	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
      	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
      	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by yschimke** [comment] 2023-09-01 14:41
This suggests okio should probably convert NPE here to an IOException.

```
Exception java.lang.NullPointerException: Deflater has been closed
  at java.util.zip.Deflater.ensureOpen (Deflater.java:583)
  at java.util.zip.Deflater.deflate (Deflater.java:458)
  at java.util.zip.Deflater.deflate (Deflater.java:384)
  at okio.DeflaterSink.deflate (DeflaterSink.kt)
```

**Comment by vitorpamplona** [comment] 2023-09-01 15:42
Can it pipe it down to a catchable event, though?

**Comment by yschimke** [comment] 2023-09-01 16:41
https://github.com/square/okio/issues/570 suggests this might be an OkHttp bug. But I still think Okio should handle it, if it's somewhat normal.

**Comment by Sn0w3y** [comment] 2024-05-03 05:21
Hello together - have the same Error. Happens occasionally. Exact one as OP
