### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: size=1179 offset=68719476998 byteCount=1

### ISSUE THREAD

**Issue by FightingLarry** [square/okhttp#7268] opened 2022-05-05 07:44 UTC
Help with this bug.

post request：https://***/appserver/gateway/device/v1

AndroidRuntime: FATAL EXCEPTION:
java.lang.ArrayIndexOutOfBoundsException: size=1179 offset=68719476998 byteCount=1
    at okio.-Util.checkOffsetAndCount(-Util.java:54)
    at okio.Buffer.getByte(Buffer.java:0)
    at okio.internal.BufferKt.readUtf8Line(BufferKt.java:15)
    at okio.RealBufferedSource.G(RealBufferedSource.java:46)
    at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.java:4)
    at okhttp3.internal.http1.Http1ExchangeCodec.g(Http1ExchangeCodec.java:14)
    at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:0)
    at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:0)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:0)
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:0)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:0)
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:0)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:0)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:0)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:0)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:0)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:0)
    at com.baidu.duershow.rxhttp.interceptor.TimeoutInterceptor.intercept(TimeoutInterceptor.java:0)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:0)
    at com.baidu.duershow.rxhttp.interceptor.HeaderInterceptor.intercept(HeaderInterceptor.java:0)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:0)
    at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.java:0)
    at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:0)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)

version:
okhttp3:okhttp-4.8.1.jar
okio:okio-2.7.0.jar
retrofit2:retrofit-2.8.2.jar

The same bug:
https://github.com/square/okhttp/issues/6688

**Comment by yschimke** [comment] 2022-05-08 09:06
It's the same answer.

> There isn't much we can do with this report (sorry). Generally this could happen with weird multithreading issues. Closing for now.

Can you make a reproduction? Without sample code or preferably a clean repro, we can't do anything.  But look for anywhere you are processing a single call and response across multiple threads.

Closing as a dupe.

**Closed by yschimke** 2022-05-08 09:06 UTC
Labels: bug
