### ISSUE TITLE
Transparent Gzip + Content-Range

### ISSUE THREAD

**Issue by nfuller** [square/okhttp#1463] opened 2015-03-02 17:20 UTC
With transparent GZIP, OkHttp clears the content-length and the content-encoding so that clients are free to pretend the data was not gzip encoded. The content-length is cleared because it's not possible to know the uncompressed size.

The HTTP spec suggests that Content-Range headers relate to the entity-body (which implies the range in the compressed content, if compression is taking place). With the content-encoding cleared, I don't think it's possible to know whether the content-range given refers to the compressed or identity encoding, since identity encoding may be sent with no content-encoding header as well. The Content-Range may therefore be useless.

Removing Content-Range is also probably not useful - the client is left with something that is not obviously a sub-range(?). Transparently decompressing the data for the client is (I assume) not feasible because of the nature of gzip encoding.

This may be theoretical rather than an actual problem, depending on how servers actually deal with this. Gzip encoding and range requests seem a not-very-useful combination anyway. This came up during a discussion about Android's transparent gzip behavior, not because anybody was trying to use it.

Perhaps disabling transparent gzip for range requests (e.g. keep the gzip encoding, the app must gunzip), failing requests with range + transparent gzip, or just treating/documenting Range requests with gzip as an unsupported configuration. The workaround would be having apps set Accept-Encoding to "gzip" or "identity" explicitly so the encoding used (and thus the meaning of the range) is clear. This would force the client to deal with gzip data if they'd asked for it.

Some information found while looking into it:
http://mailman.nginx.org/pipermail/nginx/2011-June/027712.html

**Comment by swankjesse** [comment] 2015-03-02 22:56
Dupe of https://github.com/square/okhttp/issues/116

**Closed by swankjesse** 2015-03-02 22:56 UTC
