### ISSUE TITLE
Https proxy Proxy-Authorization is missing

### ISSUE THREAD

**Issue by zi6xuan** [square/okhttp#3925] opened 2018-03-15 00:49 UTC
Here what's happening:
HTTP: the client send directly the full request to the proxy, with the proxy-auth headers. The proxy is in charge to forward to server.
HTTPS: the client want to send a request to a server, encrypted with the server public key, passing through an http proxy. So
before making the request itself, the client have to get the server public key (i.e. make SSL handshake, i.e. etablish a SSL/TLS tunnel to the server)
the HTTPS request will be encrypted so the proxy won't have access to the request headers (in case of a normal proxy)
What happens:
The client send a HTTP CONNECT to the proxy, indicating the hostname of the server to connect with and also probably the proxy-auth headers
The proxy connect the client with the server (here with an internal https server instead of remote one, to be able to decrypt and modify)
Client and server (internal one here) makes SSL handshake
Client send the HTTPS request to the server, without proxy-auth headers because the proxy is not supposed to have access to it

```
   private Request createTunnelRequest() {
     return new Request.Builder()
         .url(route.address().url())
         .header("Host", Util.hostHeader(route.address().url(), true))
         .header("Proxy-Connection", "Keep-Alive") // For HTTP/1.0 proxies like Squid.
         .header("User-Agent", Version.userAgent())
         .build();
   }
```
I watch the source code and debug it,I found the createTunnelRequestnot add the Proxy-Authorization,so The https request is can not be connected

```
    private Request createTunnelRequest(Call call) {
         Request.Builder builder = new Request.Builder()
                 .url(route.address().url())
                .header("Host", Util.hostHeader(route.address().url(), true))
                 .header("Proxy-Connection", "Keep-Alive") // For HTTP/1.0 proxies like Squid.
                 .header("User-Agent", Version.userAgent());
         String value = call.request().header("Proxy-Authorization");
         if (value != null) {
             builder.header("Proxy-Authorization", value);
         }
         return builder.build();
     }
```
it's worked

**Comment by yschimke** [comment] 2018-03-21 06:10
I believe this is described here

https://github.com/square/okhttp/blob/c70e35802e984e8b9bf3fbf1479deb37c0bdfa43/okhttp/src/main/java/okhttp3/Authenticator.java

I think what your suggesting is sending the Proxy-Authorization before being challenged by the proxy server.  I don't know whether this breaks the spec or causes additional problems.

Also just using the Authenticator should handle this for you https://github.com/square/okhttp/blob/9f8200d1e0f79649d0c5d55db669971f35322ea9/okhttp-urlconnection/src/main/java/okhttp3/JavaNetAuthenticator.java

**Comment by zi6xuan** [comment] 2018-03-22 04:34
I do not know what the reason, but I modified the source code, recompile is run
add the `builder.header("Proxy-Authorization", 'Base xxxxxxxxx');`

**Comment by yschimke** [comment] 2018-03-22 05:36
Have you implemented an Authenticator as shown above?  Or is the only place you are setting this header in the changes you made to OkHttp internal code?

**Comment by zi6xuan** [comment] 2018-03-23 02:30
Authenticator is not implemented，Because http access is normal, only https will have this problem

**Comment by swankjesse** [comment] 2018-07-05 01:28
Duplicate of https://github.com/square/okhttp/issues/2435
I’m going to bump issue that to make sure we get to it soon.

**Closed by swankjesse** 2018-07-05 01:28 UTC
Labels: needs info
