### ISSUE TITLE
Call.cancel on main thread annoy StrictMode guard.

### ISSUE THREAD

**Issue by pepyakin** [square/okhttp#869] opened 2014-05-27 16:34 UTC
There are `Call#enqueue` method. 
It looks like I should use this method from main thread to asynchroniously execute this call on some background thread so I don't care. If I start request on main thread it is very likely that I will also cancel it on main thread. 

But there is a problem on Android however with HTTPS connection
```
    android.os.NetworkOnMainThreadException
            at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1145)
            at com.android.org.conscrypt.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:1009)
            at com.squareup.okhttp.Connection.closeIfOwnedBy(Connection.java:134)
            at com.squareup.okhttp.OkHttpClient$1.closeIfOwnedBy(OkHttpClient.java:63)
            at com.squareup.okhttp.internal.http.HttpConnection.closeIfOwnedBy(HttpConnection.java:136)
            at com.squareup.okhttp.internal.http.HttpTransport.disconnect(HttpTransport.java:155)
            at com.squareup.okhttp.internal.http.HttpEngine.disconnect(HttpEngine.java:480)
            at com.squareup.okhttp.Call.cancel(Call.java:113)
```

**Comment by swankjesse** [comment] 2015-11-30 04:02
Duplicate of https://github.com/square/okhttp/issues/1592

**Closed by swankjesse** 2015-11-30 04:02 UTC
Labels: bug
