### ISSUE TITLE
Crash when disconnecting

### ISSUE THREAD

**Issue by NVentimiglia** [square/okhttp#1913] opened 2015-10-08 18:43 UTC
- Connect to the websocket normally
- Disable Wifi / Cellular
- Application hard crashes

> 10-08 11:42:23.312 D/Mono    ( 5092): Assembly Ref addref Realtime.Messaging[0xa9a54e80] -> System.Text.Encoding[0xa9aff580]: 2
10-08 11:42:23.408 E/art     ( 5092): JNI ERROR (app bug): accessed deleted global reference 0x300d6e
10-08 11:42:23.408 E/mono-rt ( 5092): Stacktrace:
10-08 11:42:23.408 E/mono-rt ( 5092): 
10-08 11:42:23.408 E/mono-rt ( 5092): 
10-08 11:42:23.408 E/mono-rt ( 5092): Attempting native Android stacktrace:
10-08 11:42:23.408 E/mono-rt ( 5092): 

No breakpoints (Failure / Close) are hit.

Sample App
https://github.com/NVentimiglia/Realtime.Messaging.Xamarin

**Comment by NVentimiglia** [comment] 2015-10-08 18:47
10-08 11:46:30.793 D/Mono    (11800): GC_BRIDGE waiting for bridge processing to finish
10-08 11:46:30.857 I/art     (11800): Explicit concurrent mark sweep GC freed 171636(6MB) AllocSpace objects, 4(64KB) LOS objects, 52% free, 28MB/60MB, paused 920us total 62.270ms
10-08 11:46:30.862 D/Mono    (11800): GC_OLD_BRIDGE num-objects 56 num_hash_entries 57 sccs size 57 init 0.00ms df1 0.17ms sort 0.04ms dfs2 0.30ms setup-cb 0.32ms free-data 0.17ms links 1/1/1/1 dfs passes 114/58
10-08 11:46:30.862 D/Mono    (11800): GC_MINOR: (Nursery full) pause 26.92ms, total 29.97ms, bridge 69.15ms promoted 464K major 4848K los 168K
10-08 11:46:30.979 E/art     (11800): JNI ERROR (app bug): accessed deleted global reference 0xa00d76
10-08 11:46:30.981 E/mono-rt (11800): Stacktrace:
10-08 11:46:30.981 E/mono-rt (11800): 
10-08 11:46:30.981 E/mono-rt (11800):   at <unknown> <0xffffffff>
10-08 11:46:30.981 E/mono-rt (11800):   at (wrapper managed-to-native) object.wrapper_native_0xb45b3aed (intptr,intptr,intptr,intptr,Android.Runtime.JValue*) <IL 0x00030, 0xffffffff>
10-08 11:46:30.981 E/mono-rt (11800):   at (wrapper delegate-invoke) <Module>.invoke_void_intptr_intptr_intptr_intptr_JValue* (intptr,intptr,intptr,intptr,Android.Runtime.JValue*) <IL 0x00070, 0xffffffff>
10-08 11:46:30.981 E/mono-rt (11800):   at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (intptr,intptr,intptr,Android.Runtime.JValue*) [0x00060] in /Users/builder/data/lanes/2058/58099c53/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:1025
10-08 11:46:30.981 E/mono-rt (11800):   at Android.Runtime.JNIEnv.FinishCreateInstance (intptr,intptr,intptr,Android.Runtime.JValue*) [0x0000b] in /Users/builder/data/lanes/2058/58099c53/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.cs:306
10-08 11:46:30.981 E/mono-rt (11800):   at Android.OS.Handler..ctor (Android.OS.Looper) [0x000c5] in /Users/builder/data/lanes/2058/58099c53/source/monodroid/src/Mono.Android/platforms/android-22/src/generated/Android.OS.Handler.cs:195
10-08 11:46:30.981 E/mono-rt (11800):   at Android.App.SyncContext.Post (System.Threading.SendOrPostCallback,object) [0x00014] in /Users/builder/data/lanes/2058/58099c53/source/monodroid/src/Mono.Android/src/Android.App/SyncContext.cs:17
10-08 11:46:30.981 E/mono-rt (11800):   at RealtimeFramework.Messaging.OrtcClient.DelegateExceptionCallback (System.Exception) [0x0003d] in E:\Projects\Realtime\Realtime.Xamarin\Realtime.Messaging\OrtcClient.cs:671
10-08 11:46:30.981 E/mono-rt (11800):   at RealtimeFramework.Messaging.Client._webSocketConnection_OnError (System.Exception) [0x0002e] in E:\Projects\Realtime\Realtime.Xamarin\Realtime.Messaging\Client.cs:94
10-08 11:46:30.981 E/mono-rt (11800):   at (wrapper delegate-invoke) System.Action`1.invoke_void_T (T) <IL 0x0005e, 0xffffffff>
10-08 11:46:30.981 E/mono-rt (11800):   at Realtime.Messaging.Droid.WebsocketConnection/<>c__DisplayClass20_0.<Close>b__1 () [0x00000] in E:\Projects\Realtime\Realtime.Xamarin\Realtime.Messaging.Droid\WebsocketConnection.cs:145
10-08 11:46:30.982 E/mono-rt (11800):   at System.Threading.Tasks.Task.InnerInvoke () [0x00012] in /Users/builder/data/lanes/2058/58099c53/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2901
10-08 11:46:30.982 E/mono-rt (11800):   at System.Threading.Tasks.Task.Execute () [0x00016] in /Users/builder/data/lanes/2058/58099c53/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2523
10-08 11:46:30.982 E/mono-rt (11800):   at System.Threading.Tasks.Task.ExecutionContextCallback (object) [0x00007] in /Users/builder/data/lanes/2058/58099c53/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2887
10-08 11:46:30.982 E/mono-rt (11800):   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object) [0x00027] in /Users/builder/data/lanes/2058/58099c53/source/mono/mcs/class/corlib/System.Threading/ExecutionContext.cs:242
10-08 11:46:30.982 E/mono-rt (11800):   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) [0x00000] in /Users/builder/data/lanes/2058/58099c53/source/mono/mcs/class/corlib/System.Threading/ExecutionContext.cs:228
10-08 11:46:30.982 E/mono-rt (11800):   at System.Threading.Tasks.Task.ExecuteWithThreadLocal (System.Threading.Tasks.Task&) [0x0005f] in /Users/builder/data/lanes/2058/58099c53/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2848
10-08 11:46:30.982 E/mono-rt (11800):   at System.Threading.Tasks.Task.ExecuteEntry (bool) [0x0006f] in /Users/builder/data/lanes/2058/58099c53/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2781
10-08 11:46:30.982 E/mono-rt (11800):   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00000] in /Users/builder/data/lanes/2058/58099c53/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2728
10-08 11:46:30.982 E/mono-rt (11800):   at System.Threading.ThreadPool.<UnsafeQueueCustomWorkItem>m__0 (object) [0x00000] in /Users/builder/data/lanes/2058/58099c53/source/mono/mcs/class/corlib/System.Threading/ThreadPool.cs:258
10-08 11:46:30.982 E/mono-rt (11800):   at (wrapper runtime-invoke) <Module>.runtime_invoke_void__this___object (object,intptr,intptr,intptr) <IL 0x00062, 0xffffffff>
10-08 11:46:30.982 E/mono-rt (11800): 
10-08 11:46:30.982 E/mono-rt (11800): Attempting native Android stacktrace:
10-08 11:46:30.982 E/mono-rt (11800): 
10-08 11:46:31.002 E/mono-rt (11800):  at ???+0 [0x70a93f80]
10-08 11:46:31.042 E/mono-rt (11800):  at ???+0 [0xdead431f]
10-08 11:46:31.058 E/mono-rt (11800): 
10-08 11:46:31.058 E/mono-rt (11800): =================================================================
10-08 11:46:31.058 E/mono-rt (11800): Got a SIGSEGV while executing native code. This usually indicates
10-08 11:46:31.058 E/mono-rt (11800): a fatal error in the mono runtime or one of the native libraries 
10-08 11:46:31.058 E/mono-rt (11800): used by your application.
10-08 11:46:31.058 E/mono-rt (11800): =================================================================
10-08 11:46:31.058 E/mono-rt (11800): 
10-08 11:46:31.058 F/libc    (11800): Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdead4321 in tid 11959 (Thread-124861)

**Comment by NVentimiglia** [comment] 2015-10-08 18:55
Actually, not sure. Here is my handler.

`````
private void _listener_Failure(object sender, FailureEventArgs e)
        {
            Device.BeginInvokeOnMainThread(() =>
            {
                var ev = OnError;
                if (ev != null)
                {
                    if (e.Exception != null)
                        ev(e.Exception);
                    else
                        ev(new Exception("Unknown WebSocket Error!"));
                }
            });

            Device.BeginInvokeOnMainThread(() =>
            {
                var ev2 = OnClosed;
                if (ev2 != null)
                {
                    ev2();
                }
            });
        }
`````

Not sure why this would cause my code to die. Feel like it might be something internal.

**Comment by NVentimiglia** [comment] 2015-10-08 19:01
0-08 12:01:00.838 E/art     ( 3095): JNI ERROR (app bug): accessed deleted global reference 0x500d8a
10-08 12:01:00.846 E/mono-rt ( 3095): Stacktrace:
10-08 12:01:00.846 E/mono-rt ( 3095): 
10-08 12:01:00.846 E/mono-rt ( 3095):   at <unknown> <0xffffffff>
10-08 12:01:00.846 E/mono-rt ( 3095):   at (wrapper managed-to-native) object.wrapper_native_0xb45b3aed (intptr,intptr,intptr,intptr,Android.Runtime.JValue*) <IL 0x00030, 0xffffffff>
10-08 12:01:00.846 E/mono-rt ( 3095):   at (wrapper delegate-invoke) <Module>.invoke_void_intptr_intptr_intptr_intptr_JValue* (intptr,intptr,intptr,intptr,Android.Runtime.JValue*) <IL 0x00070, 0xffffffff>
10-08 12:01:00.847 E/mono-rt ( 3095):   at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (intptr,intptr,intptr,Android.Runtime.JValue*) [0x00060] in /Users/builder/data/lanes/2058/58099c53/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:1025
10-08 12:01:00.847 E/mono-rt ( 3095):   at Android.Runtime.JNIEnv.FinishCreateInstance (intptr,intptr,intptr,Android.Runtime.JValue*) [0x0000b] in /Users/builder/data/lanes/2058/58099c53/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.cs:306
10-08 12:01:00.847 E/mono-rt ( 3095):   at Android.OS.Handler..ctor (Android.OS.Looper) [0x000c5] in /Users/builder/data/lanes/2058/58099c53/source/monodroid/src/Mono.Android/platforms/android-22/src/generated/Android.OS.Handler.cs:195
10-08 12:01:00.847 E/mono-rt ( 3095):   at Android.App.SyncContext.Post (System.Threading.SendOrPostCallback,object) [0x00014] in /Users/builder/data/lanes/2058/58099c53/source/monodroid/src/Mono.Android/src/Android.App/SyncContext.cs:17
10-08 12:01:00.847 E/mono-rt ( 3095):   at RealtimeFramework.Messaging.OrtcClient.DelegateExceptionCallback (System.Exception) [0x0003d] in E:\Projects\Realtime\Realtime.Xamarin\Realtime.Messaging\OrtcClient.cs:671
10-08 12:01:00.847 E/mono-rt ( 3095):   at RealtimeFramework.Messaging.Client._webSocketConnection_OnError (System.Exception) [0x0002e] in E:\Projects\Realtime\Realtime.Xamarin\Realtime.Messaging\Client.cs:94
10-08 12:01:00.847 E/mono-rt ( 3095):   at (wrapper delegate-invoke) System.Action`1.invoke_void_T (T) <IL 0x0005e, 0xffffffff>
10-08 12:01:00.847 E/mono-rt ( 3095):   at Realtime.Messaging.Droid.WebsocketConnection/<>c__DisplayClass20_0.<Close>b__1 () [0x00000] in E:\Projects\Realtime\Realtime.Xamarin\Realtime.Messaging.Droid\WebsocketConnection.cs:146
10-08 12:01:00.847 E/mono-rt ( 3095):   at System.Threading.Tasks.Task.InnerInvoke () [0x00012] in /Users/builder/data/lanes/2058/58099c53/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2901
10-08 12:01:00.848 E/mono-rt ( 3095):   at System.Threading.Tasks.Task.Execute () [0x00016] in /Users/builder/data/lanes/2058/58099c53/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2523
10-08 12:01:00.848 E/mono-rt ( 3095):   at System.Threading.Tasks.Task.ExecutionContextCallback (object) [0x00007] in /Users/builder/data/lanes/2058/58099c53/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2887
10-08 12:01:00.848 E/mono-rt ( 3095):   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object) [0x00027] in /Users/builder/data/lanes/2058/58099c53/source/mono/mcs/class/corlib/System.Threading/ExecutionContext.cs:242
10-08 12:01:00.848 E/mono-rt ( 3095):   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) [0x00000] in /Users/builder/data/lanes/2058/58099c53/source/mono/mcs/class/corlib/System.Threading/ExecutionContext.cs:228
10-08 12:01:00.848 E/mono-rt ( 3095):   at System.Threading.Tasks.Task.ExecuteWithThreadLocal (System.Threading.Tasks.Task&) [0x0005f] in /Users/builder/data/lanes/2058/58099c53/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2848
10-08 12:01:00.848 E/mono-rt ( 3095):   at System.Threading.Tasks.Task.ExecuteEntry (bool) [0x0006f] in /Users/builder/data/lanes/2058/58099c53/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2781
10-08 12:01:00.848 E/mono-rt ( 3095):   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00000] in /Users/builder/data/lanes/2058/58099c53/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2728
10-08 12:01:00.848 E/mono-rt ( 3095):   at System.Threading.ThreadPool.<UnsafeQueueCustomWorkItem>m__0 (object) [0x00000] in /Users/builder/data/lanes/2058/58099c53/source/mono/mcs/class/corlib/System.Threading/ThreadPool.cs:258
10-08 12:01:00.848 E/mono-rt ( 3095):   at (wrapper runtime-invoke) <Module>.runtime_invoke_void__this___object (object,intptr,intptr,intptr) <IL 0x00062, 0xffffffff>
10-08 12:01:00.848 E/mono-rt ( 3095): 
10-08 12:01:00.848 E/mono-rt ( 3095): Attempting native Android stacktrace:
10-08 12:01:00.848 E/mono-rt ( 3095): 
10-08 12:01:00.860 I/Choreographer( 3095): Skipped 163 frames!  The application may be doing too much work on its main thread.
10-08 12:01:00.878 E/mono-rt ( 3095):  at ???+0 [0x70a93f80]
10-08 12:01:00.951 E/mono-rt ( 3095):  at ???+0 [0xdead431f]
10-08 12:01:00.982 E/mono-rt ( 3095): 
10-08 12:01:00.982 E/mono-rt ( 3095): =================================================================
10-08 12:01:00.982 E/mono-rt ( 3095): Got a SIGSEGV while executing native code. This usually indicates
10-08 12:01:00.982 E/mono-rt ( 3095): a fatal error in the mono runtime or one of the native libraries 
10-08 12:01:00.982 E/mono-rt ( 3095): used by your application.
10-08 12:01:00.982 E/mono-rt ( 3095): =================================================================
10-08 12:01:00.982 E/mono-rt ( 3095): 
10-08 12:01:00.982 F/libc    ( 3095): Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdead4321 in tid 3163 (Thread-127670)

**Comment by NVentimiglia** [comment] 2015-10-08 19:03
10-08 12:02:48.155 I/Choreographer( 5816): Skipped 170 frames!  The application may be doing too much work on its main thread.
10-08 12:02:48.425 D/BubblePopupHelper( 5816): isShowingBubblePopup : false
10-08 12:02:48.425 D/BubblePopupHelper( 5816): isShowingBubblePopup : false
10-08 12:02:48.519 D/Mono    ( 5816): GC_BRIDGE waiting for bridge processing to finish
10-08 12:02:48.566 I/art     ( 5816): Explicit concurrent mark sweep GC freed 6804(434KB) AllocSpace objects, 0(0B) LOS objects, 52% free, 28MB/60MB, paused 1.617ms total 19.617ms
10-08 12:02:48.567 D/Mono    ( 5816): GC_OLD_BRIDGE num-objects 50 num_hash_entries 8486 sccs size 4757 init 0.00ms df1 21.09ms sort 2.27ms dfs2 10.53ms setup-cb 0.36ms free-data 14.38ms links 17098/17098/79971/17 dfs passes 25634/21855
10-08 12:02:48.567 D/Mono    ( 5816): GC_MINOR: (Nursery full) pause 32.20ms, total 33.50ms, bridge 48.15ms promoted 1168K major 2784K los 118K
10-08 12:02:48.678 E/art     ( 5816): JNI ERROR (app bug): accessed deleted global reference 0x1b00c8a
10-08 12:02:48.678 E/mono-rt ( 5816): Stacktrace:
10-08 12:02:48.678 E/mono-rt ( 5816): 
10-08 12:02:48.678 E/mono-rt ( 5816): 
10-08 12:02:48.678 E/mono-rt ( 5816): Attempting native Android stacktrace:
10-08 12:02:48.678 E/mono-rt ( 5816): 
10-08 12:02:48.694 E/mono-rt ( 5816):  at ???+6488184 [0x70a93f80]
10-08 12:02:48.717 E/mono-rt ( 5816):  at ???+6488184 [0xdead431f]
10-08 12:02:48.739 E/mono-rt ( 5816): 
10-08 12:02:48.739 E/mono-rt ( 5816): =================================================================
10-08 12:02:48.739 E/mono-rt ( 5816): Got a SIGSEGV while executing native code. This usually indicates
10-08 12:02:48.739 E/mono-rt ( 5816): a fatal error in the mono runtime or one of the native libraries 
10-08 12:02:48.739 E/mono-rt ( 5816): used by your application.
10-08 12:02:48.739 E/mono-rt ( 5816): =================================================================
10-08 12:02:48.739 E/mono-rt ( 5816): 
10-08 12:02:48.739 F/libc    ( 5816): Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdead4321 in tid 5944 (Thread-127999)

**Comment by swankjesse** [comment] 2015-10-31 00:19
Looks like a mono issue to me. If you can make an executable test case to reproduce this, we can fix it. In the interim I'm closing as there's no action for us to take on it.

**Closed by swankjesse** 2015-10-31 00:19 UTC

**Comment by NVentimiglia** [comment] 2015-10-31 16:00
Ok, just to clarify, If I made another sample application that was simpler would you help resolve the issue with the Xamarin plugin ? 

Also, I should mention I have run into this issue in the past when writing Xamarin plugins. My solution last time involved using the looper when communicating to the plugin and handling communication from the plugin. That is to say my solution was in JAVA.

**Comment by swankjesse** [comment] 2015-10-31 16:25
Since this project doesn't know anything about Xamarin or Mono, it's impossible for us to fix integration issues here. But if you can provide a test case that doesn't need Mono to reproduce, we'll fix!
