### ISSUE TITLE
Cannot specify WebSocket extensions

### ISSUE THREAD

**Issue by sbordet** [square/okhttp#5953] opened 2020-04-15 08:53 UTC
The change introduced [here](https://github.com/square/okhttp/pull/5871/files#diff-c29311352dbbaed82a3cead7a609f0b1R147) breaks the possibility for client applications to specify WebSocket extensions.

A client application may need to specify a WebSocket extension in the same way it may need to specify a WebSocket protocol, for example:

`Sec-WebSocket-Extensions: identity, fragment, custom`

If OkHttp wants to add the `permessage-deflate` extension, it should merge it with the extensions provided by the client application.

**Comment by swankjesse** [comment] 2020-04-15 11:27
I don’t think our API lenda itself to user-provided extensions. Negotiating which order to apply extensions in is awkward. Similarly it’s awkward to expose the message flags for read and write.

That said, I would like to know about the other extensions so I can understand the use case. Got a link to the CometD test?

**Comment by swankjesse** [comment] 2020-04-15 11:32
https://github.com/cometd/cometd/blob/master/cometd-java/cometd-java-websocket/cometd-java-websocket-jetty-server/src/test/java/org/cometd/websocket/ExtensionNegotiationTest.java

**Comment by swankjesse** [comment] 2020-04-15 11:32
https://github.com/cometd/cometd/blob/f3cf4d9ffe352082a57b038aa72a664ed6cdab58/cometd-java/cometd-java-websocket/cometd-java-websocket-jetty-server/src/test/java/org/cometd/websocket/ExtensionNegotiationTest.java

**Comment by swankjesse** [comment] 2020-04-15 11:47
I don't think there are enough useful web socket extensions to justify the complexity of a user-provided extensions mechanism.
https://www.iana.org/assignments/websocket/websocket.xhtml#extension-name

**Comment by swankjesse** [comment] 2020-04-15 11:58
I'm going to close this as working as intended. We don't support user-supplied extensions because the additional complexity of doing so correctly is very high, and the benefit is very low. This is similar to the policy in browser-based websocket APIs.

**Closed by swankjesse** 2020-04-15 11:58 UTC
Labels: bug, websockets

**Comment by sbordet** [comment] 2020-04-15 12:40
@swankjesse thanks, I believe that is fair enough. 

IIRC CometD had a case where the WebSocket communication was using a custom extension known to both server and client - they won't be able to use the OkHttp transport but they have other transports.

**Comment by swankjesse** [comment] 2020-04-16 04:31
What did the extension do? I assume most interesting things you'd do are more portable and work better in the payload than in extensions.
