### ISSUE TITLE
IllegalStateException: stream != null

### ISSUE THREAD

**Issue by hamberluo** [square/okhttp#2409] opened 2016-03-15 09:17 UTC
```
Fatal Exception: java.lang.IllegalStateException: stream != null
       at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:155)
       at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
       at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
       at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
       at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
       at okhttp3.RealCall.getResponse(RealCall.java:240)
       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
       at okhttp3.RealCall.access$100(RealCall.java:30)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

**Comment by dave-r12** [comment] 2016-03-21 00:50
I was researching this one, but haven't found anything yet. @hamberluo do you know if you're using Http1 or Http2 when this exception happened?

**Comment by dave-r12** [comment] 2016-03-26 12:57
I've not been able to reproduce this one. I believe the cause would be related to a response not being closed prior to making a follow up request. The only thing I came up with is to create a 'misbehaving' network interceptor that wrapped the response, but didn't close it properly.

**Comment by swankjesse** [comment] 2016-03-26 13:24
Thanks for investigating this Dave. I also tried to isolate this, but my investigation wasn’t very deep! I ended up with this, which discovered that cache bug I fixed last week.
https://gist.github.com/swankjesse/ae7315037362e284edc7

**Comment by swankjesse** [comment] 2016-03-26 13:25
(I’d like to eventually tidy that up and check it in. If you want to take it over, please do!)

**Comment by dave-r12** [comment] 2016-03-26 13:45
Oh interesting, I'll have a look.

**Comment by hamberluo** [comment] 2016-04-06 02:27
@dave-r12 i'm using Http1

**Comment by dave-r12** [comment] 2016-04-06 12:24
Cool thanks. As a follow up, are you doing anything fancy like wrapping the Response with a network interceptor?

**Comment by hamberluo** [comment] 2016-04-06 12:36
@dave-r12 yes, but i'm not sure it's the real cause. i remove those codes in next app version to verify my thoughts.

**Comment by tguerin** [comment] 2016-04-15 09:02
Hi guys, 

We have this issue in our application. I've added some logs to find out the root cause and found a way to reproduce the problem. It seems the issue comes from multiple redirect on same host. In that case the StreamAllocation doesn't release the stream and will throw IllegalStateException on the next redirect call.

**Comment by swankjesse** [comment] 2016-04-15 11:40
@tguerin good find. I'll take a look. I assume you're using the latest release?

**Comment by tguerin** [comment] 2016-04-15 12:22
@swankjesse yes

**Comment by swankjesse** [comment] 2016-05-13 00:15
I figured out a way to reproduce this. We want to release the stream by doing this:

```
      closeQuietly(userResponse.body());
```

But if a network interceptor is involved, it’s possible that closing that doesn’t accomplish what we want. For example, consider this:

```
    OkHttpClient client = new OkHttpClient.Builder().addNetworkInterceptor(new Interceptor() {
      @Override public Response intercept(Chain chain) throws IOException {
        Response response = chain.proceed(chain.request());
        return response.newBuilder()
            .body(ResponseBody.create(null, "HELLO"))
            .build();
      }
    }).build();
```

@tguerin, @hamberluo are you using any network interceptors?

**Comment by hamberluo** [comment] 2016-05-13 13:56
@swankjesse i use the stetho in debug build instead of release, yet it also crash in release.

**Closed** 2016-05-13 22:14 UTC
Labels: bug

**Comment by tguerin** [comment] 2016-05-19 09:12
@swankjesse The only network interceptor we have was used to workaround this issue

**Comment by hamberluo** [comment] 2016-05-21 00:14
@swankjesse i also use okhttp ws lib.

**Comment by dave-r12** [comment] 2016-05-27 12:47
@tguerin are you using web sockets?

**Comment by tguerin** [comment] 2016-06-13 14:22
@dave-r12 Yes, why ?
