### ISSUE TITLE
setHeaders() has surprising, bad side effects for MockResponse

### ISSUE THREAD

**Issue by MoshDev** [square/okhttp#2512] opened 2016-04-25 22:02 UTC
Using MockWebServer to test api requests.

`mockServer.enqueue(new MockResponse().setBody("Anything").setResponseCode(HttpURLConnection.HTTP_OK));`
returns successfully the response

`mockServer.enqueue(new MockResponse().setBody("Anything").setResponseCode(HttpURLConnection.HTTP_BAD_REQUEST));`
throws read time out exception

**Comment by swankjesse** [comment] 2016-04-26 03:54
Could you provide a complete failing JUnit test that would pass if we fix the bug?

**Comment by MoshDev** [comment] 2016-04-26 13:59
`  @Test
  public void sampleTest() throws IOException, InterruptedException {

    String responseText = "Hello Text";

    MockResponse mockResponse = new MockResponse().setResponseCode(HTTP_OK).setBody(responseText).setHeaders(responseHeaders);
    mockServer.enqueue(mockResponse);

    String result = sampleApiRequest();

    assertEquals(result, "Hello Text");

  }

  public String sampleApiRequest() throws IOException {
    Response<ResponseBody> stringResponse = service.sample().execute();
    if (stringResponse.isSuccessful()) {
      return stringResponse.body().string();
    }
    return stringResponse.errorBody().string();
  }`

**Comment by MoshDev** [comment] 2016-04-26 14:00
seems I found the bug,

**Comment by swankjesse** [comment] 2016-04-26 15:11
Does `responseHeaders` include a `Content-length` ? If it does, it must match the body’s content length.

**Comment by MoshDev** [comment] 2016-04-26 22:13
`responseHeaders = new Headers.Builder().add("Content-type", "application/json; charset=UTF-8").build();`

**Comment by swankjesse** [comment] 2016-04-27 00:53
Ahh, got it. The problem is that `setHeaders()` actually clears the existing headers, which wipes out anything necessary to specify body’s content-encoding or length.

**Comment by swankjesse** [comment] 2016-05-08 00:08
I’m unsure what action we should take here.

**Comment by mrhota** [comment] 2017-08-21 16:02
@swankjesse could it have anything to do with the fact that `setResponseCode` assumes everything will be `200 OK`?

```
public MockResponse setResponseCode(int code) {
    return this.setStatus("HTTP/1.1 " + code + " OK");
}
```

I can't set a MockResponse's ResponseCode to 500, for example. I have to write this explicitly
```
new MockResponse().setBody("").setStatus("HTTP/1.1 500 Internal Server Error");
```
or else MockWebServer just hangs and never returns the MockResponse.

**Comment by JakeWharton** [comment] 2017-08-21 16:16
The status line message is optional and its value should not be relied upon, so serving "OK" for every code was fine. This was changed a long while ago, though, to at least vary the message based on the hundreds place value of the code.

**Comment by yschimke** [comment] 2020-03-29 18:49
Closing - MockWebserver probably deserves it's own mini project.  even supporting different junit versions is awkward when bundled in OkHttp release cycle.

**Closed by yschimke** 2020-03-29 18:49 UTC
Labels: bug
