### ISSUE TITLE
A great many Thread BLOCKED at okhttp3.internal.connection.Transmitter.isCanceled

### ISSUE THREAD

**Issue by guozongkang** [square/okhttp#7726] opened 2023-03-01 13:59 UTC
"http-nio-7001-exec-497" #48491 daemon prio=5 os_prio=0 tid=0x00007f70911bc800 nid=0x1f3f9 waiting for monitor entry [0x00007f6c3f32e000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at okhttp3.internal.connection.Transmitter.isCanceled(Transmitter.java:349)
	- waiting to lock <0x00007f71c1006430> (a okhttp3.internal.connection.RealConnectionPool)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:81)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain$original$GYp10GsZ(RealCall.java:221)
	at okhttp3.RealCall.getResponseWithInterceptorChain$original$GYp10GsZ$accessor$4HJRK30K(RealCall.java)
	at okhttp3.RealCall$auxiliary$YsKsh89S.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java)
	at okhttp3.RealCall.execute$original$GYp10GsZ(RealCall.java:81)
	at okhttp3.RealCall.execute$original$GYp10GsZ$accessor$4HJRK30K(RealCall.java)
	at okhttp3.RealCall$auxiliary$Oe01Vdvf.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at okhttp3.RealCall.execute(RealCall.java)
	at feign.okhttp.OkHttpClient.execute(OkHttpClient.java:172)
	at org.springframework.cloud.openfeign.ribbon.RetryableFeignLoadBalancer$1.doWithRetry(RetryableFeignLoadBalancer.java:114)
	at org.springframework.cloud.openfeign.ribbon.RetryableFeignLoadBalancer$1.doWithRetry(RetryableFeignLoadBalancer.java:94)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:225)
	at org.springframework.cloud.openfeign.ribbon.RetryableFeignLoadBalancer.execute(RetryableFeignLoadBalancer.java:94)
	at org.springframework.cloud.openfeign.ribbon.RetryableFeignLoadBalancer.execute(RetryableFeignLoadBalancer.java:54)
	at com.netflix.client.AbstractLoadBalancerAwareClient$1.call(AbstractLoadBalancerAwareClient.java:104)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:303)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:287)
	at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:231)
	at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:228)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)

**Comment by guozongkang** [comment] 2023-03-01 13:59
version 3.14.1

**Comment by yschimke** [comment] 2023-03-04 12:14
Dupe of https://github.com/square/okhttp/issues/7687

**Comment by guozongkang** [comment] 2023-03-04 17:02
It's not the same question https://github.com/square/okhttp/issues/7687

**Comment by guozongkang** [comment] 2023-03-04 17:05
Transmitter.isCanceled   synchronized in the connectionPool

**Comment by guozongkang** [comment] 2023-03-04 17:05
synchronized blocks a large number of threads

**Comment by guozongkang** [comment] 2023-03-04 17:05
![image](https://user-images.githubusercontent.com/36061267/222919188-208ff23e-2251-41ff-b529-f90566a6e11c.png)

**Comment by yschimke** [comment] 2023-03-04 17:42
Version 3.14.1, is not supported.  Can you reproduce on 4.10.0 and provide a reproduction?

**Closed** 2023-05-20 16:28 UTC
Labels: bug, needs info
