### ISSUE TITLE
HTTPS - Breaking client authentication on server side

### ISSUE THREAD

**Issue by aponhcet** [square/okhttp#5090] opened 2019-05-22 11:27 UTC
Hi Guys,

When you don't specify a sslSocketFactory okhttp recreate a TLS SSLcontext instead of using SSLContext.getDefault. Doing so you init the SSLContext without giving the default keyStore and this break server side client certificate authentication.

In a system where you configure your trustCertificate and keyStore using system properties like
"javax.net.ssl.keyStore" & "javax.net.ssl.trustStore" , java merge them and init the SSLContext.getDefault for you. Basically you just need to get the socketFactory from that default context.

To make sure the sslsocket factory contain my client certificate from the keystore I have to call 
`OkHttpClient.builder.slSocketFactory(**SSLContext.getDefault().getSocketFactory**, trustManager) `

Let me know if you guys need something or if i got it wrong 
I will try to follow with a pull request.

Best,

**Comment by swankjesse** [comment] 2019-05-22 11:36
Executable test case? I think this is working as intended.

**Comment by aponhcet** [comment] 2019-05-23 07:08
Well i didn't buld a test case yet, the issue occur when I connect to an nginx server with client authentication enable. http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_verify_client

When you init the custom build ssl context you give null in the keystore parameter. This cause the client to not provide client certificate and the verification fail on server side. 

When using the SSLContext default this doesnt occur as the keystore is set using :
```
 System.setProperty("javax.net.ssl.keyStore","clientKeyStore.key");
   System.setProperty("javax.net.ssl.keyStorePassword","qwerty")
```
https://docs.oracle.com/javadb/10.8.3.0/adminguide/cadminsslclient.html

**Comment by swankjesse** [comment] 2019-05-23 12:19
If you're doing custom authentication, you should configure your OkHttpClient’s SSL programmatically.

**Comment by aponhcet** [comment] 2019-05-27 08:38
Well it is authentication at SSL level. Just giving to okhttp SSLContextProvider.getSSLContext().getSocketFactory() fixed it. 
Or giving the the keystore when you init the SSLcontext in okhttpclient.builder instead of passing null.

Maybe you the flexible solution would be to extend the api to be able to pass a keystore to the SSLContext instead of only the TrustStore.

**Comment by yschimke** [comment] 2019-05-27 09:01
@aponhcet IMHO OkHttp is a fairly opinionated user agent (not a toolkit).  So in the timeframe of 4.1, if we can identify common patterns for large subsets of users e.g. setting up good security for Android mobile developers then it's probably worth adding new Public APIs.

I think the HeldCertificate shows there is already progress towards this direction, of OkHttp users having a simple API for managing certificates.

If niche things are possible, but a bit clunky then it's less likely that we would add new APIs.

**Comment by yschimke** [comment] 2020-03-29 18:05
Won't fix.

**Closed by yschimke** 2020-03-29 18:05 UTC
Labels: bug

**Comment by apple-corps** [comment] 2022-02-03 19:15
@aponhcet I'm running into the same issue. I'm trying to set truststore and keystore by Java system properties. Rather just specifying the properties via a command line argument. I see by default the truststore gets loaded. But I think the keystore is not loaded.

Following your line `OkHttpClient.builder.slSocketFactory(**SSLContext.getDefault().getSocketFactory**, trustManager)` but how are you providing the trustManager that are given to the system properties? 

For example if I am starting my application like

```
java -Djavax.net.ssl.trustStore=truststore.pfx -Djavax.net.ssl.trustStorePassword=changeit -Djavax.net.ssl.keyStoreType=pkcs12 -Djavax.net.ssl.keyStore=client.pfx -Djavax.net.ssl.keyStorePassword=changeit -Djavax.net.debug=SSL,trustmanager ....
```

It appears the truststore is loaded, but the keyStore containing client certificate / private key is not. Then how are you providing the value for trustManager ?

**Comment by apple-corps** [comment] 2022-02-03 19:28
@yschimke it seems like it would be easier to use if we could just specify keyStore via system properties and it just worked instead of writing boilerplate.

**Comment by yschimke** [comment] 2022-02-03 20:00
I think to get the TrustManager it would just be

```
  val tmf = TrustManagerFactory.getInstance(
    TrustManagerFactory.getDefaultAlgorithm()
  ).apply {
    init(null as KeyStore?)
  }

  val tm = tmf.trustManagers[0] as X509TrustManager
  val context = SSLContext.getDefault()

  val client = OkHttpClient.Builder()
    .sslSocketFactory(context.socketFactory, tm)
    .build()
```

I appreciate it would be simpler for your setup if we made this the default, but it's by design and there are undoubtable at least some people relying on the current behaviour. The workaround is fairly simple boilerplate, you hopefully only have to write once.

Going back to @swankjesse comment

> If you're doing custom authentication, you should configure your OkHttpClient’s SSL programmatically.

I think this describes the OkHttp approach.  The default works predictably, but we allow people with specific requirements to easily customise OkHttp.  Once you know you need a specific setup, you should write specifically the code you need. The boilerplate, let's you outsource your certificate management to system properties, it's deliberate intentional code, so for us it's not boilerplate.

**Comment by apple-corps** [comment] 2022-02-03 22:01
@yschimke 

I'm trying to write your Kotlin to JAVA. I wrote

```
    TrustManagerFactory tmf = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
    X509TrustManager tM = (X509TrustManager)tmf.getTrustManagers()[0];
        OkHttpClient client = new OkHttpClient().newBuilder().sslSocketFactory(SSLContext.getDefault().getSocketFactory(),tM).build();
```

Note that I'm having trouble calling init(null) on the TMF. 

```

**Comment by yschimke** [comment] 2022-02-03 22:04
Try

tmf.init((KeyStore) null);

If your stuck, I can take a look tomorrow. I haven't tested this (I don't have local key stores etc), but its my best understanding of how it should be setup.

**Comment by apple-corps** [comment] 2022-02-03 22:12
```
    TrustManagerFactory tmf = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
    X509TrustManager tM = (X509TrustManager)tmf.getTrustManagers()[0];
    tmf.init((KeyStore) null);
    OkHttpClient client = new OkHttpClient().newBuilder().sslSocketFactory(SSLContext.getDefault().getSocketFactory(),tM).build();
```

and invoking the client and running the java gives the same

```
Exception in thread "main" java.lang.IllegalStateException: TrustManagerFactoryImpl is not initialized
        at java.base/sun.security.ssl.TrustManagerFactoryImpl.engineGetTrustManagers(TrustManagerFactoryImpl.java:102)
        at java.base/javax.net.ssl.TrustManagerFactory.getTrustManagers(TrustManagerFactory.java:313)
        at com.example.app.App.main(App.java:23)
```

But again I think if we are initializing the tmf with a null keystore, I don't see how we can use `-Djavax.net.ssl.keyStore=client.pfx` .

**Comment by apple-corps** [comment] 2022-02-03 22:27
I'm assuming that I have the certificates right as they are set up like https://stackoverflow.com/a/53709621

However not sure how I can see that the keystore is loaded properly. Here's the results after initializing with the null keystore, as suggested.


```
javax.net.ssl|ERROR|01|main|2022-02-03 14:16:23.850 PST|TransportContext.java:341|Fatal (CERTIFICATE_UNKNOWN): PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target (
"throwable" : {
  sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
        at java.base/sun.security.validator.Validator.validate(Validator.java:264)
        at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1418)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1324)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at com.example.app.App.main(App.java:48)
  Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
        ... 35 more}

)

javax.net.ssl|DEBUG|01|main|2022-02-03 14:16:23.850 PST|SSLSocketImpl.java:1638|close the underlying socket
javax.net.ssl|DEBUG|01|main|2022-02-03 14:16:23.850 PST|SSLSocketImpl.java:1657|close the SSL connection (initiative)
Exception in thread "main" javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:349)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:287)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1418)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1324)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at com.example.app.App.main(App.java:48)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
        at java.base/sun.security.validator.Validator.validate(Validator.java:264)
        at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
        ... 29 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
        ... 35 more
```

**Comment by HammaFist70** [comment] 2022-02-04 04:26
I would Truly appreciate it ,& I've been more than Accommodating! Thank
You.. Hopefully, Sincerely looking FWD to it..👍

**Comment by yschimke** [comment] 2022-02-04 07:56
For context OkHttp needs the TrustManager directly, including for Certificate Chain cleaning and possibly other reasons. So there is a good reason we deprecated the single param sslSocketFactory method.  In JDK 9 it broke because of Java modules. 

```
    // Not supported due to access checks on JDK 9+:
    // java.lang.reflect.InaccessibleObjectException: Unable to make member of class
    // sun.security.ssl.SSLSocketFactoryImpl accessible:  module java.base does not export
    // sun.security.ssl to unnamed module @xxx
```

It seems to work for me with a local trust store.

```
  System.setProperty("javax.net.ssl.trustStore", "./server")
  System.setProperty("javax.net.ssl.trustStoreType", "PKCS12")
  System.setProperty("javax.net.ssl.trustStorePassword", "123456")

  println(tmf.provider) // SunJSSE version 11
  println(tm.acceptedIssuers.size) // 1
```

Looking at the implementation details for sun.security.ssl.SSLContextImpl (JDK 11) it looks like the default SunJSSE, which should have defaults automatically. The other code path assumes they don't so loads from the system properties.

```
        private static TrustManager[] getTrustManagers() throws Exception {
            TrustManagerFactory tmf = TrustManagerFactory.getInstance(
                    TrustManagerFactory.getDefaultAlgorithm());
            if ("SunJSSE".equals(tmf.getProvider().getName())) {
                // The implementation will load the default KeyStore
                // automatically.  Cached trust materials may be used
                // for performance improvement.
                tmf.init((KeyStore)null);
            } else {
                // Use the explicitly specified KeyStore for third party's
                // TrustManagerFactory implementation.
                KeyStore ks = TrustStoreManager.getTrustedKeyStore();
                tmf.init(ks);
            }

            return tmf.getTrustManagers();
        }
```        

Can you try with

```
  tmf = TrustManagerFactory.getInstance(
    TrustManagerFactory.getDefaultAlgorithm(),
    "SunJSSE"
  );
    tmf.init((KeyStore)null);
```

This will presumably only fix things if your security providers ordering is different?

If this doesn't work, then I think you are probably back to manually loading the Keystore using the system properties.

But sanity check the trust manager you are getting first, before trying connections.

We can put up a sample for using the defaults on JVM, but I'm not able to help with the certificate failures with custom trust store set up. It's way easier with a public website.

**Comment by apple-corps** [comment] 2022-02-06 22:35
For the code:
```
    TrustManagerFactory tmf = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm(), "SunJSSE");
    tmf.init((KeyStore) null);
    X509TrustManager tM = (X509TrustManager)tmf.getTrustManagers()[0];
    OkHttpClient client = new OkHttpClient().newBuilder().sslSocketFactory(SSLContext.getDefault().getSocketFactory(),tM).build();
```    
and java parameters:

```
-Djavax.net.ssl.trustStore=truststore.pfx -Djavax.net.ssl.trustStorePassword=changeit -Djavax.net.ssl.keyStoreType=pkcs12 -Djavax.net.ssl.keyStore=client.pfx -Djavax.net.ssl.keyStorePassword=changeit
```

Executing a client request results in

```
javax.net.ssl|ALL|01|main|2022-02-06 22:08:43.930 UTC|X509Authentication.java:246|No X.509 cert selected for EC
javax.net.ssl|ALL|01|main|2022-02-06 22:08:43.931 UTC|X509Authentication.java:246|No X.509 cert selected for EC
javax.net.ssl|ALL|01|main|2022-02-06 22:08:43.931 UTC|X509Authentication.java:246|No X.509 cert selected for EC

                {
                "error": {
                    "code": "SG401",
                    "message": "Authentication was either not provided or not successful"
                    }
                }
```

Then I think we are seeing the keystore not attached. We have the same result if we remove the "SunJSSE" and run.

____________________________________________________________________________________________________

I tried also adding the keystore manually instead of null. I'm still getting the same error. Supposedly the certificates are working in a nifi program.

```
    String keyPassphrase = "changeit";
    KeyStore keyStore = KeyStore.getInstance("PKCS12");
    keyStore.load(new FileInputStream("client.pfx"), keyPassphrase.toCharArray());
    
    
    TrustManagerFactory tmf = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
    tmf.init(keyStore);
    X509TrustManager tM = (X509TrustManager)tmf.getTrustManagers()[0];
    OkHttpClient client = new OkHttpClient().newBuilder().sslSocketFactory(SSLContext.getDefault().getSocketFactory(),tM).build();
 ```

**Comment by yschimke** [comment] 2022-02-07 09:28
I don't think we can help with this bit, you'll need to get it working locally with your certificates, probably programmatically.  At point it's like you have the cleanest fix we can provide.

For example wrap the trust manager with https://github.com/cashapp/certifikit/blob/373224a571b9328f340dfa225a127f90dda5ab72/certifikit-cli/src/jvmMain/kotlin/app/cash/certifikit/cli/okhttp/CapturingTrustManager.kt and observe the certificates that are provided by the server.  Make sure the chain has a path to something in TrustManager.getAcceptedIssuers

**Comment by apple-corps** [comment] 2022-02-07 14:51
@yschimke can you provide a programatic example given a truststore: truststore.pfx and keystore: keystore.pfx files that should work given valid files? I can go ahead and check if things work the expected way.

If that does work, then I could try to import CapturingTrustManager and look at the certificate Array from getAcceptedIssuers. But I'd either have to build that locally or would it be available from a snapshot repo?

**Comment by apple-corps** [comment] 2022-02-07 19:12
It looks like there's a server example here. I can try to use it as a reference and determine if I have any issues. 
https://github.com/square/okhttp/blob/f934da0e82233c6c64ce9b9ea7f470561ac9c8c0/samples/static-server/src/main/java/okhttp3/sample/SampleServer.java#L118

**Comment by yschimke** [comment] 2022-02-08 08:17
Let me know how you go, if you are still stuck I can take a look at the weekend.

I will try to make a clean sample of the CapturingTrustManager and make it smart enough to log the issue, as I think it might simplify a lot of these types of investigations.
