### ISSUE TITLE
Avoiding deadlocks within okhttp interceptors/authenticator when using retrofit with coroutines adapter 

### ISSUE THREAD

**Issue by ursusursus** [square/okhttp#6754] opened 2021-07-17 18:34 UTC
Hi,
I used retrofit+okhttp+rxjava, now migrated to coroutines. These have implicit support and from what I know the coroutine adapter is hardcoded to use okhttp's thread dispatcher (not the caller context, as it was possible with rxjava; the async boolean parameter)

What happens now is that, there are cases where requests need to be initiated from within okhttp's interceptors/authenticator; which are ran on okhttp's threads

From what I gather, that threadpool is limited, therefore calling new request when the thread pool is maxed out, will lead to deadlock

(Just for clarification, the pseudo-codey situation is this)

```kotlin
fun OkhttpAuthenticator.authenticate() {
	...
	synchronized(this) {
		runBlocking { retrofitService.suspendingRefreshTokens() }<--- 
		...
	}
}
```
What is the recommended solution for this?

Having the auth calls declared as synchronous in retrofit?
Drive auth layers via a custom (separate) dispatcher?
Make dispatcher smart enought not to hop from okhttp thread to okhttp thread?
Is there option to not use okhttp's threadpools as it was in rxjava?

I know this might be out of retrofit scope, but I believe many implementations in the wild have this issue

**Comment by yschimke** [comment] 2021-07-17 19:03
Dupe of https://github.com/square/okhttp/issues/6754

**Closed by yschimke** 2021-07-17 19:03 UTC
Labels: enhancement

**Comment by commonsguy** [comment] 2022-01-05 15:42
FWIW, this *is* #6754, so this seems to be closed as a dupe of itself.

**Comment by yschimke** [comment] 2022-01-05 17:12
Dupe of https://github.com/square/okhttp/issues/6747
