### ISSUE TITLE
RejectedExecutionException in RealWebSocket.onClose()

### ISSUE THREAD

**Issue by dusanvita** [square/okhttp#2455] opened 2016-03-31 21:57 UTC
I'm getting a lot of RejectedExecutionException from line okhttp3.internal.ws.RealWebSocket$1.onClose (RealWebSocket.java:82) while using the engine.io/socket.io library. 

I assume that ping response runnable that is writing the pong by locking the thread, is staying in the pool long enough to create a problem when server requests socket close in the meantime? Since only one runnable can be in the pool at the time and so RejectedExecutionException is thrown.

https://github.com/square/okhttp/commit/8a1e6ceec92963423b4cc9f5edded6363fc2c43f#diff-84851fc7b3d535627088311c7ca1951dR70

Library version 3.0.1

Sorry for not writing the test case, I spent the whole day so far trying to find the issue...

**Comment by hamberluo** [comment] 2016-06-06 07:18
i also met this problem.

```
Fatal Exception: java.util.concurrent.RejectedExecutionException: Task okhttp3.internal.ws.RealWebSocket$1$2@21f58605 rejected from java.util.concurrent.ThreadPoolExecutor@313dc65a[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
       at okhttp3.internal.ws.RealWebSocket$1.onClose(RealWebSocket.java:82)
       at okhttp3.internal.ws.WebSocketReader.readControlFrame(WebSocketReader.java:205)
       at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:106)
       at okhttp3.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
       at okhttp3.ws.WebSocketCall.createWebSocket(WebSocketCall.java:151)
       at okhttp3.ws.WebSocketCall.access$000(WebSocketCall.java:41)
       at okhttp3.ws.WebSocketCall$1.onResponse(WebSocketCall.java:97)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by hamberluo** [comment] 2016-06-16 06:34
3.3.1 still has this bug.

**Comment by PiotrWpl** [comment] 2016-06-29 06:58
Is there a chance to fix this in 3.4?

**Comment by swankjesse** [comment] 2016-06-29 12:49
Can you write a test case to reproduce the problem? We've got a bunch of WebSocket tests to get you started.

**Comment by PiotrWpl** [comment] 2016-06-30 06:37
I can't reproduce this. I just seeing it in Crashlytics. All Android versions, different devices.
I'm using https://github.com/socketio/socket.io-client-java (0.7.0) as websocket client and https://github.com/socketio/socket.io (1.4.5) on the server side.

**Comment by PiotrWpl** [comment] 2016-07-04 08:52
This is how it looks in Fabric (Crashlytics) at last 30 days.

<img width="1032" alt="crash_view" src="https://cloud.githubusercontent.com/assets/1515300/16555457/046fad1c-41d5-11e6-964f-db24aa34f72a.png">

[issue_911_crash_577a0373013a00012f05cbdb0dca4161.txt](https://github.com/square/okhttp/files/345926/issue_911_crash_577a0373013a00012f05cbdb0dca4161.txt)

**Comment by rafaelekol** [comment] 2016-07-15 08:57
Have same crash report for our app in Crashlytics
We use OkHttp 3.3.1 with io.socket:socket.io-client:0.7.0
Here is the log:

```

#0. Crashed: OkHttp Dispatcher: 0 0 0x0000000000000000
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
       at okhttp3.internal.ws.RealWebSocket$1.onClose(RealWebSocket.java:82)
       at okhttp3.internal.ws.WebSocketReader.readControlFrame(WebSocketReader.java:205)
       at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:106)
       at okhttp3.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
       at okhttp3.ws.WebSocketCall.createWebSocket(WebSocketCall.java:152)
       at okhttp3.ws.WebSocketCall.access$000(WebSocketCall.java:41)
       at okhttp3.ws.WebSocketCall$1.onResponse(WebSocketCall.java:97)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:811)

--

Fatal Exception: java.util.concurrent.RejectedExecutionException: Task okhttp3.internal.ws.RealWebSocket$1$2@2d270c9d rejected from java.util.concurrent.ThreadPoolExecutor@3de66512[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
       at okhttp3.internal.ws.RealWebSocket$1.onClose(RealWebSocket.java:82)
       at okhttp3.internal.ws.WebSocketReader.readControlFrame(WebSocketReader.java:205)
       at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:106)
       at okhttp3.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
       at okhttp3.ws.WebSocketCall.createWebSocket(WebSocketCall.java:152)
       at okhttp3.ws.WebSocketCall.access$000(WebSocketCall.java:41)
       at okhttp3.ws.WebSocketCall$1.onResponse(WebSocketCall.java:97)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:811)

#0. Crashed: OkHttp Dispatcher: 0 0 0x0000000000000000
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
       at okhttp3.internal.ws.RealWebSocket$1.onClose(RealWebSocket.java:82)
       at okhttp3.internal.ws.WebSocketReader.readControlFrame(WebSocketReader.java:205)
       at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:106)
       at okhttp3.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
       at okhttp3.ws.WebSocketCall.createWebSocket(WebSocketCall.java:152)
       at okhttp3.ws.WebSocketCall.access$000(WebSocketCall.java:41)
       at okhttp3.ws.WebSocketCall$1.onResponse(WebSocketCall.java:97)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:811)

```

**Comment by dave-r12** [comment] 2016-07-16 13:59
I think I've found a way to trigger this, and part of it is that engine.io library is closing the socket then trying to write to it!

```java
        if (wsCall != null) {
            wsCall.cancel();
        }
        if (ws != null) {
            try {
                ws.close(1000, "");
            } catch (IOException e) {
                // websocket already closed
            } catch (IllegalStateException e) {
                // websocket already closed
            }
        }
```

I'm gonna see if I can add a fix for this unusual scenario.

**Comment by dave-r12** [comment] 2016-07-16 14:20
Yes, ws.close fails with IOException, causing it to shutdown the executor. Shouldn't their code first call ws.close, then cancel?

**Comment by swankjesse** [comment] 2016-07-16 14:42
Ahhhh... shutting down the executor seems like a mistake.

**Comment by rajeefmk** [comment] 2016-07-19 12:53
A little bit confused here. I also got this error after updating to socket.io 0.7.0

So the issue is really with socket.io ( / engine.io) closing the socket then trying to write to it ? Should the issue be created in the socket.io repo ?

**Comment by dusanvita** [comment] 2016-07-19 13:09
Yeah, the problem lies in the **engine.io** library when shutting down the executor when **switching the transport from Polling to Websocket**. Quick fix if you can allow yourself not to use the Polling transport but only Websocket when setting up the socket.io library. 

So, by default it will do a handshake via Polling and switch to Websocket if the server responds with an upgrade to websocket command in the handshake response. Here's the code from **Socket constructor**:

```java
this.transports = new ArrayList<String>(Arrays.asList(opts.transports != null ?
                opts.transports : new String[]{Polling.NAME, WebSocket.NAME}));
```

So you can just completely **avoid using the Polling transport** by passing the options to the constructor with transport explicitly set to:

```java
options.transports = new String[] { WebSocket.NAME };
```

**Comment by xuduo** [comment] 2016-07-20 09:51
will this fix the problem?

okhttp3.RealCall.java
```
@Override public void cancel() {
    retryAndFollowUpInterceptor.cancel(); 
   //add dispatcher.cancelAll()
    client.dispatcher().cancelAll();   
  }
```
Dispatcher.cancelAll()
seems to not have been used in okhttp

**Comment by dave-r12** [comment] 2016-07-20 12:38
After mucking with the socket.io client and server a bit more, I see there is a race condition in the tear down code. If you call disconnect(true) from the server, it will send a data frame, then a close frame. When the client processes the data frame, they appear to encode that the connection should be closed, and spawn an async task that turns around and calls WebSocket#close(). If that async task happens to execute just prior to processing the close frame, then this exception is thrown (because they close the socket, then try to write to it which shuts down the executor.)

I opened this pull request https://github.com/socketio/engine.io-client-java/pull/61.

Currently I do not see a workaround to this scenario other than changing the code.

**Comment by PiotrWpl** [comment] 2016-08-02 12:12
@dusanvita 
> Quick fix if you can allow yourself not to use the Polling transport but only Websocket when setting up the socket.io library.

Thx, but how can I determine, that I can use only websockets? ;)

**Comment by joshimohit** [comment] 2016-08-03 07:15
@swankjesse : What shall we do, change the  io.socket:socket.io-client:0.7.0 library as suggested by @dave-r12 or use square#2455 .

**Closed** 2016-09-20 04:03 UTC
Labels: bug, websockets

**Comment by fingdo** [comment] 2017-04-18 01:44
I use okhttp 3.4.2 , and all project and module use okhttp 3.4.2
```
java.util.concurrent.RejectedExecutionException: Task okhttp3.internal.ws.RealWebSocket$1$2@2ddff9b rejected from java.util.concurrent.ThreadPoolExecutor@9493f38[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2014)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:794)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1340)
	at okhttp3.internal.ws.RealWebSocket$1.onClose(RealWebSocket.java:82)
	at okhttp3.internal.ws.WebSocketReader.readControlFrame(WebSocketReader.java:205)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:106)
	at okhttp3.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
	at okhttp3.ws.WebSocketCall.createWebSocket(WebSocketCall.java:152)
	at okhttp3.ws.WebSocketCall.access$000(WebSocketCall.java:41)
	at okhttp3.ws.WebSocketCall$1.onResponse(WebSocketCall.java:97)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:833)
```

**Comment by guoxiaoxing** [comment] 2017-06-21 08:51
The problem log

```
java.util.concurrent.RejectedExecutionException: Task okhttp3.internal.ws.RealWebSocket$1$2@2ddff9b rejected from java.util.concurrent.ThreadPoolExecutor@9493f38[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2014)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:794)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1340)
	at okhttp3.internal.ws.RealWebSocket$1.onClose(RealWebSocket.java:82)
	at okhttp3.internal.ws.WebSocketReader.readControlFrame(WebSocketReader.java:205)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:106)
	at okhttp3.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
	at okhttp3.ws.WebSocketCall.createWebSocket(WebSocketCall.java:152)
	at okhttp3.ws.WebSocketCall.access$000(WebSocketCall.java:41)
	at okhttp3.ws.WebSocketCall$1.onResponse(WebSocketCall.java:97)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:833)
```


When you call shutdown(), it can cause this problem. Just like this:

`mOkHttpClient.dispatcher().executorService().shutdown();
`
