### ISSUE TITLE
ExtCertPathValidatorException: Could not validate certificate on Android 5.0 after removing the use of com.android.org.conscrypt.SSLParametersImpl

### ISSUE THREAD

**Issue by JimJayLee** [square/okhttp#6466] opened 2020-12-10 09:58 UTC
Due to the warnings of use of non-sdk interfaces by Google, I removed the reflection invoke of com.android.org.conscrypt.SSLParametersImpl in Okhttp-v3.12.0. Since this is under a try-catch statement, it is okay to get rid of it. 

Later on, we published a new release and received some complaints about login failure in game. A user sent a pic to us to depict the issue. 

![WeChat Work截圖_ec6d1c35-3064-4d11-ad8b-94d70e166159](https://user-images.githubusercontent.com/11881446/101753857-12726580-3b0e-11eb-934d-5c62a8d097c2.png)

First at all, the answer on Internet is adjust the system time on your phone. However, the time is quite right. The problem occurred when user updated the game. So the only modification in APP is the removal of the non-sdk interfaces. The device os is android 5.0. Devices above api level 21 work well. 

Considered there are at least 10k users invoked, we decided to roll back game to the former version temporarily. And we found out the problem solved when switching to another host. It turns out that android 5.0 is getting a outdated certificate. But it is a valid certificate of the host. 

I didn't know the use of SSLParametersImpl is essential part of the library, since it is restricted api officially and may not be found in any android version. I would say it should not depend on this unofficial api  to make okhttp work properly. It should be an extra feature or something.

**Comment by swankjesse** [comment] 2020-12-10 22:50
What action would you like for us to take?

**Comment by yschimke** [comment] 2020-12-11 07:41
That code isn't there for the fun of it, it keeps legacy functionality working for older devices such that 3.12.12 supports older than Android 5.0.  

https://github.com/square/okhttp/blob/parent-3.12.12/okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.java#L244-L253

We can't remove it, you need to upgrade to OkHttp 4.9.0 to remove the warning or live with your forked version.  That reflection code still exists on 4.9.0 but shouldn't be triggered on newer devices.

https://github.com/square/okhttp/blob/master/okhttp/src/main/kotlin/okhttp3/internal/platform/android/StandardAndroidSocketAdapter.kt

We can't help with the expired certificate, you should raise with the server team.

Closing this out.

**Closed by yschimke** 2020-12-11 07:41 UTC
Labels: bug

**Comment by JimJayLee** [comment] 2020-12-14 03:27
@yschimke You did not get it. The certificate is valid, not expired until July, 2021 which is checked for many times. If the certificate is expired, then why do the devices above 5.0 work properly? 

Depended on what you mentioned, you indicated that okhttp needs SSLParametersImpl to work on older android version below android 5.0. But it should work on android 5.0 if I do not get you wrong on "older that Android 5.0".

**Comment by yschimke** [comment] 2020-12-14 07:45
We probably can't help you without a definitive stacktrace showing a problem with a live vertificate or similar.  There are a lot variables here including whatever the server is doing, potentially serving different certificates to different devices etc.

Rather than continue the dicussion here, you should probably ask on stackoverflow where a wider variety of Android users and experts will see it.  You will likely get a faster answer and we stick to reproducible bug reports in this issue tracker.

On the other hand since you've already dug in, if you can make a reproduction we can use, I'd love to dig in. Maybe a PR with a failing test to get started.
