### ISSUE TITLE
Form body encoding changed from + to %20 in 4.12.0

### ISSUE THREAD

**Issue by jimshowalter** [square/okhttp#8142] opened 2023-12-17 19:53 UTC
Was this intentional? There's nothing about it in the release notes, and it increases the size of form bodies.

**Comment by swankjesse** [comment] 2023-12-19 02:00
I don’t believe the behavior has changed in OkHttp 4.12.0.

We’ve got a test case in 4.12.0 that hasn’t changed since December 8, 2019.
https://github.com/square/okhttp/blob/okhttp_4x/okhttp/src/test/java/okhttp3/FormBodyTest.java#L26

But we did change it in 5.0.0-alpha.2, and I announced that in our changelog:
https://github.com/square/okhttp/pull/6518/files
https://square.github.io/okhttp/changelogs/changelog/#version-500-alpha2

Is it possible you’re running the 5.0 release unexpectedly, perhaps via a transitive dependency?

Either way I’m sorry for the disruption, and we don’t make breaking changes lightly.

**Comment by jimshowalter** [comment] 2023-12-19 21:12
It appears we mixed mockwebserver alpha 5 with okhttp 4.12.0.

Oddly, it works, but we'd prefer to use com.squareup.okhttp3:mockwebserver:4.12.0.

But when we try to do that, there's no okhttp3.mockwebserver.MockWebServerExtension.

Is there some other non-5/non-alpha jar we need to add to get the equivalent of a JUnit 5 extension class for mockwebserver 4.12.0?

**Comment by jimshowalter** [comment] 2023-12-19 21:23
We'd love to use your v5 alpha jars, but we have to keep dependencies aligned with the latest Spring and Spring Boot, and they're on 4.12.0.

**Comment by swankjesse** [comment] 2023-12-19 21:23
One of the main goals of OkHttp 5.x is to fix our longstanding bug where MockWebServer is strongly coupled with JUnit 4.

**Comment by swankjesse** [comment] 2023-12-19 21:24
I’ll do what I can to get 5.0 final out soon, which will hopefully be taken up quickly by our Spring friends.

**Comment by jimshowalter** [comment] 2023-12-19 22:50
Is there some way to use mockwebserver alpha 5 without changing the form body?

**Comment by swankjesse** [comment] 2023-12-20 03:54
Could you please elaborate on the problem with the new behaviour? According to the PR that changed it, the new behaviour is closer to what the specs expect.

**Comment by RonakWithCode** [comment] 2023-12-20 06:57
In version 4.12.0, there was a change in form body encoding where spaces are now represented as %20 instead of the plus sign (+). Check the release notes or documentation for details, and update your code accordingly for compatibility.

**Comment by swankjesse** [comment] 2023-12-20 12:52
@RonakWithCode  there was no such behaviour change in 4.12. Please see the comment above.

**Comment by jimshowalter** [comment] 2023-12-20 18:48
The mystery is that:

- We're on 4.12.0 for everything except mockwebserver.
- We have Gradle forces for okhttp, and they work even for mockwebserver, as shown in the output from gradlew dependencies:
> \--- com.squareup.okhttp3:mockwebserver3-junit5:5.0.0-alpha.2
     +--- com.squareup.okhttp3:mockwebserver3:5.0.0-alpha.2
     |    +--- com.squareup.okhttp3:okhttp:5.0.0-alpha.2 -> 4.12.0
- The behavior of our form-body test changed from + to %20.

**Comment by yschimke** [comment] 2023-12-24 06:23
Can you reproduce in a minimal build with only 4.12.0?

Otherwise it points to an issue with your gradle build still lying about the version.

**Comment by yschimke** [comment] 2023-12-24 08:34
Closing for now as we have tests for this, will reopen if we can repro it failing on 4.12.0

**Closed by yschimke** 2023-12-24 08:34 UTC
Labels: bug, needs info
