### ISSUE TITLE
At Okhttp2.0,we can okhttpclient.cancel(tag). But at Okhttp3.0,How to cancel a request？

### ISSUE THREAD

**Issue by Larnoo** [square/okhttp#2550] opened 2016-05-11 08:13 UTC
At Okhttp2.0,we can okhttpclient.cancel(tag). But at Okhttp3.0,How to cancel a request？

**Comment by swankjesse** [comment] 2016-05-11 11:22
Dupe of https://github.com/square/okhttp/issues/2205

**Closed by swankjesse** 2016-05-11 11:22 UTC

**Comment by GhostInMatrix** [comment] 2016-05-25 15:59
Well，when using okHttp3, you can set tag in request,like:Request request = new Request.Builder()
                .url(url)
                .tag("sss").build();
so,when you wanna cancel the request with tag "sss",you can do like this:


 for(Call call : mOkHttpClient.dispatcher().queuedCalls()) {
            if(call.request().tag().equals("sss"))
                call.cancel();
        }
        for(Call call : mOkHttpClient.dispatcher().runningCalls()) {
            if(call.request().tag().equals("sss"))
                call.cancel();
        }

**Comment by randomlock** [comment] 2017-03-19 18:59
How to know if the call was cancelled ?

**Comment by JakeWharton** [comment] 2017-03-19 19:11
isCanceled()
