### ISSUE TITLE
Chain.with*Timeout methods do not work with Network Interceptors

### ISSUE THREAD

**Issue by ryanhall07** [square/okhttp#6100] opened 2020-05-29 16:49 UTC
code to reproduce
```
override fun intercept(chain: Interceptor.Chain): okhttp3.Response {
  chain
    .withReadTimeout(1, TimeUnit.MILLISECONDS)
    .proceed(request)
}

```

exception
```
    java.lang.IllegalStateException: network interceptor misk.client.NetworkInterceptorWrapper@1429341e must call proceed() exactly once
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:104)
    	at io.opentracing.contrib.okhttp3.TracingCallFactory$NetworkInterceptor.intercept(TracingCallFactory.java:105)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
    	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
    	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
    	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
    	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
    	at datadog.trace.instrumentation.okhttp3.TracingInterceptor.intercept(TracingInterceptor.java:36)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
    	at io.opentracing.contrib.okhttp3.TracingCallFactory$1.intercept(TracingCallFactory.java:59)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
    	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
    	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    	at java.base/java.lang.Thread.run(Thread.java:834)
```

The issue is `withReadTimeout` creates a copy of the `Chain`, so the previous `Interceptor` that invoked this `Interceptor` no longer has a reference to the `Chain`. The previous `Interceptor` attempts to verify that this `Interceptor` actually called `proceed` by checking the value of `calls`. However, this `Interceptor`, which has a copy of the `Chain`, updates a different `calls` reference when invoking `proceed`.

Problematic code:
https://github.com/square/okhttp/blob/19771365f25d986d125478a75c15d24d6e285e12/okhttp/src/main/kotlin/okhttp3/internal/http/RealInterceptorChain.kt#L104

More than happy to contribute a fix. Would it make more sense to make `Chain` mutable (update timeouts) or pass a reference to `calls` around? I lean towards making `Chain` mutable to prevent similar bugs like this in the future. However, I'm not familiar with what problems a mutable `Chain` might cause.

**Comment by yschimke** [comment] 2020-05-29 17:12
I believe this is very much by design.  But I'm surprised we didn't document this. I think by the time we hit network interceptors, we have already used the timeout values in establishing the connection.  So it's too late.

We should probably add here https://square.github.io/okhttp/interceptors/

**Comment by ryanhall07** [comment] 2020-05-29 17:17
interesting. how do the read/write timeouts work for retries? are they total timeouts? If not, I'd still want to control the read/write timeout per retry.

**Comment by yschimke** [comment] 2020-05-29 17:44
I doubt we'd want to land something partial here. We should probably make the constraints more explicit and documented.

**Comment by yschimke** [comment] 2020-05-31 07:38
For now, I'm going to close this out by docs and a clearer restriction.  Happy to discuss more if we think this is critical, it's a valid request just not supported currently.

https://github.com/square/okhttp/pull/6102

**Closed by yschimke** 2020-05-31 07:38 UTC
Labels: bug
