### ISSUE TITLE
[Error] unexpected end of stream on Connection

### ISSUE THREAD

**Issue by Faz95210** [square/okhttp#3703] opened 2017-11-30 15:18 UTC
Hi, 
I've been struggling for the past weeks on this error. I'm working on an app communicating with alexa but every request I make on https://avs-alexa-[eu/na].amazon.com/ gives me this error `java.io.IOException: unexpected end of stream on Connection{avs-alexa-eu.amazon.com:443, proxy=DIRECT hostAddress=avs-alexa-eu.amazon.com/52.94.216.73:443 cipherSuite=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 protocol=http/1.1}`

I try do it in a quite simple way : <br>
 ```
val okHttpClient: OkHttpClient = OkHttpClient()
        val request = okhttp3.Request.Builder()
                .get()
                .header("Authorization", authorizationHeader)
                .url(url + version + "/directives")
                .build()
        try {
            val response = okHttpClient.newCall(request).execute()
            res.body("success")
        } catch (e: Exception) {
            res.body("error")
        }
```
But I just can't figure out why I did wrong. It works fine on android 5.0 and more, but doesn't work on kitkat and older.
I've tried with custom socketFactory, installing TLSv1.2 when it isn't already installed, telling okhttp which cipher to use. But I'm still stuck. Any idea?

**Comment by yschimke** [comment] 2017-12-01 07:11
Dupe of https://github.com/square/okhttp/issues/1741

This is a better question for stackoverflow e.g. https://stackoverflow.com/questions/45838774/java-io-ioexception-unexpected-end-of-stream-on-connection-in-android

**Closed by yschimke** 2017-12-01 07:11 UTC
Labels: android-legacy

**Comment by ameenudheenirshad** [comment] 2019-07-26 10:12
unexpected end of stream issue is caused mainly when "Content-Length" mentioned in API response doesn't match the real size of API. Better contact your backend developer weather he is overriding content length.

**Comment by Balajipss** [comment] 2019-08-23 10:43
We had the similar issue. Adding below lines solved the issue

headers:{
      Accept: 'application/json',
      'Content-Type': 'application/json',
      'Cache-Control':'no-cache'
    },

**Comment by Atta-Ur-Rahman** [comment] 2021-04-22 10:51
just restart your mobile solve my issue
