### ISSUE TITLE
Inconsistent timeout behaviour when attaching an interceptor that accesses the ResponseBody

### ISSUE THREAD

**Issue by troinine** [square/okhttp#2582] opened 2016-05-27 08:52 UTC
Originally we had some tests against Retrofit (2.0.0-beta3) that tested timeouts simply by exercising `MockWebServer` and everything worked fine we were able to simulate a socket timeout situation. After Retrofit (2.0.0) upgraded its OkHttp dependency to 3.2.0 things started to behave weirdly.

See the following test:

```
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.logging.HttpLoggingInterceptor;
import okhttp3.logging.HttpLoggingInterceptor.Level;
import okhttp3.mockwebserver.MockResponse;
import okhttp3.mockwebserver.MockWebServer;
import org.junit.After;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import java.io.IOException;
import java.net.SocketTimeoutException;
import java.util.concurrent.TimeUnit;

public class TimeoutTest {
    private MockWebServer mockWebServer;
    private OkHttpClient okHttpClient;

    @Rule
    public ExpectedException expectedException = ExpectedException.none();

    @Before
    public void setup() throws IOException {
        mockWebServer = new MockWebServer();
        mockWebServer.start();

        okHttpClient = new OkHttpClient.Builder()
                .readTimeout(100, TimeUnit.MILLISECONDS)
                // Remove this or change the level to make the test pass
                .addNetworkInterceptor(new HttpLoggingInterceptor().setLevel(Level.BODY))
                .build();
    }

    @After
    public void teardown() throws IOException {
        if (mockWebServer != null) {
            mockWebServer.shutdown();
        }
    }

    @Test
    public void test() throws IOException {
        mockWebServer.enqueue(new MockResponse()
                .setBody("12")
                .clearHeaders()
                .setHeader("Content-Length", "10"));

        Request request = new Request.Builder()
                .url(mockWebServer.url("/"))
                .build();

        expectedException.expect(SocketTimeoutException.class);

        okHttpClient.newCall(request).execute().body().string();
    }
}  
```

This test tries to simulate a timeout just using OkHttp. I did copy the `MockResponse` semantics from one of your test cases. 

The issue here is that when you have the `HttpLoggingInterceptor` attached, you get a `ConnectException` when the interceptor accesses the response body. 

However, if you remove the logging interceptor or set it to log only the request URL or headers, everything works just fine. 

The behaviour seem to have changed between OkHttp 2.7 and 3.2 as timeout tests worked fine in our case when using OkHttp 2.7. Of course OkHttp has gone through a major change between 2.x and 3.x thus it is understandable that behaviour changes. However, I'm not so sure if the contract from the client's point of view is stable as adding an interceptor affects the output exception.

In general it would also nice to have some examples how to test read, write and connection timeouts since we have a special behaviour in our code that is affected by timeouts and we want to test that code.

**Comment by swankjesse** [comment] 2016-06-03 01:05
The root cause is that the logging interceptor triggers the body to be loaded, and when that fails we retry the whole request. We could potentially mark the response as “completed” when we start reading the body and refuse to retry once that happens.

**Comment by yschimke** [comment] 2019-08-02 05:02
We should presumably look at

  open fun isOneShot(): Boolean = false

**Comment by yschimke** [comment] 2020-04-11 14:26
Marking as won't fix.  Hasn't gotten much attention since 2016 and we don't actively improve logging interceptor.

**Closed by yschimke** 2020-04-11 14:26 UTC
Labels: bug
