### ISSUE TITLE
Expose Websocket Ping/Pong Round Trip Time via the WebsocketListener

### ISSUE THREAD

**Issue by bentemple** [square/okhttp#6146] opened 2020-06-25 23:25 UTC
The ping / pong round trip time is important and useful information that can pretty trivially be exposed via the WebsocketListener but currently isn't. Can we expose this information in a method such as `onPong(roundTripTime: Long)`?

There have been some discussions around the ping/pong mechanism:
https://github.com/square/okhttp/issues/2239
https://github.com/square/okhttp/issues/3197

OkHttp does now support configuring the ping timeout, but it would also be valuable and useful information to know how long the round-trip-time of each ping request takes. Websockets are often used in real time applications, and knowing your latency to the server can have a range of uses across an app to provide better synchronization with the server.

**Comment by yschimke** [comment] 2020-06-26 06:45
Think this is a dupe of https://github.com/square/okhttp/issues/5833, we wouldn't do one without the other I think.

Please mention your requirements there.

**Closed by yschimke** 2020-06-26 06:45 UTC
Labels: enhancement
