### ISSUE TITLE
RejectedExecutionException in client.dispatcher().enqueue

### ISSUE THREAD

**Issue by mstrelex** [square/okhttp#4152] opened 2018-07-14 11:04 UTC
Hi,

Getting the following exception after computer returns from sleep mode:

`Exception in thread "EventThread" java.util.concurrent.RejectedExecutionException: Task okhttp3.RealCall$AsyncCall@17c8d3 rejected from java.util.concurrent.ThreadPoolExecutor@7822a9d2[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 25]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at okhttp3.Dispatcher.enqueue(Dispatcher.java:132)
	at okhttp3.RealCall.enqueue(RealCall.java:100)
	at okhttp3.internal.ws.RealWebSocket.connect(RealWebSocket.java:192)
	at okhttp3.OkHttpClient.newWebSocket(OkHttpClient.java:438)`

Any ideas?
Much obliged.

**Comment by mstrelex** [comment] 2018-10-01 13:38
Anyone ?

**Comment by swankjesse** [comment] 2018-11-04 05:12
Duplicate of https://github.com/square/okhttp/issues/3424

**Closed by swankjesse** 2018-11-04 05:12 UTC
Labels: bug
