### ISSUE TITLE
ConnectionPool.maxConcurrentStreams

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#5950] opened 2020-04-13 13:13 UTC
We should build this. It’s a weaker form of custom connection management, but very easy to configure and implement.

**Comment by swankjesse** [comment] 2020-04-13 13:14
https://github.com/square/okhttp/issues/4530

**Comment by yschimke** [comment] 2023-05-21 08:16
Closing as a dupe of client side load balancing

**Closed by yschimke** 2023-05-21 08:16 UTC
Labels: enhancement
