### ISSUE TITLE
incorrect treatment of informational HTTP responses

### ISSUE THREAD

**Issue by reschke** [square/okhttp#7440] opened 2022-09-08 10:24 UTC
From <https://github.com/greenbytes/java-http-1xx-tests>:

~~~
mvn clean install -Dtest=OkHttpClientTests
~~~

1xx status codes other than 100 are treated incorrectly; they are reported as final responses.

**Comment by yschimke** [comment] 2022-09-08 10:28
Dupe of https://github.com/square/okhttp/issues/2257

**Closed by yschimke** 2022-09-08 10:28 UTC
Labels: bug
