### ISSUE TITLE
Onhttp3 thread pool

### ISSUE THREAD

**Issue by xh520md** [square/okhttp#5608] opened 2019-11-18 03:50 UTC
When I used okhttp3, every per request will  create a thread. Look at the source code. There is a “ConnectionPool” class with a  static method: static {
Executor = new ThreadPoolExecutor(0, 2147483647, 60L, timeunit.seconds, new SynchronousQueue(), Util. ThreadFactory ("OkHttp ConnectionPool", true);
}. I have two questions. The first one is that after executing the request, the thread is idle, and it has to wait 60 seconds for recycling. When the concurrency is high, Can we use this idle threads instead of creating threads all the time? The second problem is naming. Currently all thread pool thread names are "OkHttp ConnectionPool". It is recommended to add the thread number "OkHttp ConnectionPool-%d" ,Easy to find problems

**Comment by swankjesse** [comment] 2019-11-18 04:05
Duplicate of https://github.com/square/okhttp/issues/5607

**Closed by swankjesse** 2019-11-18 04:05 UTC
Labels: enhancement

**Comment by xh520md** [comment] 2019-11-18 04:30
How can I ask questions on GitHub？




---Original---
