### ISSUE TITLE
JDK8 > u251 detected as Jdk9Platform

### ISSUE THREAD

**Issue by manusa** [square/okhttp#6054] opened 2020-05-15 05:44 UTC
## Description

When running OkHttp with JDKu252, the output of the following method is **not** null:
https://github.com/square/okhttp/blob/39a081e30ede15c415966efe5044e93e6a2d7e10/okhttp/src/main/java/okhttp3/internal/platform/Jdk9Platform.java#L93-L106

Apparently the newer versions of JDK8 include `SSLParameters#setApplicationProtocols` and `SSLSocket#getApplicationProtocol`.

The main issue with this is that Application-Layer Protocol Negotiation (ALPN) is inherently enabled by having a [JDK9Platform](https://github.com/square/okhttp/blob/39a081e30ede15c415966efe5044e93e6a2d7e10/okhttp/src/main/java/okhttp3/internal/platform/Jdk9Platform.java#L48) but it's not supported out-of-the-box in JDK8. When performing any connection to a server where `http/2`is supported, OkHttp will then select this protocol (as it is the more efficient), but the connection will never succeed.

## Possible solution

Check Java version in `Jdk9Platform#buildIfSupported` and return null in case of JDK8.
e.g.
```java
if (System.getProperty("java.version", "").startsWith("1.8")) {
  return null;
}
```

## How to reproduce

Any project using OkHttp connecting to a server that supports `http/2` running in JDK8u252 will get a `java.net.SocketException: Broken pipe`.

e.g. Run any [kubernetes-client](https://github.com/fabric8io/kubernetes-client) example with k8s 1.18.2

## Related issues
- fabric8io/kubernetes-client#2212
- [Problem analysis](https://github.com/fabric8io/kubernetes-client/issues/2212#issuecomment-628434995)

**Comment by yschimke** [comment] 2020-05-15 08:03
> The main issue with this is that Application-Layer Protocol Negotiation (ALPN) is inherently enabled by having a JDK9Platform but it's not supported out-of-the-box in JDK8. When performing any connection to a server where http/2is supported, OkHttp will then select this protocol (as it is the more efficient), but the connection will never succeed.

The upstream change in JDK 251/251 means that HTTP/2 should be supported.  So there is likely something else going wrong in addition.

This report is a dupe of https://github.com/square/okhttp/issues/6019 and https://github.com/square/okhttp/issues/6000

**Comment by yschimke** [comment] 2020-05-15 08:13
A bit more context, OkHttp should be using Jdk9Platform on Jdk8 251/252.  We can't fall back to alpn-boot which is disabled now on the latest JDK8 JVMs.

See fixes in 

https://github.com/square/okhttp/pull/5972/files [4.x]
https://github.com/square/okhttp/pull/5977/files [3.12.x]

But if you use some libraries that have their own Socket implementations, you might still find problems because the default implementations of Socket methods throws UnsupportedOperationException.  While this is handled in OkHttp it is not desireable as it means that HTTP/2 is not supported until you upgrade those other libraries as well.

https://github.com/yschimke/okhttp/blob/a15af59debd11cf62235ad1508d26ab3d0b51e95/okhttp/src/main/kotlin/okhttp3/internal/platform/Jdk9Platform.kt#L42-L54

**Closed by yschimke** 2020-05-15 08:13 UTC
Labels: bug

**Comment by manusa** [comment] 2020-05-15 09:02
Thx @yschimke, sorry for duplicating the issue.

There's a follow-up [here](https://github.com/fabric8io/kubernetes-client/issues/2212#issuecomment-629119493) with a little more insight on default implementation not throwing UnsupportedOperationException :disappointed:

**Comment by yschimke** [comment] 2020-05-15 09:23
@manusa on the contrary, thanks for the detailed report. Let's continue on the other bug.
