### ISSUE TITLE
MockWebserver crashing with ssl negotiation error

### ISSUE THREAD

**Issue by nimeacuerdo** [square/okhttp#5587] opened 2019-11-06 09:02 UTC
Hi,

We are still not sure about the root cause but our acceptance tests execution phase is failing sometimes due to `MockWebserver` (**4.2.1**) crashing when the following error happens in `acceptConnections()`:

```
11-05 11:53:36.557  5607 23163 E AndroidRuntime: FATAL EXCEPTION: MockWebServer
11-05 11:53:36.557  5607 23163 E AndroidRuntime: Process: com.xxx.xxx.xxx, PID: 5607
11-05 11:53:36.557  5607 23163 E AndroidRuntime: java.lang.AssertionError: java.lang.reflect.InvocationTargetException
11-05 11:53:36.557  5607 23163 E AndroidRuntime: 	at okhttp3.internal.platform.android.AndroidSocketAdapter.a(SourceFile:86)
11-05 11:53:36.557  5607 23163 E AndroidRuntime: 	at okhttp3.internal.platform.AndroidPlatform.b(SourceFile:86)
11-05 11:53:36.557  5607 23163 E AndroidRuntime: 	at okhttp3.mockwebserver.MockWebServer$SocketHandler.handle(MockWebServer.kt:516)
11-05 11:53:36.557  5607 23163 E AndroidRuntime: 	at okhttp3.mockwebserver.MockWebServer$serveConnection$$inlined$execute$1.run(Util.kt:580)
11-05 11:53:36.557  5607 23163 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-05 11:53:36.557  5607 23163 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-05 11:53:36.557  5607 23163 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
11-05 11:53:36.557  5607 23163 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
11-05 11:53:36.557  5607 23163 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-05 11:53:36.557  5607 23163 E AndroidRuntime: 	at okhttp3.internal.platform.android.AndroidSocketAdapter.a(SourceFile:81)
11-05 11:53:36.557  5607 23163 E AndroidRuntime: 	... 6 more
11-05 11:53:36.557  5607 23163 E AndroidRuntime: Caused by: java.lang.NullPointerException: ssl == null
11-05 11:53:36.557  5607 23163 E AndroidRuntime: 	at com.android.org.conscrypt.NativeCrypto.getApplicationProtocol(Native Method)
11-05 11:53:36.557  5607 23163 E AndroidRuntime: 	at com.android.org.conscrypt.NativeSsl.getApplicationProtocol(NativeSsl.java:568)
11-05 11:53:36.557  5607 23163 E AndroidRuntime: 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.getApplicationProtocol(ConscryptFileDescriptorSocket.java:1085)
11-05 11:53:36.557  5607 23163 E AndroidRuntime: 	at com.android.org.conscrypt.OpenSSLSocketImpl.getAlpnSelectedProtocol(OpenSSLSocketImpl.java:134)
11-05 11:53:36.557  5607 23163 E AndroidRuntime: 	... 8 more
```

Any ideas about this? Shouldn't this be handled by `MockWebserver`?

Thanks in advance!

**Comment by swankjesse** [comment] 2019-11-06 12:49
Looks like a bug in the host OS. Which device? Which Android release?

**Comment by nimeacuerdo** [comment] 2019-11-06 13:48
It's an emulator running API 28

**Comment by swankjesse** [comment] 2019-11-06 14:45
Looks like a dupe of this:
https://github.com/square/okhttp/issues/3301

Thought that’s crashing in the cipher suite and this is crashing in the ALPN version.

**Comment by swankjesse** [comment] 2019-11-06 14:49
Reported upstream:
https://github.com/google/conscrypt/issues/781

**Comment by nimeacuerdo** [comment] 2019-11-06 17:32
Cool, thanks for the quick update @swankjesse

**Comment by yschimke** [comment] 2019-11-08 09:16
@swankjesse do we want to special case handling this in AndroidSocketAdapter?

**Comment by swankjesse** [comment] 2019-11-08 12:52
@yschimke yep. Probably even string match the exception message because we don't want to catch unexpected failures.

**Comment by yschimke** [comment] 2019-11-09 07:39
Not going to fix for direct users of Conscrypt as that should come from their bug fix and a dependency upgrade.

**Comment by yschimke** [comment] 2019-11-09 07:47
@nimeacuerdo Can you reproduce and test this when it lands in a snapshot? I'm nervous I either slightly miss the exact conditions or it just delays the NPE until the next interaction with Conscrypt.

**Comment by nimeacuerdo** [comment] 2019-11-09 10:33
@yschimke @swankjesse ok, just let me know when such snapshot is available... although this issue is not happening that often so there'll have to be many successful builds before considering it gone.

**Comment by nimeacuerdo** [comment] 2019-11-12 11:08
btw, I cannot browse the snapshots referenced at https://github.com/square/okhttp/blame/master/README.md#L108.

https://oss.sonatype.org/content/repositories/snapshots/ just shows this:

`Directory listing forbidden`

**Comment by yschimke** [comment] 2019-11-12 13:31
While you can't browse the files, they are there e.g. https://oss.sonatype.org/content/repositories/snapshots/com/squareup/okhttp3/okhttp-tls/4.3.0-SNAPSHOT/okhttp-tls-4.3.0-20191006.161431-1.pom

**Comment by yschimke** [comment] 2019-11-12 13:33
> @yschimke @swankjesse ok, just let me know when such snapshot is available... although this issue is not happening that often so there'll have to be many successful builds before considering it gone.

I think I need to look at Travis snapshot builds - sorry, latest ones probably aren't up to date.

https://travis-ci.org/square/okhttp/builds/610830250

**Comment by swankjesse** [comment] 2019-12-31 04:42
Looks like the core issue here is fixed.

**Closed by swankjesse** 2019-12-31 04:42 UTC
Labels: bug
