### ISSUE TITLE
How to communicate through HTTPS proxy with authentication 

### ISSUE THREAD

**Issue by subisueno** [square/okhttp#7659] opened 2023-01-18 10:06 UTC
I am working for a client using their VM and their Network.
I was facing connectivity problem while invoking my target API using okhttp client. The below link helped me to resolve connectivity issue to some extent -
https://github.com/square/okhttp/issues/6561

`     Authenticator proxyAuthenticator = new Authenticator() {
    @Override public Request authenticate(Route route, Response response) throws IOException {
        String credential = Credentials.basic(username, password);
        return response.request().newBuilder().header("Proxy-Authorization", credential).build();
    }
};

OkHttpClient client = new OkHttpClient.Builder()
        .proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxyHost, proxyPort)))
        .proxyAuthenticator(proxyAuthenticator);
        .socketFactory(new DelegatingSocketFactory(SSLSocketFactory.getDefault()))
        .build(); `

But started facing a new issue - SslException: Unrecognized SSL message, plaintext connection?

The API url invocation is working absolutely fine from my postman with below set up -

1. Done Custom proxy set up in postman
2. Proxy type HTTPS, proxy server host and port
3. Switch on proxy authentication with my id, password

Please help me to find what went wrong in my case.

**Comment by swankjesse** [comment] 2023-01-29 19:24
Duplicate of https://github.com/square/okhttp/issues/3787

**Closed by swankjesse** 2023-01-29 19:24 UTC
Labels: enhancement
