### ISSUE TITLE
decodeHeaderAsJavaNetCookies - value is not trimmed - Crash

### ISSUE THREAD

**Issue by TheMakerOleguch** [square/okhttp#7552] opened 2022-12-12 16:04 UTC
Hi team, I've tried to fetch meta-data from this https://developer.android.com/training/multiscreen/screendensities particular link and received an instant crash on Android.

**All other links work well**. According to `Logcat` there is an issue with parsing cookies in `decodeHeaderAsJavaNetCookies` method, decoder sends untrimmed values to the Builder class, would you mind checking?

I'm using the latest `react-native` version, which under the hood uses the `4.9.2` OkHttp version. (v`4.10.0` has an issue too)

<img width="926" alt="image" src="https://user-images.githubusercontent.com/16706446/207093669-8a0d3d87-86b8-46c9-8aff-af85e3fc2626.png">

```
2022-12-12 18:02:23.525 31954-32207/com.preply E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.preply, PID: 31954
    java.lang.IllegalArgumentException: value is not trimmed
        at okhttp3.Cookie$Builder.value(Cookie.kt:271)
        at okhttp3.JavaNetCookieJar.decodeHeaderAsJavaNetCookies(JavaNetCookieJar.kt:103)
        at okhttp3.JavaNetCookieJar.loadForRequest(JavaNetCookieJar.kt:59)
        at com.facebook.react.modules.network.ReactCookieJarContainer.loadForRequest(ReactCookieJarContainer.java:44)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:74)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
```

**Comment by yschimke** [comment] 2022-12-21 03:05
Also since it's an invalid cookie, you may want to filter these out in a network interceptor as a workaround.

https://stackoverflow.com/questions/1969232/what-are-allowed-characters-in-cookies
https://www.rfc-editor.org/rfc/rfc6265#section-4.1.1

**Comment by yschimke** [comment] 2022-12-21 03:22
I can't reproduce at all on 5.x, it looks like CookieManager is cleaning this up.  I'll switch to 4.10 and see if it's there.

**Comment by yschimke** [comment] 2022-12-21 03:32
Can't reproduce on 4.10 either, any help making the test fail is appreciated.
But I suspect it might be a bad implementation of CookieManager on older Android?

**Comment by yschimke** [comment] 2022-12-21 03:37
Fix 10 years ago for CookieManager https://android.googlesource.com/platform/frameworks/base/+/87ad930037a5ccb915d3ff3675135d405af092d7%5E%21/#F0

But it now offloads to Chromium, so wonder if that is allowing spaces in some versions?

**Comment by yschimke** [comment] 2023-01-03 03:59
Closing as not reproducible.  Likely an issue with the platform CookieManager on some particular device.

**Closed by yschimke** 2023-01-03 03:59 UTC
Labels: bug, needs info
