### ISSUE TITLE
HEAD requests break if the response contains the Content-Length header

### ISSUE THREAD

**Issue by gcapizzi** [square/okhttp#2998] opened 2016-11-21 20:39 UTC
I was trying to execute a `HEAD` request agains http://httpbin.org/get, but I got this error:

```
java.io.IOException: Content-Length and stream length disagree

at okhttp3.ResponseBody.bytes(ResponseBody.java:133)
at okhttp3.ResponseBody.string(ResponseBody.java:154)
```

[RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.13) states that:

> The Content-Length entity-header field indicates the size of the entity-body, in decimal number of OCTETs, sent to the recipient or, __in the case of the HEAD method, the size of the entity-body that would have been sent had the request been a GET.__

so I guess the check should be removed, at least for `HEAD` requests?

**Comment by swankjesse** [comment] 2016-12-10 18:52
Duplicate of https://github.com/square/okhttp/issues/2879

**Closed by swankjesse** 2016-12-10 18:52 UTC
Labels: bug
