### ISSUE TITLE
Unexpected read timeout while request is still being sent

### ISSUE THREAD

**Issue by MarkusMattinen** [square/okhttp#2122] opened 2015-12-16 14:43 UTC
Have been running into this a lot lately with Retrofit 1.9.0 and OkHttp 2.5.0.
While doing a PUT/POST request with a large request body, a "SocketException: socket is closed" is thrown from the native socket implementation. This seems to happen after a time determined by the configured OkHttp read timeout setting.

I would have expected the read timeout setting to mean the maximum time that is allowed to pass between the client having sent the entire request and the server sending the first response byte, or between response bytes sent by the server.
Instead it appears that the read timeout starts immediately and can be triggered while the client is still actively sending the request, at which point the server should not really have been expected to send a single byte yet.

Setting a huge read timeout (globally or for each request) is an ugly hack that does avoid the problem, but obviously that results in unexpectedly long timeouts in cases where the request was small and the server actually takes a long time to respond.

**Comment by swankjesse** [comment] 2015-12-17 00:45
I think it actually behaves the way you want it to. Is it possible something else is interfering? Nothing is better than a cold hard test case.

**Comment by MarkusMattinen** [comment] 2015-12-17 04:13
@swankjesse Here's a test case that seems to always trigger a timeout:

```java
@Test public void unexpectedRequestTimeout() throws Exception {
    final MockWebServer server = new MockWebServer();
    server.setBodyLimit(0);
    server.enqueue(new MockResponse().setBody("done.").throttleBody(1024, 100, TimeUnit.MILLISECONDS));

    final OkHttpClient client = new OkHttpClient();
    client.setReadTimeout(10, TimeUnit.SECONDS);
    client.setWriteTimeout(10, TimeUnit.SECONDS);

    final byte[] buffer = new byte[1024 * 1024];
    final RequestBody requestBody = RequestBody.create(MediaType.parse("application/octet-stream"), buffer);
    final Request request = new Request.Builder().post(requestBody).url(server.url("/")).build();

    client.newCall(request).execute();

    server.takeRequest();
  }
```

There's definitely something weird going on here, though. I'm not sure anymore if it is the read timeout or the write timeout that gets triggered - the stack trace seems to randomly point to either one. Increasing one of the timeouts while keeping the other one at 10 seconds also seems to result in it sometimes working and sometimes not.

I also tested this against a real server by throttling my connections to ~10KB/s and sending a large request with read and write timeouts set to 10 seconds, then watched the packets flow in tcpdump. Sometime after 10 seconds, with the request still in progress and very much active, the socket would just throw the timeout exception and close itself.

**Comment by dave-r12** [comment] 2016-01-01 00:32
Hey, not sure if this will help, but thought I'd note my observations. Running the provided test case on a Windows 10 host with OkHttp 2.7.0, I see the following:

* A SocketTimeoutException that consistently happens during the socket.write() call. I added a logging statement to RequestBody which signals when the write() completes, and it is never emitted.
* Looking at the packets with WireShark, I can see the request never completes. In addition, I'm seeing some "TCP Window Full" entries
* If I change the buffer to `new byte[1024 * 200]`, then the write completes almost instantly, I see my log statement, and then I receive an exception during the socket.read() consistently
* Looking at the packets with WireShark, it recognizes the HTTP POST, but just barely before the SocketTimeoutException is thrown

If I'm interpreting things correctly, in the first scenario the socket.write() call blocks for longer than 10 seconds, which triggers a timeout within OkHttp and it closes the socket. This seems right.

In the second scenario, the socket.write() call *appears* to complete. Even though it returns, I'm still seeing packets flowing in WireShark. I think this means the OS is still in the middle of sending the data. Because it completed, it then enters the socket.read() call which blocks and eventually times out. Again, this seems right.

**Comment by MarkusMattinen** [comment] 2016-01-07 09:03
Thanks for running the test and confirming the behaviour @dave-r12.

Not entirely sure what you mean by "this seems right" - the behaviour that you observed is definitely not what I would expect from the library. The timeouts should not be triggered while packets are still actively flowing.

**Comment by swankjesse** [comment] 2016-01-07 13:41
The packets are flowing, but far away from the application layer and OkHttp. The problem is that there isn't backpressure to cause the writes to block. You'll likely see that if you increase the upload size or decrease the host network’s buffer size.

The real problem is that the host network’s buffer makes MockWebServers read throttle ineffective. The writer can write nearly instantly, but it takes longer than the timeout for the MockWebServer tonrespond to the write.

You could imagine that this buffer & throttling could be occurring on any routing equipment between client and server in a real world deployment. You have a router that accepts the entire request immediately, but trickles those bytes up to the origin webserver.

What would you have OkHttp do in that situation? Remember that although packets are flowing, OkHttp doesn't know that.

**Comment by MarkusMattinen** [comment] 2016-01-07 17:05
I see. I suppose there is not much that can be done about the read timeouts.

That only leaves the write timeout problem then.
To reproduce it more reliably, increase both the throttling speed and the request body size in the previous test case. For example 1MB/s throttling, 20MB body, 10 seconds write timeout.

Like @dave-r12 noted, it seems to be triggered by the AsyncTimeout's watchdog thread closing the socket after the socket.write() call blocks for 10 seconds. Is there a way to avoid that, other than calculating the write timeout from the body size or trying to hack OkHttp to use chunked encoding?

**Comment by swankjesse** [comment] 2016-01-07 21:31
(Chunked encoding shouldn't make a difference.)

**Comment by MarkusMattinen** [comment] 2016-01-08 10:34
You're right, it's not so much about chunked encoding as it is about doing the socket.write() in smaller parts. Test cases (first one fails, second one passes):
```java
@Test public void largeBodyOnePart() throws Exception {
    final MockWebServer server = new MockWebServer();
    server.setBodyLimit(0);
    server.enqueue(new MockResponse().setBody("done.").throttleBody(1024 * 1024, 1000, TimeUnit.MILLISECONDS));

    final OkHttpClient client = new OkHttpClient();
    client.setReadTimeout(10, TimeUnit.SECONDS);
    client.setWriteTimeout(10, TimeUnit.SECONDS);

    final byte[] buffer = new byte[16 * 1024 * 1024];

    final RequestBody requestBody = new RequestBody() {
      public MediaType contentType() {
        return MediaType.parse("application/octet-stream");
      }

      public long contentLength() {
        return buffer.length;
      }

      public void writeTo(BufferedSink sink) throws IOException {
        sink.write(buffer, 0, buffer.length);
      }
    };

    final Request request = new Request.Builder().post(requestBody).url(server.url("/")).build();
    client.newCall(request).execute();
    server.takeRequest();
  }

  @Test public void largeBodyTwoParts() throws Exception {
    final MockWebServer server = new MockWebServer();
    server.setBodyLimit(0);
    server.enqueue(new MockResponse().setBody("done.").throttleBody(1024 * 1024, 1000, TimeUnit.MILLISECONDS));

    final OkHttpClient client = new OkHttpClient();
    client.setReadTimeout(10, TimeUnit.SECONDS);
    client.setWriteTimeout(10, TimeUnit.SECONDS);

    final byte[] buffer = new byte[16 * 1024 * 1024];

    final RequestBody requestBody = new RequestBody() {
      public MediaType contentType() {
        return MediaType.parse("application/octet-stream");
      }

      public long contentLength() {
        return buffer.length;
      }

      public void writeTo(BufferedSink sink) throws IOException {
        sink.write(buffer, 0, buffer.length / 2);
        sink.write(buffer, buffer.length / 2, buffer.length / 2);
      }
    };

    final Request request = new Request.Builder().post(requestBody).url(server.url("/")).build();
    client.newCall(request).execute();
    server.takeRequest();
  }
```

**Comment by swankjesse** [comment] 2016-01-16 23:56
No obvious action for us to take here?

**Comment by MarkusMattinen** [comment] 2016-01-18 09:52
Is the behaviour in the last two test cases expected?
Since I'm using Retrofit I can't actually use the solution that makes the latter test case pass by writing into the sink in chunks.

It would be nice if OkHttp wrote the request body in reasonably-sized chunks so that the timeout actually worked as a timeout, not as a deadline. Being able to disable the watchdog timeout but keep the socket timeout might also work around the problem, but I could not figure out how to do that either.

**Comment by swankjesse** [comment] 2016-01-18 15:19
Chunking the request body isn’t going to make a difference here.

**Comment by MarkusMattinen** [comment] 2016-01-18 15:30
So why does it seem to make a difference in my test case above? Am I doing something else differently?

**Comment by swankjesse** [comment] 2016-01-18 15:39
It’s not a behavior you can rely upon. It’s likely not failing as a side effect of how segments are being flushed, but this is definitely not a reliable fix.

**Comment by swankjesse** [comment] 2016-01-18 15:42
...In this case it looks like inconsistency in `MockWebServer.throttledTransfer()`. It throttles within each chunk, but not across chunks. This is a bad emulation of how throttled transferring will work in practice.

**Comment by MarkusMattinen** [comment] 2016-01-18 16:19
Yes, I did notice that behaviour with the throttling, which is why I have used 1000 or even 100 as the throttling interval. That should not be the difference here.

Why is flushing parts of the request an unreliable fix? It does not rely on any undefined socket/buffer behaviour, the timeout code that the hack bypasses is all in OkHttp.

When sink.write() is called a timer is added to the watchdog thread's handler, which then manually triggers a socket timeout if socket.write() blocks longer than the defined write timeout. Writing in two parts cancels the timer after the first part has been written into the socket (either on the wire or in a buffer) and restarts it when sink.write is called again. Writing in even more parts would make the timeout behave like I would expect it to. There could be some overhead from the timer being restarted too often, so unless it is possible to disable or fix the watchdog behaviour some other way a sensible write chunk size would be needed.

**Comment by MarkusMattinen** [comment] 2016-01-18 16:43
The relevant Okio code seems to be here:
https://github.com/square/okio/blob/master/okio/src/main/java/okio/AsyncTimeout.java#L155
The actual socket timeout exception that gets thrown is caused by this:
https://github.com/square/okio/blob/master/okio/src/main/java/okio/Okio.java#L221

**Comment by swankjesse** [comment] 2016-01-18 16:59
So the argument is that with a 1 second timeout, it’s dumb that we hold true to that 1 second, whether we’re writing 5 bytes or 5,000 ? I buy that.

**Comment by MarkusMattinen** [comment] 2016-01-18 17:01
That sounds like a deadline to me.

**Comment by MarkusMattinen** [comment] 2016-01-18 17:08
From Okio documentation (http://square.github.io/okio/1.x/okio/okio/Timeout.html):
Timeouts specify the maximum time to wait for a single operation to complete. Timeouts are typically used to detect problems like network partitions. For example, if a remote peer doesn't return any data for ten seconds, we may assume that the peer is unavailable.

**Comment by MarkusMattinen** [comment] 2016-01-18 17:15
I think that is also how pretty much all socket timeout settings behave, i.e. it gets triggered if not a single byte is received/written in the timeout period.

I suppose another solution could be having the ability to completely disable the Okio sink timeout and just relying on SO_TIMEOUT, which I should behave the way I described. But currently there is only a single write timeout setting that sets them both.

**Comment by swankjesse** [comment] 2016-01-18 17:26
Yeah, I like that idea.

**Comment by swankjesse** [comment] 2016-01-18 17:26
One problem is that there’s no built-in write timeout, only the built-in read timeout.

**Comment by MarkusMattinen** [comment] 2016-01-18 17:34
Ouch. You're right, there isn't.

So how about restarting the timeout every time a kilobyte or so has been written? That's practically the same thing, no?

**Comment by swankjesse** [comment] 2016-01-18 17:45
Yeah, I think that’s what we should do.

**Comment by namntse02942** [comment] 2016-02-02 10:32
That's the story 15 days ago.
Could you please let me know was that fixed now?

**Comment by MarkusMattinen** [comment] 2016-02-15 08:55
I'm currently using the following workaround with good results:

```java
public class OkHttpHelper {
    private static final int SOCKET_TIMEOUT_SECS = 15;

    // This should be less than the lowest "normal" upload bandwidth times SOCKET_TIMEOUT_SECS,
    // but not too low or upload speed with long fat networks will suffer.
    // Because it also affects the TCP window size it should preferably be a power of two.
    private static final int SEND_WINDOW_SIZE_BYTES = (int) Math.pow(2, 16); // 64 KiB

    //
    // OkHttp starts waiting for the response as soon as the last byte of the request body is either
    // in the socket buffer or on the wire. This results in a read timeout if the socket buffers
    // or the TCP window are large and the upload bandwidth is small.
    //
    // As a workaround this socket factory sets a smaller socket send buffer, effectively also
    // setting an upper limit for the TCP window size.
    //
    private static class CustomSocketFactory extends SocketFactory {
        private SocketFactory mDefaultSocketFactory;

        public CustomSocketFactory(SocketFactory defaultSocketFactory) {
            if (defaultSocketFactory == null) {
                mDefaultSocketFactory = SocketFactory.getDefault();
            } else {
                mDefaultSocketFactory = defaultSocketFactory;
            }
        }

        @Override
        public Socket createSocket(String host, int port) throws IOException {
            return setSocketOptions(mDefaultSocketFactory.createSocket(host, port));
        }

        @Override
        public Socket createSocket(String host, int port, InetAddress localHost, int localPort) throws IOException {
            return setSocketOptions(mDefaultSocketFactory.createSocket(host, port, localHost, localPort));
        }

        @Override
        public Socket createSocket(InetAddress host, int port) throws IOException {
            return setSocketOptions(mDefaultSocketFactory.createSocket(host, port));
        }

        @Override
        public Socket createSocket(InetAddress address, int port, InetAddress localAddress, int localPort) throws IOException {
            return setSocketOptions(mDefaultSocketFactory.createSocket(address, port, localAddress, localPort));
        }

        @Override
        public Socket createSocket() throws IOException {
            return setSocketOptions(mDefaultSocketFactory.createSocket());
        }

        private Socket setSocketOptions(Socket socket) throws SocketException {
            socket.setSendBufferSize(SEND_WINDOW_SIZE_BYTES);

            return socket;
        }
    }

    //
    // OkHttp writes the entire request body at once, triggering Okio's timeout mechanism if sending
    // the entire request takes longer than SOCKET_TIMEOUT_SECS seconds.
    //
    // As a workaround this interceptor writes the request body in parts,
    // resulting in Okio's timeout being applied separately for each part.
    //
    private static Interceptor sStreamingRequestInterceptor = new Interceptor() {
        @Override
        public com.squareup.okhttp.Response intercept(Chain chain) throws IOException {
            final Request originalRequest = chain.request();

            if (originalRequest.body() == null) {
                return chain.proceed(originalRequest);
            }

            final RequestBody originalBody = originalRequest.body();
            RequestBody streamingRequestBody = new RequestBody() {
                @Override
                public MediaType contentType() {
                    return originalBody.contentType();
                }

                @Override
                public long contentLength() throws IOException {
                    return originalBody.contentLength();
                }

                @Override
                public void writeTo(final BufferedSink sink) throws IOException {
                    Sink streamingSink = new ForwardingSink(sink) {
                        @Override
                        public void write(Buffer source, long byteCount) throws IOException {
                            long written = 0L;

                            while (written < byteCount) {
                                long writeLength = Math.min(SEND_WINDOW_SIZE_BYTES, byteCount - written);

                                sink.write(source.readByteArray(writeLength));
                                written += writeLength;
                            }
                        }
                    };

                    BufferedSink bufferedSink = Okio.buffer(streamingSink);
                    originalBody.writeTo(bufferedSink);
                    bufferedSink.emit();
                }
            };

            return chain.proceed(originalRequest.newBuilder()
                    .method(originalRequest.method(), streamingRequestBody)
                    .build());
        }
    };

    public static OkHttpClient createClient() {
        OkHttpClient okHttpClient = new OkHttpClient();
        okHttpClient.setReadTimeout(SOCKET_TIMEOUT_SECS, TimeUnit.SECONDS);
        okHttpClient.setWriteTimeout(SOCKET_TIMEOUT_SECS, TimeUnit.SECONDS);
        okHttpClient.setSocketFactory(new CustomSocketFactory(okHttpClient.getSocketFactory()));
        okHttpClient.networkInterceptors().add(sStreamingRequestInterceptor);

        return okHttpClient;
    }
}
```

**Comment by jianghaolu** [comment] 2016-03-18 19:21
Seeing a similar issue when uploading a 100mb file. Issue gone when Fiddler is turned on.
Stacktrace:
```
java.net.SocketTimeoutException: timeout
	at okio.Okio$3.newTimeoutException(Okio.java:212)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:288)
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:184)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
	at okio.RealBufferedSink.write(RealBufferedSink.java:41)
	at okhttp3.internal.http.Http1xStream$FixedLengthSink.write(Http1xStream.java:286)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
	at okio.RealBufferedSink.writeAll(RealBufferedSink.java:99)
	at okhttp3.RequestBody$3.writeTo(RequestBody.java:118)
	at retrofit2.RequestBuilder$ContentTypeOverridingRequestBody.writeTo(RequestBuilder.java:226)
	at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:704)
	at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:563)
	at okhttp3.RealCall.getResponse(RealCall.java:241)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
	at com.example.app.UserAgentInterceptor.intercept(UserAgentInterceptor.java:58)
```

**Comment by swankjesse** [comment] 2016-05-08 15:41
@jianghaolu looks like a legit timeout in your case.
@MarkusMattinen fixed in the new Okio, which is required by forthcoming OkHttp 3.3.

**Closed by swankjesse** 2016-05-08 15:41 UTC
Labels: bug

**Comment by rakshitsoni02** [comment] 2016-06-16 11:45
Gettin this error please give suggestion.
06-09 16:15:02.722 24776-24860/org.trakie.application W/System.err: javax.net.ssl.SSLException: Connection closed by peer
06-09 16:15:03.201 24776-24860/org.trakie.application W/System.err: at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
06-09 16:15:03.250 24776-24860/org.trakie.application W/System.err: at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:371)
06-09 16:15:03.280 24776-24860/org.trakie.application W/System.err: at okhttp3.internal.io.RealConnection.connectTls(RealConnection.java:195)
06-09 16:15:03.301 24776-24860/org.trakie.application W/System.err: at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:148)
06-09 16:15:03.380 24776-24860/org.trakie.application W/System.err: at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
06-09 16:15:03.420 24776-24860/org.trakie.application W/System.err: at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:188)
06-09 16:15:03.460 24776-24860/org.trakie.application W/System.err: at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
06-09 16:15:03.490 24776-24860/org.trakie.application W/System.err: at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
06-09 16:15:03.640 24776-24860/org.trakie.application W/System.err: at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
06-09 16:15:03.670 24776-24860/org.trakie.application W/System.err: at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
06-09 16:15:03.830 24776-24860/org.trakie.application W/System.err: at okhttp3.RealCall.getResponse(RealCall.java:240)
06-09 16:15:03.870 24776-24860/org.trakie.application W/System.err: at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
06-09 16:15:03.980 24776-24860/org.trakie.application W/System.err: at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
06-09 16:15:04.000 24776-24860/org.trakie.application W/System.err: at okhttp3.RealCall.execute(RealCall.java:57)
06-09 16:15:04.030 24776-24860/org.trakie.application W/System.err: at com.msg91.sendotp.library.internal.ApiService.getResponse(ApiService.java:102)
06-09 16:15:04.070 24776-24860/org.trakie.application W/System.err: at com.msg91.sendotp.library.internal.ApiService.verifyRequest(ApiService.java:61)
06-09 16:15:04.260 24776-24860/org.trakie.application W/System.err: at com.msg91.sendotp.library.internal.VerificationMethod$2.doInBackground(VerificationMethod.java:128)
06-09 16:15:04.270 24776-24860/org.trakie.application W/System.err: at com.msg91.sendotp.library.internal.VerificationMethod$2.doInBackground(VerificationMethod.java:123)
06-09 16:15:04.340 24776-24860/org.trakie.application W/System.err: at android.os.AsyncTask$2.call(AsyncTask.java:287)
06-09 16:15:04.400 24776-24860/org.trakie.application W/System.err: at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
06-09 16:15:04.480 24776-24860/org.trakie.application W/System.err: at java.util.concurrent.FutureTask.run(FutureTask.java:137)
06-09 16:15:04.550 24776-24860/org.trakie.application W/System.err: at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
06-09 16:15:04.610 24776-24860/org.trakie.application W/System.err: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
06-09 16:15:04.660 24776-24860/org.trakie.application W/System.err: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
06-09 16:15:04.770 24776-24860/org.trakie.application W/System.err: at java.lang.Thread.run(Thread.java:856)
06-09 16:15:04.860 24776-24776/org.trakie.application E/Verification: Verification failed: Request Unsuccessful Try Again

**Comment by asadwaheed1** [comment] 2017-12-06 11:04
I am also facing this issue on retrofit 2.3.0 when api call is timed out data is still being sent to server
