### ISSUE TITLE
Read timeout - Connection is not closed on post request

### ISSUE THREAD

**Issue by avo-nemo** [square/okhttp#6571] opened 2021-02-25 10:55 UTC
We had currently a problem with read timeouts on post requests on production.

**Client information**
Google Pixel 4XL
Android 11.0
Charles 4.5.5
OKHttp Version 4.9.1

The problem occurs on a variety of devices and os versions. I'm using retrofit - but I assume the problem is located in OKHttp.

**Steps to reproduce**
- Set timeout to 10 seconds or leave default timeout on client
- Setup Charles proxy
- Throttle bandwidth with Charles to a download of 0.1 kbps and the upload to 50000 kbps
- Send a post request with large body (around 7 MB)
- Wait until upload is done
- Wait defined timeout 

**Description**

After this steps the request in Charles has still the status "Waiting for response" and after around 1:39 minutes the request gets completed. The request in the android application is finished with an SocketTimeoutException timeout - a read timeout.

As the data is completely transmitted to the server and the client hasn't terminated the connection the backend cannot mark the request as failure and the uploaded data is processed although the client shows an error and the data is uploaded again, which leads to duplicates.

We tested the same behaviour on iOS and the request is finished after the timeout.

**Tried solutions**

- Response body cannot be closed because of the exception, but should be done internally
- Evict all connections in the connection pool
- Set retryOnConnectionFailure to false

**Workaround**

For now we implemented the workaround to increase the read timeout for this specific post request to 5 minutes, which should minimise the occurrences, but doesn't fix the problem.

Is there an option which I'm missing to force close the connection?

**Comment by swankjesse** [comment] 2021-02-25 12:05
I'm having trouble following this. What's the desired behavior? For OkHttp to not timeout even when a timeout is configured?

**Comment by swankjesse** [comment] 2021-02-25 12:08
Perhaps this will be fixed by closing the response after it fails with an exception. Typically we do this with a try block (Java) or use block (Kotlin).

**Comment by avo-nemo** [comment] 2021-02-25 14:00
Thanks for the quick answer.

Sorry if I didn't describe the problem good enough.

Of course OkHttp should timeout. That's not what I meant. The problem is that after the timeout the connection is not closed.

The upload of the data is completed. Now the server tries to send the response to the client to successfully end the request with HTTP Status 204. Because of the slow connection on the client side a timeout occurs, which is completely fine. The problem is that after OKHttp ends the request with a timeout and therefore the application stops listening for a response, the request is still ongoing and waits for the response until the request is completed. Because of that the server thinks that the request was completed successfully although the client got timed out.

Why is the connection not closed after receiving a timeout? 

Currently we use RXJava in combination with Retrofit and OkHttp. Which means the SocketTimeoutException is thrown and leads me in the error block and I don't have a access to the response object for closing it.

Can u please give me a hint how I should close the response after the exception?

**Comment by swankjesse** [comment] 2021-02-25 14:14
Can you configure a LoggingEventListener on your OkHttpClient?
https://square.github.io/okhttp/4.x/okhttp-logging-interceptor/okhttp3.logging/-logging-event-listener/

I’m curious to see if the connection is released.

**Comment by avo-nemo** [comment] 2021-02-25 17:12
With a read timeout of 30 seconds I get the following result:

[0 ms] callStart: Request{method=POST, ...}
... I/okhttp.OkHttpClient: [0 ms] proxySelectStart: ...
... I/okhttp.OkHttpClient: [1 ms] proxySelectEnd: [HTTP @ ...]
... I/okhttp.OkHttpClient: [1 ms] dnsStart: ...
... I/okhttp.OkHttpClient: [1 ms] dnsEnd: [/...]
... I/okhttp.OkHttpClient: [1 ms] connectStart: /... HTTP @ ...
... I/okhttp.OkHttpClient: [60 ms] secureConnectStart
... I/okhttp.OkHttpClient: [238 ms] secureConnectEnd: ...
... I/okhttp.OkHttpClient: [238 ms] connectEnd: http/1.1
... I/okhttp.OkHttpClient: [239 ms] connectionAcquired: Connection{...}
... I/okhttp.OkHttpClient: [239 ms] requestHeadersStart
... I/okhttp.OkHttpClient: [239 ms] requestHeadersEnd
... I/okhttp.OkHttpClient: [239 ms] requestBodyStart
... I/okhttp.OkHttpClient: [1046 ms] requestBodyEnd: byteCount=7024954
... I/okhttp.OkHttpClient: [31050 ms] responseFailed: java.net.SocketTimeoutException: timeout
... I/okhttp.OkHttpClient: [31051 ms] connectionReleased
... I/okhttp.OkHttpClient: [31051 ms] callFailed: java.net.SocketTimeoutException: timeout

This means the connection is released, but I can see that the request was successfully processed on backend side with a HTTP Status 204. If the request would have been cancelled and connection terminated the backend log would not have an entry as we saw after the iOS test. 

Do you have an idea what could trigger this behaviour? Could there be an issue with the proxy? 
I'm a little bit lost right now. Thanks for your efforts and your help in analysing the issue!

**Comment by yschimke** [comment] 2021-02-25 18:31
I don't think ultimately this is an issue for OkHttp to deal with.  You should consider including a unique request id in your POST and detect these and handle cleanly.  You may want to poll with a lightweight status request instead of resubmitting.  But HTTP semantics define POST as non-idempotent, so basically the app layer should handle this complexity.

**Comment by swankjesse** [comment] 2021-02-26 04:56
Looks like OkHttp doesn't receive even the headers of the response body. If you can reproduce this in a standalone test case, I'm interested.

**Comment by avo-nemo** [comment] 2021-02-26 12:02
Ok, thanks - I'll try to give you a standalone test case. I assume you want that the test case is somehow simulating the limitation of the bandwidth, am I right? 

Nevertheless this will take some time, since I have to do this out of office hours.

**Comment by gssandesh** [comment] 2021-02-26 12:36
Even I am facing the same issue. okhttp was working fine in my production system os patch updated now read timeouts exception occurs but curl request works fine

**Comment by yschimke** [comment] 2021-02-26 15:28
This last one is OkHttp 2

**Comment by yschimke** [comment] 2021-07-28 08:34
Going to close this unless we can get a reproducing test case.

**Closed by yschimke** 2021-07-28 08:34 UTC
Labels: bug, needs info
