### ISSUE TITLE
Kotlin dependencies alignment between OkHttp and Okio

### ISSUE THREAD

**Issue by sambishop** [square/okhttp#7500] opened 2022-11-02 16:19 UTC
OkHttp depends on Okio, and both have Kotlin stdlib dependencies.  But there's a mismatch between the stdlib versions that they depend on.

What I'm currently getting at runtime is a mix of versions.  (kotlin-stdlib version 1.4.10 and kotlin-stdlib-common version 1.4.0.)  That makes me wonder what version of those libraries were used in the OkHttp test pipeline.  I would be grateful if there were an alignment between OkHttp and Okio on the Kotlin stdlib version that they depend on, so it would be clear what to use at runtime.

**Comment by yschimke** [comment] 2022-11-02 17:39
Dupe of https://github.com/square/okhttp/issues/6184

Generally we try to keep them lined up, but different developers do the upgrade, so they can be temporarily out of alignment.  This is not considered to be an issue, in your app you can safely depend on the latest kotlin version.

**Closed by yschimke** 2022-11-02 17:39 UTC
Labels: enhancement

**Comment by JakeWharton** [comment] 2022-11-02 17:43
Also if you have 1.4.10 of the stdlib then it should have a dependency on 1.4.10 of the stdlib-common which your build system should select over a transitive dependency on 1.4.0 of the stdlib-common. Or perhaps those Kotlin versions are just too old? In the newer ones this is definitely what will happen.
