### ISSUE TITLE
Getting SocketTimeoutException a few seconds after websocket is opened.

### ISSUE THREAD

**Issue by arriolac** [square/okhttp#2294] opened 2016-01-29 00:06 UTC
Hi,

I'm getting a `SocketTimeoutException` right after a websocket has been connected (~10 seconds later). This wasn't happening in version 2.4.0. Stacktrace:

```
             System.err  W  java.net.SocketTimeoutException
                         W      at java.net.PlainSocketImpl.read(PlainSocketImpl.java:484)
                         W      at java.net.PlainSocketImpl.-wrap0(PlainSocketImpl.java)
                         W      at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
                         W      at okio.Okio$2.read(Okio.java:139)
                         W      at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
                         W      at okio.RealBufferedSource.request(RealBufferedSource.java:71)
                         W      at okio.RealBufferedSource.require(RealBufferedSource.java:64)
                         W      at okio.RealBufferedSource.readByte(RealBufferedSource.java:77)
                         W      at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:115)
                         W      at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:104)
                         W      at okhttp3.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
                         W      at okhttp3.ws.WebSocketCall.createWebSocket(WebSocketCall.java:152)
                         W      at okhttp3.ws.WebSocketCall.access$000(WebSocketCall.java:41)
                         W      at okhttp3.ws.WebSocketCall$1.onResponse(WebSocketCall.java:97)
                         W      at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
                         W      at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:33)
                         W      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                         W      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                         W      at java.lang.Thread.run(Thread.java:818)
```

Thanks,

Chris

**Comment by artem-zinnatullin** [comment] 2016-01-29 00:21
Try to increase read timeout `OkHttpClient.setReadTimeout()` (or via `OkHttpClient.Builder` for v3).

**Comment by JakeWharton** [comment] 2016-01-29 04:50
10 seconds is the default read timeout. You'll want to set the read timeout to 0 (aka forever). Dupe of #1930.

**Closed by JakeWharton** 2016-01-29 04:50 UTC
