### ISSUE TITLE
Http2Reader eats a lot of CPU for ~38 seconds

### ISSUE THREAD

**Issue by reda-alaoui** [square/okhttp#6525] opened 2021-01-24 12:51 UTC
Hi,

We are using:
- `retrofit` 2.9.0
- `okhttp` 3.14.9

When we use `retrofit` to perform an http request against an HTTP/2 server (tested with HAProxy and Nginx), `okhttp` starts a new non daemon thread running `Http2Connection$ReaderRunnable`. Despite the fact the http response is received almost immediately, the thread always run for ~38 seconds. 
During those 38 seconds, the thread is always active. All thread dumps show the thread performing a read operation:
```java
"OkHttp example.org" #4938 daemon prio=5 os_prio=0 tid=0x00007f3518348800 nid=0x1054e runnable [0x00007f3571bbc000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:990)
	- locked <0x00007f37f26725c0> (a java.lang.Object)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:948)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	- locked <0x00007f37f26725d0> (a sun.security.ssl.AppInputStream)
	at okio.Okio$2.read(Okio.java:140)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at okio.RealBufferedSource.request(RealBufferedSource.java:72)
	at okio.RealBufferedSource.require(RealBufferedSource.java:65)
	at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.java:96)
	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.execute(Http2Connection.java:668)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
```

The CPU profiling shows that during those 38 seconds, the thread is constantly eating CPU resource.

Having multiple feign instances each relying on their own okhttp instances, we end up with a dozen of threads continuously eating CPU.

Our workaround is to force okhttp to always use HTTP/1.1.

**Comment by yschimke** [comment] 2021-01-24 12:57
Can you turn on HTTP/2 frame logging to see what is being received?

https://square.github.io/okhttp/debug_logging/#http2-frame-logging

Potentially it might show up with event listeners, https://square.github.io/okhttp/events/, but there is some frame traffic that might only show up at that level.

**Comment by reda-alaoui** [comment] 2021-01-24 13:11
Hi @yschimke ,

I enabled HTTP/2 frame while performing `GET https://api.github.com/repos/square/okhttp/issues`:
```
[2021-01-24 14:08:46] >> CONNECTION 505249202a20485454502f322e300d0a0d0a534d0d0a0d0a 
[2021-01-24 14:08:46] >> 0x00000000     6 SETTINGS       
[2021-01-24 14:08:46] >> 0x00000000     4 WINDOW_UPDATE  
[2021-01-24 14:08:46] >> 0x00000003    52 HEADERS       END_STREAM|END_HEADERS 
[2021-01-24 14:08:46] << 0x00000000    12 SETTINGS       
[2021-01-24 14:08:46] << 0x00000000     0 SETTINGS      ACK 
[2021-01-24 14:08:46] >> 0x00000000     0 SETTINGS      ACK 
[2021-01-24 14:08:46] << 0x00000003  1135 HEADERS       END_HEADERS 
[2021-01-24 14:08:46] << 0x00000003  1364 DATA           
[2021-01-24 14:08:46] >> 0x00000003     4 RST_STREAM     
[2021-01-24 14:10:47] << 0x00000000     8 GOAWAY 
```
It is worse than I tought. The thread was active for 2 minutes.

**Comment by reda-alaoui** [comment] 2021-01-24 13:13
Here is the test:

```java
package com.cos.retrofit;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.util.stream.Stream;
import okhttp3.OkHttpDebugLogging;
import org.junit.Test;
import retrofit2.Call;
import retrofit2.Retrofit;
import retrofit2.http.GET;

public class FooTest {

  @Test
  public void test() throws IOException, InterruptedException {
    OkHttpDebugLogging.INSTANCE.enableHttp2();

    FooApi api =
        new Retrofit.Builder().baseUrl("https://api.github.com/").build().create(FooApi.class);

    assertThat(api.fetch().execute().isSuccessful()).isTrue();

    Thread[] threads = new Thread[50];
    Thread.enumerate(threads);

    Thread connectionThread =
        Stream.of(threads)
            .filter(thread -> thread.getName().equals("OkHttp api.github.com"))
            .findFirst()
            .orElseThrow(RuntimeException::new);

    connectionThread.join();
  }

  private interface FooApi {

    @GET("repos/square/okhttp/issues")
    Call<Void> fetch();
  }
}

```

**Comment by yschimke** [comment] 2021-01-24 13:22
This is sounding normal to be honest, it's just doing a blocking read.  The thread is a daemon thread, and it's waiting for additional bytes.

How are you measuring "the thread is constantly eating CPU resource", are you actually seeing CPU activity slowing down other processes?

At this point, I suggest asking on stackoverflow and discussing there.  It doesn't look like anything is wrong or wasting CPU from what you have shown.  Closing for now, as there isn't a bug to fix here.

**Comment by reda-alaoui** [comment] 2021-01-24 13:26
> How are you measuring "the thread is constantly eating CPU resource", are you actually seeing CPU activity slowing down other processes?

This is what VisualVM profiler shows:

![Screenshot from 2021-01-24 14-23-40](https://user-images.githubusercontent.com/2890843/105631671-db52dc00-5e4f-11eb-94da-f2902b302040.png)

![Screenshot from 2021-01-24 14-24-53](https://user-images.githubusercontent.com/2890843/105631683-f4f42380-5e4f-11eb-96de-79b5bda24b36.png)

So I conclude that from the JVM point of view, the thread is never idle. Therefore I came to the conclusion "the thread is constantly eating CPU resource".
Do you think my interpretation of the profiling is incorrect?

**Comment by reda-alaoui** [comment] 2021-01-24 13:28
Here is a counter example of a thread consuming zero CPU resource during the time window of the profiling:

![Screenshot from 2021-01-24 14-27-41](https://user-images.githubusercontent.com/2890843/105631771-67fd9a00-5e50-11eb-8eaf-90761bd60621.png)

**Comment by swankjesse** [comment] 2021-01-24 13:51
It looks like badly-behaved TLS to me. Do you get this behavior with any HTTPS server or just a partial one? Any idea which TLS implementation you're talking to? My best guess looking at these traces is the SSL server is sending empty or very small frames and the reader is saturated processing it.

**Comment by swankjesse** [comment] 2021-01-24 13:57
It'd also be useful to see CPU usage within `AppInputStream`. Your initial trace shows deeper stacks there but your visual VM screenshots don't.

Also also might be worth an experiment to use Conscrypt instead of Java’s built in TLS to see what the performance consequence is.

**Comment by yschimke** [comment] 2021-01-24 14:08
> It looks like badly-behaved TLS to me. Do you get this behavior with any HTTPS server or just a particular one? Any idea which TLS implementation you're talking to? My best guess looking at these traces is the SSL server is sending empty or very small frames and the reader is saturated processing it.

TCP/SSL frames? HTTP/2 frames don't show this.  But Wireshark packet capture could help confirm this. If you want to go down this rabbithole, this is a starting point https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/kt/WiresharkExample.kt

**Comment by yschimke** [comment] 2021-01-24 14:34
I adapted that program above to remove retrofit, but it doesn't show excessive CPU usage.  Just blocking IO operations.

```
JDK 15 

"OkHttp api.github.com@2656" daemon prio=5 tid=0x1a nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at sun.nio.ch.Net.poll(Net.java:-1)
	  at sun.nio.ch.NioSocketImpl.park(NioSocketImpl.java:181)
	  at sun.nio.ch.NioSocketImpl.park(NioSocketImpl.java:190)
	  at sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:314)
	  at sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
	  at sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
	  at java.net.Socket$SocketInputStream.read(Socket.java:981)
	  at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
	  at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	  at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
	  at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1434)
	  at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1038)
	  at okio.InputStreamSource.read(JvmOkio.kt:91)
	  at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
	  at okio.RealBufferedSource.request(RealBufferedSource.kt:60)
	  at okio.RealBufferedSource.require(RealBufferedSource.kt:53)
	  at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:89)
```

openjdk 11

```
"OkHttp api.github.com@2438" daemon prio=5 tid=0x19 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.net.SocketInputStream.socketRead0(SocketInputStream.java:-1)
	  at java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	  at java.net.SocketInputStream.read(SocketInputStream.java:168)
	  at java.net.SocketInputStream.read(SocketInputStream.java:140)
	  at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:476)
	  at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:470)
	  at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
	  at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1354)
	  at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:963)
	  at okio.InputStreamSource.read(JvmOkio.kt:91)
	  at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
	  at okio.RealBufferedSource.request(RealBufferedSource.kt:60)
	  at okio.RealBufferedSource.require(RealBufferedSource.kt:53)
	  at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:89)	  
```

**Comment by yschimke** [comment] 2021-01-24 14:58
From the stacktrace, I assume you are on JDK 8 or 7?  +1 to trying Conscrypt or OpenJSSE and seeing if you get the same problem.

Closest I found with quick googling being https://lists.jboss.org/pipermail/aerogear-users/2016-September/000918.html

But honestly I can't reproduce easily here.

One way to see if it's bouncing around in OkHttp vs JVM read code is with breakpoints just printing out rather than suspending.  The snapshot of a stacktrace doesn't make it clear to us where the loop is happening if it's the same code path everytime.

![image](https://user-images.githubusercontent.com/231923/105634146-9a10fb00-5e54-11eb-9d1e-cb484347c181.png)

```
Breakpoint reached at okio.InputStreamSource.read(JvmOkio.kt:91)
Breakpoint reached at okio.InputStreamSource.read(JvmOkio.kt:91)
Breakpoint reached at okio.InputStreamSource.read(JvmOkio.kt:91)
```

**Comment by reda-alaoui** [comment] 2021-01-24 15:03
Our production is running on OpenJDK 8.
My local tests are running on OpenJDK 11.

I am trying to see if VisualVM can be trusted about CPU consumption. Because, with the test I posted earlier (against github.com), VisualVM is telling me that `OkHttp api.github.com` is never idle.

**Comment by yschimke** [comment] 2021-01-24 15:17
Some discussion here http://www.brendangregg.com/blog/2014-06-09/java-cpu-sampling-using-hprof.html.  It isn't going to ever be idle.  It's mainly whether there is a long blocking call (correct) or a tight loop somewhere (broken).

But unless you can show it's bouncing around in OkHttp code then you should probably raise a bug with Oracle if inside the SSL code using real CPU.

Closing for now, not much we can do to help you on this without further evidence that it's actually a bug in OkHttp.

Personally, I'm glad the debugging and events at different layers can help you dig into what's going on.  So this was interesting, but not going to investigate further.

**Closed by yschimke** 2021-01-24 15:17 UTC
Labels: bug

**Comment by reda-alaoui** [comment] 2021-01-24 15:20
Ok. Thank you very much @yschimke , @swankjesse :)
I'll keep investigating

**Comment by reda-alaoui** [comment] 2021-01-25 09:39
In the end, the issue comes from misinterpretation of VisualVM.
There is a second panel named "Thread CPU time" which is more reliable:

![Screenshot from 2021-01-25 10-37-45](https://user-images.githubusercontent.com/2890843/105687991-620fc380-5ef9-11eb-9be3-c536d0c493fe.png)

We can see that the thread is mostly idle.

YourKit corroborated the results.

Thanks again for your help, and kudos for this wonderful library !

**Comment by yschimke** [comment] 2021-01-25 09:42
As an open source maintainer, these sorts of discussions are useful and interesting if they are engaged and we are drilling through to a solution and understanding of the problem. Others will experience the same thing.

Thanks for drilling through to a complete solution in a day.
