### ISSUE TITLE
java.net.ProxySelector.connectFailed do not ever been called

### ISSUE THREAD

**Issue by TimDunk** [square/okhttp#7696] opened 2023-02-16 12:06 UTC
In Java11;

When the version of OkHttp is 4.X  :

OkHttpClient.Builder adds a proxySelector,   when the proxy server refuses the connection, _java.net.ProxySelector.connectFailed_ method has not been called. I suppose it is a bug.

When the version of OkHttp is 3.X  :  
it works well.

**Comment by yschimke** [comment] 2023-02-16 18:46
Yep, think I can confirm this with the last line of this test. This is against 4.x. 

I'll test against 5.x and fix and then backport.

```
  @Test public void connectTimeoutsAttemptsAlternateRoute() throws Exception {
    RecordingProxySelector proxySelector = new RecordingProxySelector();
    proxySelector.proxies.add(new Proxy(Proxy.Type.HTTP, TestUtil.UNREACHABLE_ADDRESS));
    proxySelector.proxies.add(server.toProxyAddress());

    server.enqueue(new MockResponse()
        .setBody("success!"));
    client = client.newBuilder()
        .proxySelector(proxySelector)
        .readTimeout(Duration.ofMillis(100))
        .connectTimeout(Duration.ofMillis(100))
        .build();

    Request request = new Request.Builder().url("http://android.com/").build();
    executeSynchronously(request)
        .assertCode(200)
        .assertBody("success!");

    assertThat(proxySelector.failures).isNotEmpty();
  }
```

**Comment by yschimke** [comment] 2023-02-17 19:33
I suspect these are related https://github.com/square/okhttp/issues/7553

```
  /** Track a bad route in the route database. Other routes will be attempted first. */
  internal fun connectFailed(client: OkHttpClient, failedRoute: Route, failure: IOException) {
    // Tell the proxy selector when we fail to connect on a fresh connection.
    if (failedRoute.proxy.type() != Proxy.Type.DIRECT) {
      val address = failedRoute.address
      address.proxySelector.connectFailed(
        address.url.toUri(), failedRoute.proxy.address(), failure
      )
    }

    client.routeDatabase.failed(failedRoute)
  }
```

**Comment by yschimke** [comment] 2023-05-21 09:26
Dupe of https://github.com/square/okhttp/issues/7553

**Closed by yschimke** 2023-05-21 09:26 UTC
Labels: bug
