### ISSUE TITLE
Don't leave callbacks hanging when interceptors throw unchecked exceptions

### ISSUE THREAD

**Issue by marshallpierce** [square/okhttp#5281] opened 2019-07-11 17:51 UTC
Currently, `Callback#onFailure` has an `IOException` param, and is only called when the interceptor chain throws an `IOException`. This means that when an unchecked exception is thrown, it bubbles up to the worker thread, and nothing happens with the callback.

This isn't unknown (see #1482 and others), but here's a self-contained repro anyway: https://bitbucket.org/marshallpierce/okhttp-interceptor-repro/src/master/

https://github.com/square/okhttp/issues/1482#issuecomment-78042597 indicates that this is intentional:

> For async, we shouldn't call onFailure with the unchecked exception; that method is for I/O failures only. Instead we're better off crashing to the worker thread's uncaught exception handler.

However, unchecked exceptions happen in practice, and either way I claim "don't leave callbacks permanently stuck in neither success or failure" is axiomatically a Good Thing.

- Unchecked exceptions are unavoidable in practice. Any nontrivial code may throw them.
- I think the above comment is incorrect, and that killing the worker basically does nobody any good. Now another thread has to be started, and the responsible code will never be notified.
- It's effectively impossible to build reliable code on top of Callback because of this. Retrofit, for instance, produces `CompletableFuture`s that never complete when this happens, which is clearly bad, and there's no way for it to do any better, either, because `Callback` won't let it.

[Async Http Client](https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/AsyncHandler.java#L107) has the right idea, as does the [client](https://docs.oracle.com/en/java/javase/11/docs/api/java.net.http/java/net/http/HttpClient.html#sendAsync(java.net.http.HttpRequest,java.net.http.HttpResponse.BodyHandler)) recently added to the JDK.

Changing the signature of `onFailure` would be a breaking change, so that'll presumably have to wait, but in the meantime it looks like a pragmatic solution would be to wrap throwables in `IOException` so they may be provided to that method. Perhaps a `WrapperIOException` class could be used for just this purpose so that callbacks who care to differentiate could tell the difference between an "unchecked-as-ioexception" and the usual breed.

**Comment by JakeWharton** [comment] 2019-07-11 18:01
Dupe of #5151. You can find the plan to remedy this in there.

**Closed by JakeWharton** 2019-07-11 18:01 UTC
Labels: bug
