### ISSUE TITLE
java.lang.NullPointerException: ssl_session == null

### ISSUE THREAD

**Issue by MichaelChansn** [square/okhttp#3529] opened 2017-08-17 03:48 UTC
I have the same issue...

java.lang.NullPointerException: ssl_session == null

at com.android.org.conscrypt.NativeCrypto.SSL_SESSION_cipher(Native Method)
at com.android.org.conscrypt.OpenSSLSessionImpl.getCipherSuite(OpenSSLSessionImpl.java:320)
at okhttp3.Handshake.get(SourceFile:49)
at okhttp3.internal.io.RealConnection.connectTls(SourceFile:196)
at okhttp3.internal.io.RealConnection.connectSocket(SourceFile:148)
at okhttp3.internal.io.RealConnection.connect(SourceFile:111)
at okhttp3.internal.http.StreamAllocation.findConnection(SourceFile:188)
at okhttp3.internal.http.StreamAllocation.findHealthyConnection(SourceFile:127)
at okhttp3.internal.http.StreamAllocation.newStream(SourceFile:97)
at okhttp3.internal.http.HttpEngine.connect(SourceFile:289)
at okhttp3.internal.http.HttpEngine.sendRequest(SourceFile:241)
at okhttp3.RealCall.getResponse(SourceFile:240)
at okhttp3.RealCall$ApplicationInterceptorChain.proceed(SourceFile:198)
at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:160)
at okhttp3.RealCall.access$100(SourceFile:30)
at okhttp3.RealCall$AsyncCall.execute(SourceFile:127)
at okhttp3.internal.NamedRunnable.run(SourceFile:32)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)

OKhttp version: 3.2.0
android version : 6.0
android model ： Meizu M5

crashed at external/conscrypt/src/main/native/org_conscrypt_NativeCrypto.cpp

- static SSL_SESSION* to_SSL_SESSION(JNIEnv* env, jlong ssl_session_address, bool throwIfNull) {
- SSL_SESSION* ssl_session
- = reinterpret_cast<SSL_SESSION*>(static_cast<uintptr_t>(ssl_session_address));
- if ((ssl_session == NULL) && throwIfNull) {
- JNI_TRACE("ssl_session == null");
- jniThrowNullPointerException(env, "ssl_session == null");
- }
- return ssl_session;
- }

just don't know why, and i can not reproduce.
274 times crash in 4.6 million devices

**Comment by JakeWharton** [comment] 2017-08-17 04:01
Dupe of #3301. No action for OkHttp to take.

**Closed by JakeWharton** 2017-08-17 04:01 UTC
