### ISSUE TITLE
java.lang.NullPointerException: ssl == null

### ISSUE THREAD

**Issue by 2862339302** [square/okhttp#4260] opened 2018-09-11 10:10 UTC
com.squareup.okhttp3:okhttp:3.11.0

java.lang.NullPointerException: ssl == null
	at com.android.org.conscrypt.NativeCrypto.SSL_read(NativeCrypto.java)
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:758)
	at okio.Okio$2.read(Okio.java:140)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at okio.RealBufferedSource.request(RealBufferedSource.java:68)
	at okio.RealBufferedSource.require(RealBufferedSource.java:61)
	at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.java:95)
	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.execute(Http2Connection.java:609)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.lang.Thread.run(Thread.java:761)

**Comment by swankjesse** [comment] 2018-09-11 11:51
Can you please report this to the Conscrypt project with information about the OS release? This crash is not caused by OkHttp, but the OS itself.

https://github.com/google/conscrypt

**Comment by 2862339302** [comment] 2018-09-12 01:38
OK,thanks.

**Comment by RobertRzepniewski** [comment] 2020-01-23 18:58
Hi @swankjesse 

Is there any workaround/hack to catch this exception?
I've added an interceptor that catches all exceptions but it hasn't caught it.
Would it make sense to manually add the Conscrypt library to possibly avoid such exception?

Cheers,
Rob

**Comment by swankjesse** [comment] 2020-01-23 19:18
@RobertRzepniewski we added a workaround in the latest release (4.3.1)
https://github.com/square/okhttp/issues/5587

**Comment by RobertRzepniewski** [comment] 2020-01-23 21:39
That's great, thanks @swankjesse 👍

**Comment by RobertRzepniewski** [comment] 2020-01-29 09:28
Hi @swankjesse 

I've updated to 4.3.1 but still receive the following. The core issue seems really similar:

```
Fatal Exception: java.lang.NullPointerException: ssl == null
       at com.android.org.conscrypt.NativeCrypto.SSL_write(NativeCrypto.java)
       at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:807)
       at okio.OutputStreamSink.write(OutputStreamSink.java:56)
       at okio.AsyncTimeout$sink$1.write(AsyncTimeout.java:103)
       at okio.internal.RealBufferedSinkKt.commonFlush(RealBufferedSinkKt.java:183)
       at okio.RealBufferedSink.flush(RealBufferedSink.java:247)
       at okhttp3.internal.http2.Http2Writer.goAway(Http2Writer.java:233)
       at okhttp3.internal.http2.Http2Connection.shutdown(Http2Connection.java:428)
       at okhttp3.internal.http2.Http2Connection.close$okhttp(Http2Connection.java:448)
       at okhttp3.internal.http2.Http2Connection$ReaderRunnable.run(Http2Connection.java:623)
       at java.lang.Thread.run(Thread.java:764)
```

I get these on Android 7.0, 7.1.1 & 8.0.0.
Not really sure how to replicate that.

Thanks,
Rob

**Comment by swankjesse** [comment] 2020-01-29 12:07
This stacktace is from OkHttp 3.x.

**Comment by RobertRzepniewski** [comment] 2020-01-29 12:15
@swankjesse this is the dependency I use: ```com.squareup.okhttp3:okhttp:4.3.1```

**Comment by swankjesse** [comment] 2020-01-29 12:33
Something isn’t right. The stacktrace has .java files in it, but since 4.0.0 OkHttp classes should have .kt files.

**Comment by RobertRzepniewski** [comment] 2020-01-29 12:45
I've been on OkHttp 4+ since August. It somehow must be how these crashes are reported. I can also see .java extension for crashes coming from my own .kt files. 
I use Fabric and this coud be why:
> We assume a .java extension by default, but we'll be looking to improve this experience for Kotlin in the future.

https://stackoverflow.com/questions/57518909/why-do-kotlin-files-appear-as-java-is-fabric-crashlytics-with-proguard-enabled

**Comment by RobertRzepniewski** [comment] 2020-01-29 13:21
I have a custom interceptor that I add to `OkHttpClient.Builder` but it won't catch this error. Is there some other workaround? I execute requests synchronously with `call.execute()`and ideally would be able to catch this failure.

**Comment by swankjesse** [comment] 2020-01-29 15:05
Ahh, okay that’s good to know. Let’s try to fix!

**Comment by hszlangbaum** [comment] 2020-01-29 15:26
Brill! 👍

**Comment by yschimke** [comment] 2020-04-01 19:25
@swankjesse Is there a better fix for these types of issues than patching individual sites? The previous fix was a TLS handshake issue, so it was on our turf.  https://github.com/square/okhttp/pull/5590/files

I wonder whether we need some way to wrap Okio Sink and Source with exception translating wrappers?  and on Android only apply some known wrappers as we detect them?

```
return sink.wrapExceptions {
  when {
    e is NullPointerException && e.message == "ssl == null" -> throw IOException(e) 
  }
}
```

**Comment by swankjesse** [comment] 2020-04-01 19:45
I think we probably want to handle the above case in Okio?

**Comment by yschimke** [comment] 2020-04-01 19:51
Always? Or in some exception safe source and sink wrappers?

**Comment by swankjesse** [comment] 2020-04-02 11:43
Might be able to do it in the common InputStream or Socket adapters. (Is there any performance cost of an unused try/catch block?)

**Comment by EddieMeng** [comment] 2020-08-10 03:59
Fatal Exception: java.lang.NullPointerException
ssl == null
com.android.org.conscrypt.NativeCrypto.SSL_write (NativeCrypto.java)
com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write (OpenSSLSocketImpl.java:807)
okio.OutputStreamSink.write (Okio.kt:6)
okio.AsyncTimeout$sink$1.write (AsyncTimeout.kt:6)
okio.RealBufferedSink.flush (RealBufferedSink.kt:6)
okhttp3.internal.http2.Http2Writer.goAway (Http2Writer.kt:9)
okhttp3.internal.http2.Http2Connection.shutdown (Http2Connection.kt:9)
okhttp3.internal.http2.Http2Connection.close$okhttp (Http2Connection.kt:2)
okhttp3.internal.http2.Http2Connection$ReaderRunnable.run (Http2Connection.kt:8)

We have this issue also,  please inform me once your guys fixed the bug @swankjesse

**Comment by yschimke** [comment] 2020-08-10 07:13
@EddieMeng I suggest you follow along here, I don't think we take requests for personal notifications.

The bug is in AOSP if it's badly affecting you, you can look at adopting the Play provider or conscrypt-android

https://developer.android.com/training/articles/security-gms-provider.html

**Comment by chihung93** [comment] 2020-09-04 08:36
I have problem to upload large file 2.2GB

```
 javax.net.ssl.SSLException: Write error: ssl=0x79da6cfec8: I/O error during system call, Broken pipe
        at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)
        at com.android.org.conscrypt.NativeSsl.write(NativeSsl.java:426)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLOutputStream.write(ConscryptFileDescriptorSocket.java:660)
        at okio.OutputStreamSink.write(JvmOkio.kt:53)
        at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:103)
        at okio.RealBufferedSink.flush(RealBufferedSink.kt:247)
        at okhttp3.internal.http1.Http1ExchangeCodec$KnownLengthSink.flush(Http1ExchangeCodec.kt:276)
        at okio.ForwardingSink.flush(ForwardingSink.kt:32)
        at okhttp3.internal.connection.Exchange$RequestBodySink.flush(Exchange.kt:228)
        at okio.RealBufferedSink.flush(RealBufferedSink.kt:250)
        at net.gotev.uploadservice.okhttp.OkHttpBodyWriter.flush(OkHttpBodyWriter.kt:25)
        at net.gotev.uploadservice.network.BodyWriter.write(BodyWriter.kt:67)
        at net.gotev.uploadservice.network.BodyWriter.writeStream(BodyWriter.kt:42)
        at net.gotev.uploadservice.protocols.binary.BinaryUploadTask.onWriteRequestBody(BinaryUploadTask.kt:16)
        at net.gotev.uploadservice.okhttp.OkHttpStackRequest$createBody$1.writeTo(OkHttpStackRequest.kt:76)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at net.gotev.uploadservicedemo.App.lambda$getOkHttpClient$2(App.java:121)
        at net.gotev.uploadservicedemo.-$$Lambda$App$_LWmqaXNeIhbCyckILMOrbvcMgA.intercept(Unknown Source:0)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at net.gotev.uploadservicedemo.App.lambda$getOkHttpClient$1(App.java:110)
        at net.gotev.uploadservicedemo.-$$Lambda$App$i1SOtWVwIE4ECfByutde1MWQaGw.intercept(Unknown Source:0)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at net.gotev.uploadservice.okhttp.OkHttpStackRequest.getResponse(OkHttpStackRequest.kt:95)
        at net.gotev.uploadservice.HttpUploadTask.upload(HttpUploadTask.kt:49)
        at net.gotev.uploadservice.UploadTask.run(UploadTask.kt:140)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
    	Suppressed: java.net.ProtocolException: unexpected end of stream
        at okhttp3.internal.connection.Exchange$RequestBodySink.close(Exchange.kt:239)
        at okio.RealBufferedSink.close(RealBufferedSink.kt:268)
        at net.gotev.uploadservice.okhttp.OkHttpBodyWriter.close(OkHttpBodyWriter.kt:30)
        at kotlin.io.CloseableKt.closeFinally(Closeable.kt:60)
        at net.gotev.uploadservice.okhttp.OkHttpStackRequest$createBody$1.writeTo(OkHttpStackRequest.kt:75)
```

**Comment by yschimke** [comment] 2020-10-31 12:58
Closing this out for OkHttp.  Upstream fix is in, but likely to keep happening on devices forever.  And the remaining fix would be in okio, not here.

**Closed by yschimke** 2020-10-31 12:58 UTC
Labels: android, bug
