### ISSUE TITLE
IndexOutOfBoundsException in RealConnection

### ISSUE THREAD

**Issue by jaydenyu93** [square/okhttp#4208] opened 2018-08-13 12:06 UTC
got following crash in google pixel xl device with android p using okhttp3.11
Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 0
       at java.util.Collections$EmptyList.get(Collections.java:4502)
       at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:325)
       at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:282)
       at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:167)
       at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
       at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)

**Comment by yschimke** [comment] 2018-08-13 15:52
Seems like a real bug triggered by an unfortunate (bad?) server setup.

```
  /** Returns a possibly-empty list of certificates that identify the remote peer. */
  public List<Certificate> peerCertificates() {
    return peerCertificates;
  }
```

```
      // Verify that the socket's certificates are acceptable for the target host.
      if (!address.hostnameVerifier().verify(address.url().host(), sslSocketSession)) {
        X509Certificate cert = (X509Certificate) unverifiedHandshake.peerCertificates().get(0);
```

**Comment by yschimke** [comment] 2018-09-03 05:58
Still an issue, but relevant comment

https://github.com/square/okhttp/pull/4236#discussion_r212837638

**Comment by swankjesse** [comment] 2018-11-04 05:15
Closing this; will handle pre-shared keys in the other issue.

**Closed by swankjesse** 2018-11-04 05:15 UTC
Labels: bug

**Comment by hatzlj** [comment] 2020-05-07 13:52
In case someone else stumbles across this exception, we had the same Exception occuring and had a hard time finding a solution - altough the issue is closed and we we weren't able to track down the actual problem it's worth sharing at least our findings: the situation in the code described above seems to occur in our case with a constellation having okhttp running on openjdk-11.0.1 after updating the apache2 the okhttp library tries to connect to (in our case it was used in the sonar-maven-plugin).

We were able to reproduce the behaviour constantly on openjdk-11.0.1 and openjdk-11.0.2+9 and it seems to be gone from openjdk-11.0.3 (mabe even openjdk-11.0.2+31 or openjdk-11.0.2+32 - had no chance to test this).
Checking the [JDK 11 complete release notes](https://www.oracle.com/technetwork/java/javase/11all-relnotes-5013287.html) we can see that there has been some changes related to TLS and cipher suites in openjdk-11.0.2+31 and 11.0.3+12 so we assume that this is the core problem here.
