### ISSUE TITLE
Can't use okhttp combine with otto?

### ISSUE THREAD

**Issue by jompon** [square/okhttp#2046] opened 2015-11-28 09:19 UTC
My Gradle
compile 'com.squareup.okhttp:okhttp:2.6.0'
compile 'com.squareup:otto:1.3.8'

```java
public final class BusProvider {
  private static final Bus BUS = new Bus(); <--------Error on this line

  public static Bus getInstance() {
    return BUS;
  }

  private BusProvider() {
    // No instances.
  }
}
```
>java.lang.NoClassDefFoundError: com.squareup.otto.ThreadEnforcer

**Comment by JakeWharton** [comment] 2015-11-29 02:14
Dupe of https://github.com/square/otto/issues/177

**Closed by JakeWharton** 2015-11-29 02:14 UTC
