### ISSUE TITLE
Sometime may block

### ISSUE THREAD

**Issue by ygonzalez1** [square/okhttp#7687] opened 2023-02-07 16:59 UTC
Hi, I have the same issue using Java 8 with a Feign client. I've been able to reproduce the issue using a few threads.  

This is my feign config.

    compile('org.springframework.cloud:spring-cloud-starter-openfeign')
    compile group: 'io.github.openfeign', name: 'feign-okhttp', version: '10.2.0'

![image](https://user-images.githubusercontent.com/38919089/217269262-77ba4d9c-5b27-4e43-a3cb-94673e069165.png)

I created a loop to make 100k calls to the same service through each thread.
![image](https://user-images.githubusercontent.com/38919089/217269699-7f42a6b5-96a8-4b00-8f05-72b6199c92d5.png)

out of 10 threads that were working only 3 are working (thread-2, thread-9, thread-10)
![image](https://user-images.githubusercontent.com/38919089/217271155-85611db6-c19b-468e-9039-4436b4da6311.png)

Using VisualVM, I was able to see that the threads were waiting forever.
![image](https://user-images.githubusercontent.com/38919089/217273223-a799875f-e26d-4a11-85d7-1fa3d5069920.png)
![image](https://user-images.githubusercontent.com/38919089/217273527-73f9c27c-a1f9-4779-919a-24d5a98d2f1c.png)
![image](https://user-images.githubusercontent.com/38919089/217273673-7227d76b-fc4a-42c9-845a-fe93f5eda96b.png)

In the end all the threads are left waiting and the process in general stops working properly.

Could someone fix it?

**Comment by ygonzalez1** [comment] 2023-02-07 17:00
Related with https://github.com/square/okhttp/issues/4241

**Comment by yschimke** [comment] 2023-02-18 14:50
It's the same answer as #4241 We'll need a reproduction.  It's quite possible this is happening, because you have multiple requests over a single Http/2 connection, and your own code is not fully processing all responses or cancelling them.

If you can make a standalone reproduction, I'm happy to investigate.

**Comment by yschimke** [comment] 2023-03-04 12:15
Closing as a dupe of https://github.com/square/okhttp/issues/4241

Need a clean repro to proceed

**Closed by yschimke** 2023-03-04 12:15 UTC
Labels: bug, needs info
