### ISSUE TITLE
IllegalStateException: closed : HttpLoggingInterceptor.kt:248

### ISSUE THREAD

**Issue by pankajtalaviya97** [square/okhttp#8307] opened 2024-03-28 04:52 UTC
getting below exception and crashed my app

Fatal Exception: java.lang.IllegalStateException
closed
okio.RealBufferedSource.request (RealBufferedSource.kt:206)
okhttp3.logging.HttpLoggingInterceptor.intercept (**_HttpLoggingInterceptor.kt:248_**)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp (RealCall.kt:201)
okhttp3.internal.connection.RealCall$AsyncCall.run (RealCall.kt:517)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1145)

**Comment by yschimke** [comment] 2024-03-28 07:50
Dupe of https://github.com/square/okhttp/issues/5783 and https://github.com/square/okhttp/issues/6106

> I don’t think this is an OkHttp bug. If you close a stream and then attempt to read it, that’s an IllegalStateException. My expectation here is some other interceptor is closing the response body.

Please provide a repro, or ask on a site like stackoverflow.

**Closed by yschimke** 2024-03-28 07:50 UTC
Labels: bug
