### ISSUE TITLE
java.io.EOFException: \n not found: size=0 content=…

### ISSUE THREAD

**Issue by icecooly** [square/okhttp#2849] opened 2016-09-13 04:29 UTC
What kind of issue is this?
 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

Caused by: java.io.IOException: unexpected end of stream on okhttp3.Address@be2b615b
        at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:201) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:53) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.RealCall.execute(RealCall.java:60) ~[BmqBizSystem.jaz:build201609122239]
        at io.itit.itf.okhttp.RequestCall.execute(RequestCall.java:131) ~[BmqBizSystem.jaz:build201609122239]
        at io.itit.itf.wxbiz.srv.WeixinPayService.postCert(WeixinPayService.java:145) ~[BmqBizSystem.jaz:build201609122239]
        ... 10 more
Caused by: java.io.EOFException: \n not found: size=0 content=…
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:215) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:186) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:53) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124) ~[BmqBizSystem.jaz:build201609122239]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[BmqBizSystem.jaz:build201609122239]

**Comment by JakeWharton** [comment] 2016-09-13 13:16
Dupe of #1517.

**Closed by JakeWharton** 2016-09-13 13:16 UTC

**Comment by moziqi** [comment] 2017-12-02 03:30
java.io.EOFException: \n not found: size=0 content=...
