### ISSUE TITLE
Customize KeyStore for HandshakeCertificates

### ISSUE THREAD

**Issue by MGaetan89** [square/okhttp#6116] opened 2020-06-05 12:45 UTC
Hello,

I am trying to establish a connection with my server by using two way SSL.
For that, I'm using `HandshakeCertificates` as follow:
```kotlin
val deviceCertificate = keyStore.getCertificate(CERTIFICATE_ALIAS) as X509Certificate
val publicKey = deviceCertificate.publicKey
val privateKey = getKeyStore().getKey(KEY_ALIAS, null) as PrivateKey
val keyPair = KeyPair(publicKey, privateKey)
val heldCertificate = HeldCertificate(keyPair, deviceCertificate)

handshakeBuilder.heldCertificate(heldCertificate)
```

Which I then set on my OkHttpClient with:
```kotlin
val handshake = handshakeBuilder.build()

clientBuilder.sslSocketFactory(handshake.sslSocketFactory(), handshake.trustManager)
```

But when I run my app, it crashes with:
```
java.security.KeyStoreException: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
        at com.android.org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineSetKeyEntry(BcKeyStoreSpi.java:689)
        at java.security.KeyStore.setKeyEntry(KeyStore.java:1179)
        at okhttp3.tls.internal.TlsUtil.newKeyManager(TlsUtil.kt:95)
        at okhttp3.tls.HandshakeCertificates$Builder.build(HandshakeCertificates.kt:175)
        at com.myapp.common.security.data.CommonSecurityProvider$Companion.getSslSocketFactoryConfig(CommonSecurityProvider.kt:112)
        at com.myapp.common.network.di.CommonNetworkModuleKt$commonNetworkModule$1$7.invoke(CommonNetworkModule.kt:64)
        at com.myapp.common.network.di.CommonNetworkModuleKt$commonNetworkModule$1$7.invoke(Unknown Source:4)
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
        	... 139 more
```

From my investigation, it could be because OkHttp is using its own `KeyStore` when building the `HandshakeCertificates`, while my app is using `AndroidKeyStore`. Is there a way to customize this? Or am I doing something wrong?

https://github.com/square/okhttp/blob/4c595553fbcbfc316d24a74197aa753dbc05da9f/okhttp-tls/src/main/kotlin/okhttp3/tls/HandshakeCertificates.kt#L175-L176

**Comment by yschimke** [comment] 2020-06-05 19:57
Dupe of https://github.com/square/okhttp/issues/5684

Bouncy Castle is throwing away the root cause exception

```
        try
        {
            table.put(alias, new StoreEntry(alias, key, password, chain));
        }
        catch (Exception e)
        {
            throw new KeyStoreException(e.toString());
        }
```

**Comment by yschimke** [comment] 2020-06-05 20:40
I'd like to understand why it's happening, how we are triggering.  But ultimately I suspect it's a bouncycastle issue on Android.  Worth raising with them.

Can you easily test with BouncyCastle betas?

https://downloads.bouncycastle.org/betas/bcprov-jdk15on-166b10.jar
https://downloads.bouncycastle.org/betas/bcpkix-jdk15on-166b10.jar
https://downloads.bouncycastle.org/betas/bctls-jdk15on-166b10.jar

**Comment by yschimke** [comment] 2020-06-05 20:48
Poor mans attempt at a reproduction https://github.com/square/okhttp/pull/6118/files

**Comment by yschimke** [comment] 2020-06-07 08:01
Closing out here and will track on https://github.com/bcgit/bc-java/issues/723

I'll reopen this if BC closes out their issue, or we can reprod here.  But currently not much we can do with this report, it's failing outside of our codebase.

Separately please re-open if you can provide a minimal reproduction.  And thanks for reporting, I'd love to get to the bottom of this.

**Comment by MGaetan89** [comment] 2020-06-07 08:36
Thanks for your time on this issue.

From our investigation, the `NullPointerException` is coming from here: https://cs.android.com/android/platform/superproject/+/master:external/bouncycastle/repackaged/bcprov/src/main/java/com/android/org/bouncycastle/jcajce/provider/keystore/bc/BcKeyStoreSpi.java;l=413?q=BcKeyStoreSpi&ss=android%2Fplatform%2Fsuperproject

I'll try to use the beta versions of Bouncy Castle, or provide a minimal failing project to reproduce the issue.

For my original question, is there a way (or is it planned), to be able to set the `KeyStore` type in `HandshakeCertificates`, instead of passing `null` to `newKeyManager` and `newTrustManager`?

**Comment by yschimke** [comment] 2020-06-07 09:17
@MGaetan89 not actively planned as far as I know, but with a clean repro and ideally a PR, we can work out the right API for this.

**Comment by yschimke** [comment] 2020-06-07 09:24
@MGaetan89 if it's happening in the AOSP copy of bc-java, I guess you can't use a beta.  That is probably a dead end, sorry.

**Comment by yschimke** [comment] 2020-06-07 09:37
Can you workaround for now with something like

```
    System.setProperty("keystore.type", "BKS")

    Security.insertProviderAt(BouncyCastleProvider(), 1)
    Security.insertProviderAt(BouncyCastleJsseProvider(), 2)
```

**Comment by slovi** [comment] 2020-07-23 10:15
@MGaetan89 Hi Gaetan, I have the same problem. Did you find any solution?

I investigated that and the problem most likely seems to be in this class:

https://android.googlesource.com/platform/external/conscrypt/+/dac92c6/src/main/java/org/conscrypt/OpenSSLRSAPrivateKey.java#195

getFormat() method returns null if key is "engineBased". Does anybody know what does it mean and how to instantiate PrivateKey which is guaranteed to be exportable? (otherwise I cannot store it as an enty in keystore).

**Comment by yschimke** [comment] 2020-08-29 08:42
Is this happening with 4.8.1 still?

**Comment by MGaetan89** [comment] 2020-08-31 08:19
I've just check again with OkHttp 4.8.1, and I still have the same issue.

**Comment by yschimke** [comment] 2020-12-09 08:43
@MGaetan89 I think I finally understand this enough to attempt a workaround

This is the terrible workaround I've tested with https://gist.github.com/yschimke/4a1eda31c584a64549c790d887f275e0

**Comment by yschimke** [comment] 2023-05-21 08:19
Closing as low priority.  Is this actively blocking anyone?

OkHttp allows working around limitations of our default code.

**Closed by yschimke** 2023-05-21 08:19 UTC
Labels: bug, needs info, android
