### ISSUE TITLE
java.util.NoSuchElementException  

### ISSUE THREAD

**Issue by blueberryCoder** [square/okhttp#5954] opened 2020-04-15 09:31 UTC
okhttp:3.14.7
android

when i use Protocol.H2_PRIOR_KNOWLEDGE    + charles proxy

1. socket connected  and new Http2Conection
2. but the Http2Connection$ReaderRunable  failed  (because charles proxy )
3. then the socket be closed by reader thread.
4. then ExchangeFinder$findHealthyConnection check the connection is not healthy
5. so find the next route ,then occur `java.util.NoSuchElementException`

Could you throw  a IOException ?

java.util.NoSuchElementException
        at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:75)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:187)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
        at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
        at okhttp3.RealCall.execute(RealCall.java:81)

Here’s an example test to get you started.
https://gist.github.com/swankjesse/981fcae102f513eb13ed

**Comment by yschimke** [comment] 2020-04-16 07:44
Dupe of https://github.com/square/okhttp/issues/4875

**Closed by yschimke** 2020-04-16 07:44 UTC
Labels: bug
