### ISSUE TITLE
EventListener.connectFailed() callback has not called in case of client certificate has been expired

### ISSUE THREAD

**Issue by puresprout** [square/okhttp#6115] opened 2020-06-05 12:26 UTC
I am using okhttp-3.12.6 library.

I understand that the connection establishment process for TLS two-way authentication is as follows.

1. Send the server certificate from the server to the client.
2. The client checks the expiration period of the server certificate.
3. If it has not expired, the client sends a client certificate to the server
4. The server checks the expiration period of the client certificate.

I implemented okhttp3's EventListener to print the log in all callback methods.

Case 1-Server Certificate Expiration, Client Certificate Expiration

```
callStart
dnsStart
dnsEnd
connectStart
secureConnectStart

connectFailed-javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found. java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

callFailed-javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found. java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```

In case 1, the connectFailed callback was called because the server certificate has expired.

Case 2 - Server certificate never expires, client certificate expires

```
callStart
dnsStart
dnsEnd
connectStart
secureConnectStart
secureConnectEnd
connectEnd
connectionAcquired
connectionReleased

callFailed javax.net.ssl.SSLProtocolException: Read error: ssl=0x7db18ac008: Failure in SSL library, usually a protocol error
error:10000415:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_EXPIRED (external/boringssl/src/ssl/tls_record.cc:592 0x7db18fe288:0x00000001)
```

In case 2, the connectFailed callback was not called even though the client certificate expired.

the connectFailed callback called when the server certificate expires, but why does the connectFailed callback not called when the client certificate expires?

I understand that the process of establishing a TLS connection involves sending and receiving both server and client certificates.

Is this a bug?

(To test you should issue both server and client certificates.
To expire the certificate, you can use the method of adjusting the local time or issue the actual expired certificate.)

**Comment by yschimke** [comment] 2020-06-05 19:43
I can't reproduce, I suspect that it's related to the timing of the server rejecting the client certificate.  Not something we control.

https://github.com/square/okhttp/pull/6117

**Comment by puresprout** [comment] 2020-06-06 04:20
It is correct that the client's EventListener.callFailed() callback is called because the server refused to connect due to the expiration of the client certificate.
By the way, I think the connectFailed() callback should be called first, why not called?

Conversely, when the server certificate expires, the client's EventListener.connectFailed() callback is called. And finally callFailed() is called.

yschimke said it is not reproduced,
> I can't reproduce, I suspect that it's related to the timing of the server rejecting the client certificate. Not something we control.
> 
> #6117

Are you saying that the connectFailed() callback was called normally when the client certificate expired?

I think both case 1 and case 2 should be called in the following order.

```
...
connectFailed()
...
callFailed()
```

However, when the client certificate expires, there is no call to connectFailed() itself. callFailed() is always called.

Thank you for attaching the test result that outputs the debugging log of yschimke.

**(I am using okhttp-3.12.6 library.)**

**Comment by yschimke** [comment] 2020-06-06 09:10
Overall, I suspect the answer is that we are mainly dependent on the implementation of the server and timing variability.  I've landed baseline tests but there are a couple of open questions.

1) Should MockWebServer do any additional checks that a real server would after the non-blocking call to 

```
          sslSocket.startHandshake()
```

Calling sslSocket.getSession() would block, while other methods allow earlier validation. 

See https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/SSLSocket.html#getHandshakeSession() for some context. 

2) Is there any client behaviour we should check for e.g. the report above indicates that we are releasing the connection, is that considered a candidate connection for a second request?

**Comment by swankjesse** [comment] 2020-06-06 19:25
No further action to take on this.

**Closed by swankjesse** 2020-06-06 19:25 UTC
Labels: bug
