### ISSUE TITLE
Crash: Unexpected TLS version: NONE

### ISSUE THREAD

**Issue by anthony3444** [square/okhttp#3719] opened 2017-12-12 05:47 UTC
Hi there!

First at all thank you very much for your library!

I've integrated okhttp3 since couple months ago; there were no problem until yesterday with an user (Huawei, model MHA-L29, on Android 7.0):

```
Fatal Exception: java.lang.IllegalArgumentException: Unexpected TLS version: NONE
       at okhttp3.TlsVersion.forJavaName(TlsVersion.java:53)
       at okhttp3.Handshake.get(Handshake.java:56)
       at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:300)
       at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:268)
       at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160)
       at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
       at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:776)
```
Have you got some ideas about this crash?

Thank you very much guys!

**Comment by yschimke** [comment] 2017-12-12 06:07
Does your app upgrade to GMS services SSL? e.g. include ProviderInstaller.installIfNeeded

I've seen a similar issue in rare timing cases either before or after a network issue, the SSL provider can return NONE as the string.  OkHttp might have to handle this more gracefully.

https://github.com/google/conscrypt/blob/c88f9f55a523f128f0e4dace76a34724bfa1e88c/common/src/main/java/org/conscrypt/SSLNullSession.java#L149-L151

**Comment by anthony3444** [comment] 2017-12-12 06:29
Hi!

About your questions:

- "Does your app change the SSL provider in any way? to GMS services e.g. include ProviderInstaller.installIfNeeded" : no change
- "Is it a one-off or consistently reproducible?" : just only 1 crash until now

Is there a manner to catch this exception in my App to avoid a crash?

**Comment by asfdfdfd** [comment] 2017-12-13 15:35
I could confirm this issue on multiple devices. You could look in details at Crashlytics http://crashes.to/s/188322d298a

I use GMS ProviderInstaller and custom SSLSocketFactory.

**Comment by dgadelha** [comment] 2017-12-23 00:23
+1:

![image](https://user-images.githubusercontent.com/10081640/34315440-a19f2062-e766-11e7-824d-7ca4a623d7bb.png)

**Comment by yschimke** [comment] 2017-12-23 10:35
n.b. my PR fix will turn these into IOExceptions and handle them cleanly e.g. retry other connection routes.  But it won't fix an underlying fatal problem e.g. connecting to specific servers with a custom SSLSocketFactory.

**Comment by anthony3444** [comment] 2018-01-09 20:24
@yschimke: this crash stills there :( I've added ProviderInstaller.installIfNeeded into my App + a custom SSLSocketFactory. It's really rare, but today 1 user had this crash (Android 7.0 on Galaxy S7 Edge).

**Comment by yschimke** [comment] 2018-01-10 05:06
@anthony3444 the fix is in the next release (3.10), until then when they happen you will get a crash from OkHttp.

**Comment by hidroh** [comment] 2018-01-22 15:27
We're observing the same crash. 100% of crashes happen to users on Google phones running Android 8.1.0, though we can't reproduce on the same device we have.

**Comment by sergicastellsague** [comment] 2018-01-24 08:09
@yschimke do we have an ETA of this release?

**Comment by yschimke** [comment] 2018-01-24 08:37
I don't, I think we had planned for a 3.10 earlier than this.  cc @swankjesse @JakeWharton

**Comment by kelset** [comment] 2018-01-29 16:02
Hey guys, same crash - it's quite rare for us too, was just wondering if the issue could be kept open until 3.10 is released.

Are there any extra informations that I could provide that may be needed/helpful?

**Comment by swankjesse** [comment] 2018-02-18 20:37
I think this is fixed in 3.10.

**Closed by swankjesse** 2018-02-18 20:37 UTC
Labels: bug

**Comment by anna-b** [comment] 2018-02-20 12:45
@swankjesse is 3.10 expected to be released any time soon? thanks!

**Comment by kelset** [comment] 2018-02-20 13:41
@anna-b if you look at the [milestone](https://github.com/square/okhttp/milestone/22) they seem to be aiming for end Feb. So a bit more than a week.

**Comment by vasiledoe** [comment] 2018-07-10 09:11
same error using 3.10 with Retrofit 2

**Comment by yschimke** [comment] 2018-07-10 09:57
Mostly fixed in 3.10, but there was a race condition.  Hopefully fixed correctly in 3.11

**Comment by dave-r12** [comment] 2018-07-10 18:57
Also, that stack trace appears to be 3.8.

**Comment by TomasYu** [comment] 2018-07-18 06:06
Is this fixed in 3.11?

**Comment by yschimke** [comment] 2018-07-18 06:29
Yes, if you see it with 3.11 or it manifests in other similar ways, please open an issue.

**Comment by gongzelong0718** [comment] 2018-07-31 08:27
@yschimke 

Thanks for your reply. 
Could you specify which commit in 3.11 fix that issue?

I just upgrade to 3.10 to fix another crash (https://github.com/square/okhttp/issues/3438)
Could you explain more about under which rare condition does this crash still happen in 3.10 ?

**Comment by swankjesse** [comment] 2018-07-31 10:53
@gongzelong0718 please give 3.11 a try. The commits in the release are on our git history.

**Comment by dave-r12** [comment] 2018-08-01 13:10
@gongzelong0718 the stack trace includes class names and line numbers. We can correlate that information with git tags to understand possible versions. For example: `okhttp3.ConnectionSpec.tlsVersions(ConnectionSpec.java:113) at `

In version 3.8 it contains this line of code:
https://github.com/square/okhttp/blob/parent-3.8.0/okhttp/src/main/java/okhttp3/ConnectionSpec.java#L113

And in 3.10:
https://github.com/square/okhttp/blob/parent-3.10.0/okhttp/src/main/java/okhttp3/ConnectionSpec.java#L113

Note that 3.10 has no executable code!

**Comment by chwnFlyPig** [comment] 2019-03-26 05:13
this issue still exists in okhttp3.12.1. 
here is my logs:
![TlsVersion-crash](https://user-images.githubusercontent.com/8335653/54972963-e83ee400-4fc8-11e9-8c8a-0ecbe916448f.png)
