### ISSUE TITLE
Android 11 also has socket timeouts

### ISSUE THREAD

**Issue by zomanubhav87** [square/okhttp#6541] opened 2021-02-03 20:05 UTC
okhttpversion - 3.14.9

Reffering the almost same [issue](https://github.com/square/okhttp/issues/3974).
But this issue still hasn't been resolved and it is also occurring on android 11.

```
Non-fatal Exception: java.net.SocketTimeoutException
timeout
okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException (Http2Stream.java:678)
okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut (Http2Stream.java:686)
okhttp3.internal.http2.Http2Stream.takeHeaders (Http2Stream.java:154)
okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders (Http2ExchangeCodec.java:136)
okhttp3.internal.connection.Exchange.readResponseHeaders (Exchange.java:115)
okhttp3.internal.http.CallServerInterceptor.intercept (CallServerInterceptor.java:94)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:142)
okhttp3.internal.connection.ConnectInterceptor.intercept (ConnectInterceptor.java:43)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:142)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:117)
okhttp3.internal.cache.CacheInterceptor.intercept (CacheInterceptor.java:94)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:142)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:117)
okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.java:93)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:142)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.java:88)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:142)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:117)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:142)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:117)
okhttp3.RealCall.getResponseWithInterceptorChain (RealCall.java:229)
okhttp3.RealCall.execute (RealCall.java:81)
com.google.firebase.perf.network.FirebasePerfOkHttpClient.execute (FirebasePerfOkHttpClient.java:5)
retrofit2.OkHttpCall.execute (OkHttpCall.java:190)
retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall.execute (DefaultCallAdapterFactory.java:98)
android.os.Handler.handleCallback (Handler.java:883)
```

<img width="314" alt="Screenshot 2021-02-04 at 1 43 18 AM" src="https://user-images.githubusercontent.com/67726653/106803583-5efb9c80-668a-11eb-92fa-c523ae803dc8.png">

This is happening when we are making a network call from background when app is opened by work manager.

**Comment by swankjesse** [comment] 2021-02-04 02:48
Duplicate of https://github.com/square/okhttp/issues/3974

**Closed by swankjesse** 2021-02-04 02:48 UTC
Labels: bug
