### ISSUE TITLE
Javadoc jar is empty

### ISSUE THREAD

**Issue by ansman** [square/okhttp#6475] opened 2020-12-15 14:47 UTC
The javadoc jar that okhttp publishes is empty. This is likely because `withJavadocJar()` is used which doesn't support dokka. 

To fix it you should be able to create a dokka task named `javadocJar` before calling it.

**Comment by yschimke** [comment] 2020-12-15 14:54
Dupe of https://github.com/square/okhttp/issues/6475, thanks for reporting!

**Closed by yschimke** 2020-12-15 14:54 UTC
Labels: bug

**Comment by ansman** [comment] 2020-12-15 14:55
I think the dupe link is incorrect because it points back to this issue.
