### ISSUE TITLE
OkHttp's cache doesn't save multiple response variants for the same target

### ISSUE THREAD

**Issue by mizosoft** [square/okhttp#6214] opened 2020-08-06 01:02 UTC
OkHttp's `Cache` seems to replace an existing response entry if another comes from the same target but with different values for request's `Vary` fields. For example consider this test case: 

```java
@Test void vary() throws Exception {
  var server = new MockWebServer();
  server.setDispatcher(new Dispatcher() {
    @Override public MockResponse dispatch(RecordedRequest recordedRequest) {
      var baseResponse = new MockResponse()
          .addHeader("Cache-Control", "max-age=69420")
          .addHeader("Vary", "Accept-Encoding");
      var body = "ZIP ME!";

      var encoding = recordedRequest.getHeader("Accept-Encoding");
      if ("gzip".equalsIgnoreCase(encoding)) {
        return baseResponse.addHeader("Content-Encoding", "gzip")
            .setBody(ZipUtils.gzip(body));
      } else if ("deflate".equalsIgnoreCase(encoding)) {
        return baseResponse.addHeader("Content-Encoding", "deflate")
            .setBody(ZipUtils.deflate(body));
      } else {
        return baseResponse.setBody(body);
      }
    }
  });
  server.start(8080);

  var client = new OkHttpClient.Builder()
      .cache(new Cache(Files.createTempDirectory("okhttp-cache").toFile(), 10 * 1024))
      .build();

  var gzipRequest = new Request.Builder()
      .url(server.url("/"))
      .header("Accept-Encoding", "gzip")
      .build();
  try (var response = client.newCall(gzipRequest).execute()) {
    assertEquals("ZIP ME!", ZipUtils.gunzip(response.body().bytes()));
    assertEquals(1, client.cache().networkCount());
    assertEquals(0, client.cache().hitCount());
  }

  // gzip response gets replaced as both requests have same key using by the cache (URL)
  var deflateRequest = new Request.Builder()
      .url(server.url("/"))
      .header("Accept-Encoding", "deflate")
      .build();
  try (var response = client.newCall(deflateRequest).execute()) {
    assertEquals("ZIP ME!", ZipUtils.inflate(response.body().bytes()));
    assertEquals(2, client.cache().networkCount());
    assertEquals(0, client.cache().hitCount());
  }

  try (var response = client.newCall(gzipRequest).execute()) {
    assertEquals("ZIP ME!", ZipUtils.gunzip(response.body().bytes()));
    // Expected: use previously saved response
    assertEquals(2, client.cache().networkCount()); // fails: expected 2 but was 3
    assertEquals(1, client.cache().hitCount());     // fails: expected 1 but was 0
  }
}
```

I don't know if this is intentional or not but if I understand correctly, a cache is allowed to have multiple response entries per cache key, each with a secondary key represented by request's selecting headers values (last paragraph of [RFC 7234 sec 2](https://tools.ietf.org/html/rfc7234#section-2)). If this is indeed intentional, it'd be much appreciated to know reasons why.

Thanks in advance & great library!

**Comment by swankjesse** [comment] 2020-08-06 04:23
Confirmed. You're the first person to notice that independent variations are missing, so it might have been the right call! Or at least at the time.

OkHttp’s cache was originally designed to be concurrent enough for single-user applications (like a browser) but it's now commonly used in server and cloud environments where this design is too limiting.

What's your use case? Presumably we need something other than an MD5 of the URL as a cache key.

**Comment by mizosoft** [comment] 2020-08-06 05:57
Hi jesse, thanks for the response.

Unfortunately, I don't have a specific use case for this, I've just been messing with the cache lately :p. However, I can imagine one for a single-user being having multiple representations for a resource (say multiple languages for an article). With the current design, switching to one representation (different `Accept-...`) causes the cache to invalidate the other.

As for the key, I'm not sure how you'd integrate `Vary` fields since you probably need to read entry's metadata with URL key first. Since `DiskLruCache` acts as a `ListMultimap` in some sense, I'm guessing you might use an index for each variant, with the metadata mapping each request's `Vary` field values to it's corresponding index (variant).

**Comment by yschimke** [comment] 2020-08-06 06:13
I suspect anyone who hit this probably found it quicker to append a fake "?variant=XML" on the URL than explain the bug and request a fix.  It seems like a useful feature if done right, there might even be broader issues here like cache pollution we aren't handling?

**Comment by swankjesse** [comment] 2020-08-06 11:48
I don't believe there's cache pollution; it'll just evict something it doesn't need to evict when you switch variants.

Because fixing this has a real runtime cost (more work for cache lookup) and unclear benefit my preference is to icebox this.

**Comment by yschimke** [comment] 2020-08-06 12:03
> I don't believe there's cache pollution; it'll just evict something it doesn't need to evict when you switch variants.

Is that because if it's per user or per variant it just won't be very cacheable? Public caches would see problems well before we do?

**Comment by swankjesse** [comment] 2020-08-06 12:05
Its because if we have a variant mismatch we treat it like a stale cache entry. The old variant is not used and the new one will clobber it.

**Comment by yschimke** [comment] 2020-08-08 07:01
Going to close this out rather than icebox it.  Hasn't been a priority and @mizosoft doesn't have a firm need for it.

**Closed by yschimke** 2020-08-08 07:01 UTC
Labels: bug, enhancement

**Comment by juandesi** [comment] 2021-06-03 17:24
I have a similar use case with a Header that changes the response body. The workaround that we used is to send dummy query params to force another cache key for each request with different headers. Is there any strict reason why this is not going to be implemented?

**Comment by swankjesse** [comment] 2021-06-04 03:05
@juandesi it's surprisingly complicated to implement! We no longer have a single identifier for each cache entry, and we may even need to build precedence rules when multiple cached responses can satisfy a single request.

If you have two different responses, I like your solution of using two URLs.

**Comment by juandesi** [comment] 2021-06-04 11:59
I can imagine how complex this could get, but from my POV this behaviour makes the vary header unusable for caching then. Every time that a vary header changes it will force a cache eviction, even if you alternate the same two values.  For me this requests (despite they are pointing to the same endpoint) are different, they are not a single request.

Is there any way to provide another cache implementation to cover this ? maybe that could work for you and users that want this behaviour (or another one) can implement their own cache.

Anyways, thanks for the clarification :)

**Comment by swankjesse** [comment] 2021-06-05 13:41
The cache itself is not pluggable but you can use an interceptor to do your own cache if you like. The one drawback of that is you won't get called to cache redirects unless you get pretty fancy. (Doing a cache in a network interceptor won't work because it won't let you skip the network call.)
