### ISSUE TITLE
OkHttp support for asynchronous APIs to receive a response body in parts.

### ISSUE THREAD

**Issue by mikebgrep** [square/okhttp#7935] opened 2023-07-11 18:45 UTC
Hi, it will be great if support for receiving a response body in parts when executing a GET request be implemented.I am using an API that has an endpoint that retrieves all record's from the given table and this going for a while.

I see in documentation that this is not supported at the moment, so you consider made this update.
 
Ps. Is there some another way that this can be achieved.

**Comment by yschimke** [comment] 2023-07-11 19:52
Is this a dupe of https://github.com/square/okhttp/issues/7263 ?

The suggestion there is still the plan of record

> Would you consider forking MultipartReader to specialize it for your use case

I promised to take a look at that to confirm, so I'll follow up on there.

**Comment by JakeWharton** [comment] 2023-07-12 03:19
And notably this already works for all usage of the underlying RequestBody except for abstraction on top of it.

**Comment by mikebgrep** [comment] 2023-07-12 06:55
Hi, so you suggest that this example will work beside they are written in the documentation that receiving body in parts is not working.

https://github.com/square/okhttp/issues/7263#issuecomment-1115390637

**Comment by yschimke** [comment] 2023-07-12 07:44
I think that relates to buffering, MultipartReader shouldn't read the entire response into memory.  But if you are getting exact segments with delays in between that implementation isn't working. 

Closing this as a dupe, there is a very real limitation in the other bug, but it's not baked into the core response body, so you can modify MultipartReader to fit your needs.

**Closed by yschimke** 2023-07-12 07:44 UTC

**Comment by mikebgrep** [comment] 2023-07-12 16:38
I will check the duplicate
