### ISSUE TITLE
How to custom request method?

### ISSUE THREAD

**Issue by linyongsheng** [square/okhttp#3669] opened 2017-10-30 05:11 UTC
I use okhttp to implement UPnP protocol stack.  There are some request method less common ,like NOTIFY
 SUBSCRIBE UNSUBSCRIBE.
```
Request request = new Request.Builder()
                .url(record.callback)
                .method("NOTIFY", requestBody)
                .header("NT", "upnp:event")
                .header("NTS", "upnp:propchange")
                .header("SID", sid)
                .header("SEQ",  seq)
                .build();
```
but it will throw exception. I know it can't past the follow check `HttpMethod.permitsRequestBody`:
```
public static boolean permitsRequestBody(String method) {
    return requiresRequestBody(method)
        || method.equals("OPTIONS")
        || method.equals("DELETE")    // Permitted as spec is ambiguous.
        || method.equals("PROPFIND")  // (WebDAV) without body: request <allprop/>
        || method.equals("MKCOL")     // (WebDAV) may contain a body, but behaviour is unspecified
        || method.equals("LOCK");     // (WebDAV) body: create lock, without body: refresh lock
  }
```
okhttp will alow custom request method in the future?

**Comment by linyongsheng** [comment] 2017-11-02 06:10
@swankjesse

**Comment by yschimke** [comment] 2017-11-04 00:01
dupe of https://github.com/square/okhttp/issues/229

**Closed by yschimke** 2017-11-04 00:01 UTC

**Comment by arjunmenon** [comment] 2018-05-10 13:46
@linyongsheng Were you able to solve this? I got a Openhome setup and need to communicate with it. What was your workaround?
