### ISSUE TITLE
OkHttp does not close connection when server sends a FIN, ACK

### ISSUE THREAD

**Issue by tejasjadhav** [square/okhttp#7045] opened 2022-01-31 13:21 UTC
We've recently encountered an issue on production wherein an HTTP server, which is shutting down, sends back a `FIN, ACK` packet, but OkHttp still continues sending traffic on that connection instead of closing it and started a new connection.

Here is a screenshot of one such incident on Wireshark on my local setup (`10.101.84.85` is the server, `172.17.0.6` is the client),
![Screenshot 2022-01-31 at 6 27 11 PM](https://user-images.githubusercontent.com/10093001/151797917-9896ce18-f5c7-45f4-86fb-4e46cfaefee9.png)

My test setup is as follows,
* Hosted on Kubernetes.
* Client side running using OkHttp 4.5.0 (Java 18)
* Server side running a Golang HTTP server (Golang 1.18)
* Client side uses Kubernetes FQDN to talk to the server.
* Client maintains a connection pool of 10 connections.
* Client side code: https://gist.github.com/tejasjadhav/d5a4b4efca8e7400236ce18e86dcb00a#file-app-java
* Server side code: https://gist.github.com/tejasjadhav/d5a4b4efca8e7400236ce18e86dcb00a#file-main-go

### Expectation
OkHttp client should remove the connection from the pool when server sends back `FIN, ACK` packet.

### Actual
OkHttp does not terminate the connection for which server sends back `FIN, ACK` packet and still sends traffic on that connection, which results in a connection resets and failures on subsequent calls.

### Steps to reproduce
1. Create an OkHttp client with a connection pool to an HTTP server.
2. Make 1-2 requests using that client to initialise the pool.
3. Shutdown the server. Observe that `FIN, ACK` packets are being sent by the server on shutdown.
4. While the server is shutting down, send 1-2 requests using the OkHttp client.
5. The requests should fail with an error `unexpected end of stream`. Server would have sent an `RST` in response.

### Environment
* OkHttp 4.5.0
* Java 18

**Comment by yschimke** [comment] 2022-01-31 15:21
Any chance you can test with 4.9.3? We have had various fixes in this area, but not specifically aware of anything that would fix it.

**Comment by tejasjadhav** [comment] 2022-01-31 16:17
@yschimke tried it on OkHttp 4.9.3. Still seeing the same behavior

![Screenshot 2022-01-31 at 9 44 44 PM 1](https://user-images.githubusercontent.com/10093001/151830823-579148a3-7dcf-4733-ba26-ef7f34172ebd.png)

**Comment by yschimke** [comment] 2022-02-06 08:32
I added a test specifically for this, from the test and also wireshark, it looks like it is working fine.

This is testing on localhost, so socket behaviour may very well be different.  We have often observed on Android that some network stacks don't detect the close in a timely manner, and rely on timeouts instead.

Can you try a similar test but with a raw socket, send "GET / HTTP/1.1" on the socket and confirm you get a timely IOException when the client reads from the InputStream.

<img width="1542" alt="image" src="https://user-images.githubusercontent.com/231923/152673214-2b18c32a-0976-474a-b0c2-3c466ca7926d.png">

I'll dig briefly into our healthchecks, maybe there is another case to consider, or timing differences, that differs on remote networks?

**Comment by yschimke** [comment] 2022-02-06 08:50
We shouldn't be able to reuse that connection because it isn't considered healthy once half closed

https://github.com/square/okhttp/blob/6d040e06c132048599cd8c22e9d2fc71e22d3245/okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/RealConnection.kt#L660-L672

also

https://github.com/square/okhttp/blob/6d040e06c132048599cd8c22e9d2fc71e22d3245/okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/RealConnection.kt#L7390L740

**Comment by yschimke** [comment] 2022-02-06 08:54
I'm pretty confident in saying that the only way we will continue to use that connection is if the VM doesn't know that the socket is halfclosed, and we also haven't got an IOException when reading the response.

OkHttp doesn't do pipelining, so there should only be one failed request, the one we expect that was in progress when the FIN was sent.

**Comment by tejasjadhav** [comment] 2022-02-06 14:56
@yschimke I tried to emulate the scenario again on localhost.

**Java:** 11
**OS:** MacOS Big Sur

But now I'm getting `Connection reset` error whenever server shuts down gracefully. However, if I force kill the server, I could see `Unexpected end of stream` error again.

Overall, I think there are three scenarios,

1. **Server and client both on Kubernetes**
  Can see `unexpected end of stream` on OkHttp even when server is terminating gracefullty. I think this could be because of what you stated as different behaviour around OS not being aware of socket disconnects.
2. **Server and client on localhost with graceful shutdown on server**
  Can see `Connection refused` errors on OkHttp.
3. **Server and client on localhost with abrupt shutdown (`kill -9`) on server**
  Can see `unexpected end of stream` on OkHttp.

However, in all the above cases, the one common behaviour to note was that the server did send a `FIN, ACK` packet back to OkHttp, but OkHttp still used the connection for subsequent requests.

![image](https://user-images.githubusercontent.com/10093001/152685654-290c2119-8f81-4b08-97b0-7f369d510e9d.png)

> OkHttp doesn't do pipelining, so there should only be one failed request, the one we expect that was in progress when the FIN was sent.

Actually, in all the cases I've seen so far, these errors (`Connection reset` as well as `Unexpected end of stream`) were only coming for those connection that were idle at the time when the server was shutting down and got reused for subsequent requests. The only connections that OkHttp removed from its connection pool on server shutdown were the ones that got a `Connection: close` header from the server in response to their previous requests.

> Can you try a similar test but with a raw socket, send "GET / HTTP/1.1" on the socket and confirm you get a timely IOException when the client reads from the InputStream.

Can you elaborate on this a bit?

I tried making a manual client wherein the requests from OkHttp to the server are triggered on keypress and I was able to emulate the above mentioned case (OkHttp reusing connection despite getting `FIN, ACK`) even 4s after server sent back a `FIN, ACK` packet to OkHttp. In this case, I got `Connection reset` exception in OkHttp,

![image](https://user-images.githubusercontent.com/10093001/152686431-4e966d73-945a-4737-b886-12081ffe5052.png)

**Comment by tejasjadhav** [comment] 2022-02-06 14:58
> I added a test specifically for this, from the test and also wireshark, it looks like it is working fine.

@yschimke I checked the [test case](https://github.com/square/okhttp/pull/7058/files#diff-25aa37fddf66072054d36067532b90601574ce5557deee1e4921d041e4b76363R1463) that you added. It asserts that `unexpected end of stream` errors are expected for half closed connections. So does it mean that this is an expected behaviour?

**Comment by yschimke** [comment] 2022-02-06 15:02
> > I added a test specifically for this, from the test and also wireshark, it looks like it is working fine.
> 
> @yschimke I checked the [test case](https://github.com/square/okhttp/pull/7058/files#diff-25aa37fddf66072054d36067532b90601574ce5557deee1e4921d041e4b76363R1463) that you added. It asserts that `unexpected end of stream` errors are expected for half closed connections. So does it mean that this is an expected behaviour?

Yes, I think it's correct.  We are halfway through a request, the client has sent the request body and then starts to read the response, which never comes because the server half closes the socket.

**Comment by yschimke** [comment] 2022-02-06 15:06
> Actually, in all the cases I've seen so far, these errors (`Connection reset` as well as `Unexpected end of stream`) were only coming for those connection that were idle at the time when the server was shutting down and got reused for subsequent requests. The only connections that OkHttp removed from its connection pool on server shutdown were the ones that got a `Connection: close` header from the server in response to their previous requests.

I designed the test because of the wireshark you showed at the top, it doesn't have a response from the last GET request, so I assumed this was the case.

I think we already have tests for the case you are describing, closing at the end of the request/response.

Generally I still don't see how we can reuse the connection, after it is idle in the pool and the socket has closed 4 seconds earlier.  We check if the socket is fully or half closed before reusing it.  I can't test on your machines and networks, so it's hard to replicate.

**Comment by yschimke** [comment] 2022-02-06 15:15
Can you try this...

Make a test, like the one I added to CallTest, either self contained using MockWebServer, or in the worst case calling against your existing server.  Also add in an Event Listener https://square.github.io/okhttp/4.x/okhttp/okhttp3/-event-listener/ that logs the Connection acquired, port number `(connection.socket().remoteSocketAddress as InetSocketAddress).port` and timestamps.  With that and a matching wireguard log/screenshot.

We should be able to confirm the scenario and that it's in error.

But it probably doesn't help us too much, I suspect that it will show the socket closes, but that we don't get the correct results from socket.isClosed().  We do healthchecks, and more extensive ones for methods other than GET.

**Comment by yschimke** [comment] 2022-03-10 08:27
Closing this out, my testing showed it working correctly.  And we know there are android issues where close doesn't get propogated.

**Closed by yschimke** 2022-03-10 08:27 UTC
Labels: bug, needs info

**Comment by esudaley** [comment] 2024-02-28 02:08
Hello, hope all is well. I'm seeing precisely the same behavior as the OP. 

![image](https://github.com/square/okhttp/assets/51211969/9111f588-cc51-40d8-ba9c-fc9009cae9a4)

This occurs when POSTing multipart/form-data from the InvokeHTTP NiFi processor which depends on,

`<groupId>com.squareup.okhttp</groupId>
<artifactId>okhttp</artifactId>
<version>2.7.1</version>`

openjdk version "11.0.22" 2024-01-16 LTS
OpenJDK Runtime Environment (Red_Hat-11.0.22.0.7-1) (build 11.0.22+7-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-11.0.22.0.7-1) (build 11.0.22+7-LTS, mixed mode, sharing)

The following is the stack trace as NiFi logs it,

 java.net.SocketException: Broken pipe (Write failed)
	at org.apache.nifi.controller.repository.StandardProcessSession.read(StandardProcessSession.java:2711)
	at org.apache.nifi.controller.repository.StandardProcessSession.read(StandardProcessSession.java:2656)
	at org.apache.nifi.processors.standard.InvokeHTTP$1.writeTo(InvokeHTTP.java:1181)
	at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.kt:157)
	at okhttp3.MultipartBody.writeTo(MultipartBody.kt:93)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:62)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at org.apache.nifi.processors.standard.InvokeHTTP.onTrigger(InvokeHTTP.java:951)
	at org.apache.nifi.processor.AbstractProcessor.onTrigger(AbstractProcessor.java:27)
	at org.apache.nifi.controller.StandardProcessorNode.onTrigger(StandardProcessorNode.java:1361)
	at org.apache.nifi.controller.tasks.ConnectableTask.invoke(ConnectableTask.java:247)
	at org.apache.nifi.controller.scheduling.TimerDrivenSchedulingAgent$1.run(TimerDrivenSchedulingAgent.java:102)
	at org.apache.nifi.engine.FlowEngine$2.run(FlowEngine.java:110)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	
I know this thread issue was closed some time ago, but it appears as though this is the same issue. Would you happen to have any thoughts? Thank you!

**Comment by yschimke** [comment] 2024-02-28 06:39
Please update to OkHttp 4.x and see if still reproducible. That version is unsupported

**Comment by esudaley** [comment] 2024-02-28 18:25
Thank you for your quick reply! Apologies, the issue is actually occurring when using version 4.11.0. 

https://github.com/apache/nifi/blob/rel/nifi-1.23.2/pom.xml#L111

I was referencing an outdated pom.

**Comment by polesapart** [comment] 2024-04-12 18:53
@esudaley I was using okhttp 4.12.0 with a somewhat outdated okio (I see somethign similar on the linked pom). After updating to 3.9.0, it started to work fine.
