### ISSUE TITLE
Multipart upload progress problem?

### ISSUE THREAD

**Issue by durunvo** [square/okhttp#1746] opened 2015-07-09 19:59 UTC
Hi, i used this code [pull/1528](https://github.com/square/okhttp/pull/1528) and get this error in onFailure

unexpected end of stream

Another thing, i don't understand that the progress is not from the uploading, but just writing the buffer?
Because the progress took like 30ms to finish and image size is 1Mb. It is too fast. 
Then it callback into onFailure
![screen shot 2558-07-10 at 2 58 18 am](https://cloud.githubusercontent.com/assets/5458194/8605442/8ec1f71e-26af-11e5-880f-0706efcdba12.png)

**Comment by swankjesse** [comment] 2015-07-09 20:53
We don't have progress implemented yet.
Duplicate of https://github.com/square/okhttp/issues/1471

**Closed by swankjesse** 2015-07-09 20:53 UTC
