### ISSUE TITLE
NullPointerException in 'c.f okhttp3.ResponseBody.source()'

### ISSUE THREAD

**Issue by hamberluo** [square/okhttp#2745] opened 2016-07-24 09:46 UTC
Device is Nexus 6P

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'c.f okhttp3.ResponseBody.source()' on a null object reference
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:103)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
       at okhttp3.RealCall.access$100(RealCall.java:33)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
```

**Comment by swankjesse** [comment] 2016-07-24 23:17
Do you have any interceptors installed? It’s possible that one of those interceptors is returning a response with a null body.

**Comment by hamberluo** [comment] 2016-07-25 02:25
@swankjesse it is reported from release version with no interceptors.

**Comment by swankjesse** [comment] 2016-07-25 02:53
Yikes, that looks like a regression! Do you mind using a network interceptor to track what the response headers & status code were? Can fix ASAP but it’ll be easier if I know how it got in this state.

**Comment by hamberluo** [comment] 2016-07-26 01:59
@swankjesse I can't reproduce this problem as it is uploaded by crashlytics which only happened on one user.

**Comment by swankjesse** [comment] 2016-07-30 16:15
Are you using websockets?

**Comment by swankjesse** [comment] 2016-07-30 16:16
I think this response might trigger it, but only if you’re using websockets:
```
    server.enqueue(new MockResponse()
        .setResponseCode(101)
        .addHeader("Content-Encoding", "gzip")
        .setBody(gzip("abcabc")));
```

**Comment by hamberluo** [comment] 2016-07-31 03:40
Yes I use websockets.

**Comment by boxme** [comment] 2016-08-01 05:41
@swankjesse 

I am trying to help with this and after some investigation it seems the below is causing the problem:

```
if (!forWebSocket || response.code() != 101) {
      response = response.newBuilder()
          .body(httpCodec.openResponseBody(response))
          .build();
}
```
does not allow the response to have body but `HttpHeaders.hasBody(response)` will return true due to having a `Content-Length` in the headers

Would the fix for this be removing `Content-Length` if it's a websocket and having response code 101?

**Comment by hamberluo** [comment] 2016-08-20 03:59
any progress?

**Comment by heqingbao** [comment] 2016-12-05 08:17
@hamberluo @swankjesse 
Yes, and WebSocket related, I can only ws replaced wss (if the server support). I guess it is because of _HTTP response hijacking_

**Comment by swankjesse** [comment] 2017-04-30 17:20
I believe this is fixed.

**Closed by swankjesse** 2017-04-30 17:20 UTC
Labels: bug, needs info
