### ISSUE TITLE
Non SDK API usages byOkHttp in Android Q Beta 4 

### ISSUE THREAD

**Issue by adityaiit** [square/okhttp#5181] opened 2019-06-10 19:20 UTC
Hi,

I am seeing the following log when checking for non-SDK usages in Android Q Beta 4 emulator

For OkHttp 3.12.0 version
Accessing hidden method Lcom/android/org/conscrypt/ConscryptFileDescriptorSocket;->setUseSessionTickets(Z)V (greylist,core-platform-api, reflection, allowed)
Accessing hidden method Lcom/android/org/conscrypt/ConscryptFileDescriptorSocket;->setHostname(Ljava/lang/String;)V (greylist,core-platform-api, reflection, allowed)
Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setAlpnProtocols([B)V (greylist,core-platform-api, reflection, allowed)
Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->getAlpnSelectedProtocol()[B (greylist,core-platform-api, reflection, allowed)

For OkHttp 3.14.2 version
Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setUseSessionTickets(Z)V (greylist,core-platform-api, reflection, allowed)
Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setHostname(Ljava/lang/String;)V (greylist,core-platform-api, reflection, allowed)
Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->getAlpnSelectedProtocol()[B (greylist,core-platform-api, reflection, allowed)
Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setAlpnProtocols([B)V (greylist,core-platform-api, reflection, allowed)
Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (greylist,core-platform-api, reflection, allowed)
Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (greylist,core-platform-api, reflection, allowed)
Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (greylist,core-platform-api, reflection, allowed)

I see that in ticket [#3980](https://github.com/square/okhttp/issues/3980) some of these warnings are resolved. I am planning to use 3.12.0 version as my app supports KitKat and above. 

Please let me know if all the non-SDK usages will be resolved in the future releases of OkHttp. If not, will it be fine to just continue using the non-SDK APIs without any problem?

Thanks

**Comment by swankjesse** [comment] 2019-06-11 00:51
Duplicate of https://github.com/square/okhttp/issues/3980

**Closed by swankjesse** 2019-06-11 00:51 UTC
Labels: bug

**Comment by guenter47** [comment] 2021-05-20 08:53
This is'nt a duplicate see: ->setUseSessionTickets(Z)V (greylist,core-platform-api, reflection, allowed)

**Comment by guenter47** [comment] 2021-05-20 08:53
I have the same warning
