### ISSUE TITLE
Cache stops being written to when java.io.InterruptedIOException: thread interrupted

### ISSUE THREAD

**Issue by snodnipper** [square/okhttp#1903] opened 2015-10-07 17:22 UTC
When requesting tens of files in separate threads, cancelling some results in an _java.io.InterruptedIOException: thread interrupted_ exception that causes [<code>hasJournalErrors = true;</code>](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/com/squareup/okhttp/internal/DiskLruCache.java#L305).

Consequently, within <code>private synchronized Editor edit(String key, long expectedSequenceNumber)</code> the cache is no longer updated because of [<code>hasJournalErrors</code>](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/com/squareup/okhttp/internal/DiskLruCache.java#L467).

Once in this state I do not believe that <code>rebuildJournal();</code> is called until the cache is reinitialized.  I looked in [<code>journalRebuildRequired()</code>](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/com/squareup/okhttp/internal/DiskLruCache.java#L434) but that does not consider the hasJournalErrors flag.

Perhaps I should guard against threads being cancelled that are writing to the cache?  RFC.

<img width="430" alt="okhttp" src="https://cloud.githubusercontent.com/assets/576719/10345116/3d54eb50-6d1f-11e5-9a3d-3b6d20472011.png">

**Comment by swankjesse** [comment] 2015-10-31 00:34
@snodnipper are you calling `Thread.interrupt()` ? That's unexpected on threads performing HTTP requests with OkHttp. You should prefer `Call.cancel()` instead.

**Comment by swankjesse** [comment] 2015-10-31 13:22
... or are you calling `ExecutorService.shutdown()` ?

**Comment by snodnipper** [comment] 2015-10-31 16:08
thanks Jesse for getting back.  I am going to have to check early next week - the calling code is [proprietary](https://developers.arcgis.com/android/), where I simply provided an adapter using okhttp.  I am pretty sure it is just an ExecutorService with <code>boolean cancel(boolean mayInterruptIfRunning = true)</code>.

Essentially, the use case is:
* user views a map which requests tens of map tiles (unique urls to cover visible map data)
* user zooms in or pans
* tiles scheduled for download _but_ now outside of the visible area are cancelled.

I will try and provide some further feedback next week.  Cheers!

**Comment by swankjesse** [comment] 2015-10-31 16:29
Right now OkHttp doesn't do well with interrupted threads. If you can use Call.cancel instead, things will probably work better.

(And we should independently decide what to do about Thread.interrupt, if anything.)

**Comment by snodnipper** [comment] 2015-11-03 14:14
So the logic of the software is pretty simple:
* ThreadPoolExecutor
* Runnable objects are [submitted](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/AbstractExecutorService.html#submit(java.lang.Runnable)) to the executor and the Future is stored in a map (URL -> Future)
* Futures are cancelled with [<code>cancel(true)</code>](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Future.html#cancel(boolean))

I resolved it quickly by using [MapDB](http://www.mapdb.org/) as the cache.  I then discussed a few options with folk, e.g. letting writes continue with another thread / using write ahead logs etc.  We didn't want to put too much effort in without at least checking in with you guys.

@schoenobates

**Comment by swankjesse** [comment] 2015-11-03 23:52
@snodnipper got it. My guess is that `Future.cancel()` calls `Thread.interrupt()`, and OkHttp isn't prepared to deal with this.

**Comment by snodnipper** [comment] 2016-01-12 18:53
added a crude project to demo the problem https://github.com/snodnipper/okhttp-issue1903-demo

**Comment by cre8ivejp** [comment] 2017-05-24 05:51
Any updates?
This is still happening on the version 3.8.0

**Comment by yschimke** [comment] 2020-03-29 18:48
Dupe of https://github.com/square/okhttp/issues/1902, closing as won't fix.

**Closed by yschimke** 2020-03-29 18:48 UTC
Labels: bug
