### ISSUE TITLE
Some Web Sockets tests are flaky

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#5708] opened 2020-01-07 03:01 UTC
https://circleci.com/gh/square/okhttp/8330?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

closeReasonMaximumLength - okhttp3.internal.ws.WebSocketHttpTest
```
org.junit.ComparisonFailure: expected:<[0]> but was:<[1]>
	at okhttp3.OkHttpClientTestRule.ensureAllConnectionsReleased(OkHttpClientTestRule.kt:91)
	at okhttp3.OkHttpClientTestRule$apply$1.evaluate(OkHttpClientTestRule.kt:121)
```

serverCloseThenClientClose - okhttp3.internal.ws.RealWebSocketTest
```
java.lang.AssertionError: 
Expecting empty but was:<[Closed[1000 Hello!]]>
	at okhttp3.internal.ws.WebSocketRecorder.assertExhausted(WebSocketRecorder.java:163)
	at okhttp3.internal.ws.RealWebSocketTest.tearDown(RealWebSocketTest.java:58)
```

**Comment by swankjesse** [comment] 2020-01-07 03:01
These flaked on Java 13.

**Comment by yschimke** [comment] 2020-01-07 13:42
At the moment the websocket tests are 3 of the 4 flaky tests

https://circleci.com/build-insights/gh/square/okhttp/master

**Comment by yschimke** [comment] 2020-05-09 07:18
Dupe of https://github.com/square/okhttp/issues/6033, which covers more tests

**Closed by yschimke** 2020-05-09 07:18 UTC
Labels: bug, tests
