### ISSUE TITLE
Response.body().string() is NOT Idempotent

### ISSUE THREAD

**Issue by mkatsoho** [square/okhttp#1988] opened 2015-11-11 08:12 UTC
Response resp = new OkHttpClient().newCall(req).execute();
        String respbody = resp.body().string();   
        String respbody_empty = resp.body().string();

**Comment by JakeWharton** [comment] 2015-11-11 08:13
It's not meant to be. Effectively a dupe of #1968.

**Closed by JakeWharton** 2015-11-11 08:13 UTC
