### ISSUE TITLE
https   request    SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by fengchuxiaodai** [square/okhttp#3554] opened 2017-08-30 09:42 UTC
This is a HTTPS request, the certificate created by ourselves, using the okhttp3.8.0 version to respond is ok, but the handshake failed using the 3.8.1 version, and the error message is as follows

: javax.net.ssl.SSLHandshakeException: Handshake failed
     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:429)
     at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:281)
     at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:251)
     at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:151)
     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195)
     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
     at java.lang.Thread.run(Thread.java:761)
 Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xe327b780: Failure in SSL library, usually a protocol error
 error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (external/boringssl/src/ssl/tls_record.c:192 0xe334faf3:0x00000000)
     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)

**Comment by swankjesse** [comment] 2017-08-30 14:04
It seems unlikely the changes between OkHttp 3.8.0 and 3.8.1 could cause this. I suspect the issue is elsewhere in your HTTPS config. Unfortunately I don't think there's anything we can do in OkHttp to fix this.

**Comment by swankjesse** [comment] 2017-08-30 14:31
Closing because I don’t think this is actionable. If I’m wrong, please provide an executable test case!

**Closed** 2017-08-30 14:31 UTC

**Comment by fengchuxiaodai** [comment] 2017-08-31 01:43
That's the way it is:
Okhttp uses the 3.8.0 version, and the same code can ask for success
Okhttp uses the 3.8.1 version, and the same code feedback handshake fails, and the log is the code I posted above

**Comment by fengchuxiaodai** [comment] 2017-08-31 01:44
Now we are changing certificates, and then try again, there is a problem to ask you

**Comment by fengchuxiaodai** [comment] 2017-08-31 01:51
Oh, I made a mistake
The last version we used was 3.4.1, not 3.8.0
So what's the difference between 3.4.1 and 3.8.1?

**Comment by swankjesse** [comment] 2017-08-31 02:06
https://github.com/square/okhttp/blob/master/CHANGELOG.md

My guess is it's this. Work around by creating a ConnectionSpec that supports TLSv1.
> “OkHttp no longer recovers from TLS handshake failures by attempting a TLSv1 connection.”

**Comment by fengchuxiaodai** [comment] 2017-08-31 02:11
No, I tried this, but still prompted a handshake failure

**Comment by fengchuxiaodai** [comment] 2017-08-31 02:27
I just tried again, plus the TLS encryption suite was set up, and I don't know why it wasn't set up before

**Comment by fengchuxiaodai** [comment] 2017-08-31 09:19
thank you！
But I have a question,  Why did you do that?

**Comment by swankjesse** [comment] 2017-08-31 14:27
TLSv1 is obsolete and security experts worry about potential compromises like Heartbleed soon becoming possible.
