### ISSUE TITLE
Url not valid for OkHttp Request, but valid for HttpUrlConnection

### ISSUE THREAD

**Issue by mr-procrastinator** [square/okhttp#1836] opened 2015-09-03 11:43 UTC
Could you describe why http request to http://ad.dc2.adtech.de/adserv/ADTECH;grp=[group] with using HttpUrlConnection are working fine:
```java
String url ="http://ad.dc2.adtech.de/adserv/ADTECH;grp=[group]";
URL u = null;
try {
    u = new URL(url);
} catch (MalformedURLException e) {
    e.printStackTrace();
    return;
}
try {
    HttpURLConnection connection = (HttpURLConnection) u.openConnection();
    L.d("response code "+ connection.getResponseCode());
    connection.disconnect();
} catch (IOException e) {
    e.printStackTrace();
}
```
whereas request with using OkHttp return error:
```java
String urlString ="http://ad.dc2.adtech.de/adserv/ADTECH;grp=[group]";
URL url = null;
try {
    url = new URL(urlString);
} catch (MalformedURLException e) {
    e.printStackTrace();
    return;
}
Request request = new Request.Builder()
        .url(url)
        .build();

okHttpClient.newCall(request).enqueue(new Callback() {
    @Override
    public void onFailure(Request request, IOException e) {
        e.printStackTrace();
    }

    @Override
    public void onResponse(Response response) throws IOException {
    }
});
```
Error:
```
java.io.IOException: not valid as a java.net.URI: http://ad.dc2.ad
       tech.de/adserv/ADTECH;grp=[group]
    W      at com.squareup.okhttp.Request.uri(Request.java:61)
    W      at com.squareup.okhttp.internal.http.HttpEngine.networkRequest(HttpEn
       gine.java:714)
    W      at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngin
       e.java:222)
    W      at com.squareup.okhttp.Call.getResponse(Call.java:267)
    W      at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.
       java:224)
    W      at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java
       :195)
    W      at com.squareup.okhttp.Call.access$100(Call.java:34)
    W      at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162)
    W      at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:
       33)
    W      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecut
       or.java:1112)
    W      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecu
       tor.java:587)
    W      at java.lang.Thread.run(Thread.java:818)
    W  com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162)
    W      at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:
       33)
    W      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecut
       or.java:1112)
    W      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecu
       tor.java:587)
    W      at java.lang.Thread.run(Thread.java:818)
```
Tested on OkHttp v2.5 
How to make it works with using OkHttp?

**Comment by swankjesse** [comment] 2015-09-03 13:10
Yeah, yuck. Right now OkHttp tries its best to avoid converting URLs to `java.net.URI`, since that class is overly strict around what characters are valid. Your best workaround is to string replace `[` with `%5b` and `]` with `%5d`. This only occurs because you're mixing `[` URLs with cookies.

`http://ad.dc2.adtech.de/adserv/ADTECH;grp=%5bgroup%5d`

In a future version of OkHttp we'll replace `java.net.CookieHandler` with our own interface that doesn't require `java.net.URI`.

**Comment by mr-procrastinator** [comment] 2015-09-03 13:25
Thanks, will try your workaround. I hope in next version it will be fixed.

**Comment by swankjesse** [comment] 2015-11-01 17:31
Fixed with https://github.com/square/okhttp/pull/1959

**Closed** 2015-11-01 17:45 UTC
Labels: bug

**Comment by traic** [comment] 2015-11-07 15:48
does this mean the cookie issue will be addressed?

**Comment by swankjesse** [comment] 2015-11-07 17:07
@traic the issue is fixed now. You can use the 2.6.0-SNAPSHOT if you like.
