### ISSUE TITLE
About ArrayIndexOutOfBoundsException of okhttp in arm64 & docker environment

### ISSUE THREAD

**Issue by blinkfox** [square/okhttp#6477] opened 2020-12-16 03:07 UTC
I recently used the MinIO Java SDK (`okhttp` is used internally) for concurrent performance testing, and when I deployed it directly on the `amd64` and `arm64` CPU architectures through the JVM for concurrent testing, there was no problem.

However, if I deploy and start the application through `Docker` under the `arm64` CPU architecture, and use `30` concurrent random putObject and getObject, an `ArrayIndexOutOfBoundsException` will be thrown after a while.

Finally, I upgraded the version of okhttp to `4.8.1`, and after the version of okio was `2.7.0`, this problem no longer exists. But if I use `okhttp-3.14.9`, will still have this problem.

I want to know why `okhttp-3.x` will throw `ArrayIndexOutOfBoundsException` only when `arm64` and `Docker` are working. What causes this exception? Moreover, the new version of `4.x` does not have this problem. Is there any change in the code implementation?

I would like to know the real reason for this, thank you for helping me answer it.

The exception log is as follows:

```java
java.lang.ArrayIndexOutOfBoundsException: 8192 
    at okio.Buffer.writeUtf8(Buffer.java:986) ~[okio-1.17.3.jar!/:na] 
    at okio.Buffer.writeUtf8(Buffer.java:961) ~[okio-1.17.3.jar!/:na] 
    at okio.RealBufferedSink.writeUtf8(RealBufferedSink.java:53) ~[okio-1.17.3.jar!/:na] 
    at okhttp3.internal.http1.Http1ExchangeCodec.writeRequest(Http1ExchangeCodec.java:196) ~[okhttp-3.14.9.jar!/:na] 
    at okhttp3.internal.http1.Http1ExchangeCodec.writeRequestHeaders(Http1ExchangeCodec.java:141) ~[okhttp-3.14.9.jar!/:na] 
    at okhttp3.internal.connection.Exchange.writeRequestHeaders(Exchange.java:72) ~[okhttp-3.14.9.jar!/:na] 
    at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:43) ~[okhttp-3.14.9.jar!/:na] 
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar!/:na] 
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43) ~[okhttp-3.14.9.jar!/:na] 
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar!/:na] 
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar!/:na] 
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) ~[okhttp-3.14.9.jar!/:na] 
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar!/:na] 
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar!/:na] 
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.14.9.jar!/:na] 
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar!/:na] 
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88) ~[okhttp-3.14.9.jar!/:na] 
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar!/:na] 
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar!/:na] 
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) ~[okhttp-3.14.9.jar!/:na] 
    at okhttp3.RealCall.execute(RealCall.java:81) ~[okhttp-3.14.9.jar!/:na] 
    at io.minio.MinioClient.execute(MinioClient.java:647) ~[minio-8.0.3.jar!/:8.0.3] 
    at io.minio.MinioClient.putObject(MinioClient.java:4547) ~[minio-8.0.3.jar!/:8.0.3] 
    at io.minio.MinioClient.putObject(MinioClient.java:2713) ~[minio-8.0.3.jar!/:8.0.3] 
    at io.minio.MinioClient.putObject(MinioClient.java:2830) ~[minio-8.0.3.jar!/:8.0.3] 
    at com.blinkfox.optimus.tcs.miniolocaldemo.service.MinioClientService.putObject(MinioClientService.java:83) ~[classes!/:2.5.9] 
    at com.blinkfox.optimus.tcs.miniolocaldemo.service.TcsMinioService.randomNativeUpload(TcsMinioService.java:259) ~[classes!/:2.5.9] 
    at com.blinkfox.optimus.tcs.miniolocaldemo.service.TcsMinioService.randomNativeUploadAndDownload(TcsMinioService.java:309) ~[classes!/:2.5.9] 
    at com.blinkfox.optimus.tcs.miniolocaldemo.controller.MinioController.randomNative(MinioController.java:118) ~[classes!/:2.5.9] 
```

The original issue was in minio-java：[The ArrayIndexOutOfBoundsException occurs when Minio Java SDK operates concurrently in docker container with CPU architecture of arm64](https://github.com/minio/minio-java/issues/1135)。

My environment:

- cpu arch: `aarch64`
- docker version: `19.03.8`
- Java version: `1.8.0_201`
- okhttp version: `3.14.9`

**Comment by yschimke** [comment] 2020-12-16 07:42
Usually this indicates you are using the response concurrently from different threads or something similar.  But I can't say definitively.  Our two supported versions are 3.12.12 (legacy) and 4.9.0 and it might have been fixed in either OkHttp or Okio since.

4.x is based on kotlin so a lot of the internal implementation changes because of different compiler choices etc.  But hard to say much definitively.  Closing this out, please reopen if you can reproduce on a current supported version (either one is fine).

**Closed by yschimke** 2020-12-16 07:42 UTC
Labels: bug

**Comment by blinkfox** [comment] 2020-12-16 07:48
@yschimke Okay thank you！
