### ISSUE TITLE
Unknown Error: "???" okhttp3.internal.http2.Http2Writer.data

### ISSUE THREAD

**Issue by imcsedms** [square/okhttp#5497] opened 2019-09-26 06:04 UTC
Hi,

I'm using retrofit on my Android Project and I got a report from crashlytics but surprisingly has no stack trace:

![image](https://user-images.githubusercontent.com/47604549/65662177-1da2b800-e066-11e9-8293-4235f154a9c3.png)

![image](https://user-images.githubusercontent.com/47604549/65662231-432fc180-e066-11e9-8bd6-111fe059147d.png)

These are my dependencies concerning this issue.

```gradle
//Retrofit
implementation 'com.squareup.retrofit2:retrofit:2.4.0'
implementation 'com.squareup.retrofit2:converter-gson:2.4.0'
implementation 'com.squareup.retrofit2:adapter-rxjava2:2.4.0'
implementation 'com.squareup.okhttp3:logging-interceptor:3.7.0'
```

Any chance we can identify such occurrence? Device used is Samsung Galaxy Tab A, Android Pie (9)

Thanks!

**Comment by yschimke** [comment] 2019-09-26 06:23
Unless you can provide a reproducible test case there is not much we can help with.  Please re-open with that or post in an appropriate format to stackoverflow.

Sorry, but closing until we get something more we can work with to show a real bug in okhttp.

**Closed by yschimke** 2019-09-26 06:23 UTC
Labels: bug

**Comment by JakeWharton** [comment] 2019-09-26 11:37
OOMs are rarely caused by what fails when they're thrown. You have general
memory problems and should investigate leaks and heap dumps to see what is
consuming your application's memory.
