### ISSUE TITLE
Is it possible to send both cache and network response for a single request

### ISSUE THREAD

**Issue by sathi-007** [square/okhttp#2306] opened 2016-02-01 10:40 UTC
i would like to fetch data from cache first and then send network request, so that the user will not feel the delay of network response.

Is there any possible tweak for this. please let me know.

**Comment by JakeWharton** [comment] 2016-02-01 15:14
Probably a dupe of #1083. 

You can make two requests for now. The first should use `CacheControl.FORCE_CACHE` and the second can just be a normal request.

**Closed** 2016-02-03 23:24 UTC
