### ISSUE TITLE
Possible race condition with http2

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#2469] opened 2016-04-09 17:40 UTC
I haven't looked into this yet, but am seeing different behaviour for the same operation

```
$ okcurl --frames https://graph.facebook.com/robots.txt
<< 0x00000000    30 SETTINGS      
<< 0x00000000     4 WINDOW_UPDATE 
>> CONNECTION 505249202a20485454502f322e300d0a0d0a534d0d0a0d0a
>> 0x00000000     0 SETTINGS      ACK
>> 0x00000000     6 SETTINGS      
>> 0x00000000     4 WINDOW_UPDATE 
>> 0x00000003    76 HEADERS       END_STREAM|END_HEADERS
<< 0x00000000     0 SETTINGS      ACK
<< 0x00000003     4 WINDOW_UPDATE 
<< 0x00000003   174 HEADERS       END_HEADERS
<< 0x00000003    26 DATA          END_STREAM
User-agent: *
Disallow: /
>> 0x00000000     8 GOAWAY       
``` 

```
$ okcurl --frames https://graph.facebook.com/robots.txt
<< 0x00000000    30 SETTINGS      
>> 0x00000000     0 SETTINGS      ACK
<< 0x00000000     4 WINDOW_UPDATE 
>> CONNECTION 505249202a20485454502f322e300d0a0d0a534d0d0a0d0a
>> 0x00000000     6 SETTINGS      
>> 0x00000000     4 WINDOW_UPDATE 
>> 0x00000003    76 HEADERS       END_STREAM|END_HEADERS
<< 0x00000000    34 GOAWAY        
>> CONNECTION 505249202a20485454502f322e300d0a0d0a534d0d0a0d0a
<< 0x00000000    30 SETTINGS      
<< 0x00000000     4 WINDOW_UPDATE 
>> 0x00000000     0 SETTINGS      ACK
>> 0x00000000     6 SETTINGS      
>> 0x00000000     4 WINDOW_UPDATE 
>> 0x00000003    76 HEADERS       END_STREAM|END_HEADERS
<< 0x00000000     0 SETTINGS      ACK
<< 0x00000003     4 WINDOW_UPDATE 
<< 0x00000003   172 HEADERS       END_HEADERS
<< 0x00000003    26 DATA          END_STREAM
User-agent: *
Disallow: /
>> 0x00000000     8 GOAWAY   
```

**Comment by yschimke** [comment] 2016-04-10 04:11
Not sure of the root cause, but I believe its actually an error from the server that gets translated into a retry because of IPv6 and IPv4 addresses that are available.

java.io.IOException: stream was reset: REFUSED_STREAM
	at okhttp3.internal.framed.FramedStream.getResponseHeaders(FramedStream.java:145)
	at okhttp3.internal.http.Http2xStream.readResponseHeaders(Http2xStream.java:149)
	at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:723)
	at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:81)
	at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:708)

Two questions I have

1) Is this a client bug or a server bug? I'll dig into that a bit.
2) Should clients be made aware of this as its likely to affect initial connection latency, potentially badly if DNS misconfiguration is causing longer delays

**Comment by yschimke** [comment] 2016-04-10 05:13
I can actually replicate it with api.twitter.com also.  Again it seems to be based on the ordering of events.

```
[api.twitter.com/199.59.150.9, api.twitter.com/199.59.149.232, api.twitter.com/199.59.150.41, api.twitter.com/199.59.149.199]
<< 0x00000000     6 SETTINGS      
>> 0x00000000     0 SETTINGS      ACK
>> CONNECTION 505249202a20485454502f322e300d0a0d0a534d0d0a0d0a
>> 0x00000000     6 SETTINGS      
>> 0x00000000     4 WINDOW_UPDATE 
<< 0x00000000     8 GOAWAY        
PROTOCOL_ERROR
>> CONNECTION 505249202a20485454502f322e300d0a0d0a534d0d0a0d0a
<< 0x00000000     6 SETTINGS      
>> 0x00000000     0 SETTINGS      ACK
>> 0x00000000     6 SETTINGS      
>> 0x00000000     4 WINDOW_UPDATE 
>> 0x00000003   381 HEADERS       END_STREAM|END_HEADERS
<< 0x00000000     0 SETTINGS      ACK
<< 0x00000003   204 HEADERS       END_HEADERS
<< 0x00000003   126 DATA          END_STREAM
```

**Comment by dave-r12** [comment] 2016-04-10 15:08
I can reproduce this by setting a breakpoint in FramedConnection, line 508. It looks like the server is sending the SETTINGS frame before we have time to send the connection preface. We ACK the settings before sending our connection preface. From the spec

> The SETTINGS frames received from a peer as part of the connection preface MUST be acknowledged (see Section 6.5.3) after sending the connection preface.

@swankjesse does that sound right?

**Comment by swankjesse** [comment] 2016-04-10 16:15
@dave-r12 yeah, that sounds exactly right. We should defer starting the reader thread until after we’ve written the connection preface. Want to take that?

**Comment by swankjesse** [comment] 2016-04-10 16:20
It might be as simple as moving this line to the bottom of `sendConnectionPreface()`, renaming that method to suit its new functionality, and fixing any tests that this upsets.

```
    new Thread(readerRunnable).start(); // Not a daemon thread.
```

**Comment by dave-r12** [comment] 2016-04-10 16:27
I haven't spent much time in that area of the code base yet, it will probably take me a bit to get my footing. I can get started on building my mental model, feel free to make the change.

**Comment by swankjesse** [comment] 2016-04-10 16:28
On it.

**Comment by swankjesse** [comment] 2016-04-10 16:28
You can be my reviewer!

**Comment by yschimke** [comment] 2016-04-10 17:10
FYI - I can't reproduce the issue with your branch

**Closed** 2016-04-10 19:02 UTC
