### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: Handshake failed

### ISSUE THREAD

**Issue by IgorGanapolsky** [square/okhttp#1940] opened 2015-10-22 19:53 UTC
Hi,
I am trying to make a GET request to an HTTPS server (over VPN).  I followed the guidelines described in this issue: https://github.com/square/okhttp/issues/1628.  However, it's keeps giving me an error:
> javax.net.ssl.SSLHandshakeException: Handshake failed

I am using Retrofit 2.0.0-beta2 in my Android application for this networking code.  Please advise.

Thank you,
Igor

**Comment by artem-zinnatullin** [comment] 2015-10-22 23:48
Try to connect to your https endpoint via browser/another_http_client through the VPN, there are high chances that VPN is the reason of your problems.

**Comment by IgorGanapolsky** [comment] 2015-10-22 23:50
No, VPN is not the problem.  Connected to VPN,  I am able to hit this
server through the browser on Android.  I just can't hit it in my app.

**Comment by artem-zinnatullin** [comment] 2015-10-22 23:56
ok, is it reachable via OkHttp without VPN? If not — (why you mentioned that you're doing it over VPN…) it may be a problem of https configuration on the backend so you can contact their support with this issue.

**Comment by IgorGanapolsky** [comment] 2015-10-23 00:01
My point is that VPN is necessary to hit this particular server.  And I can
reach it through the browser.  But not through the app on the phone.  Both
- my computer and Android phone - have VPN configs set up.  Makes sense?

**Comment by swankjesse** [comment] 2015-10-23 02:38
Could you provide a test case to demonstrate the problem?

**Comment by IgorGanapolsky** [comment] 2015-10-23 02:40
What's the best way to simulate VPN and a TLS server in a test case?  I
cannot reveal my company's server details - obviously.

**Comment by swankjesse** [comment] 2015-10-23 03:38
@IgorGanapolsky sounds like a duplicate of a bug we're already tracking.
https://github.com/square/okhttp/issues/1780

**Closed by swankjesse** 2015-10-23 03:38 UTC

**Comment by IgorGanapolsky** [comment] 2015-10-23 06:07
@swankjesse You linked to an enhancent PR?

**Comment by swankjesse** [comment] 2015-10-23 17:06
Yes. It's a feature request.

**Comment by tulasi-ram** [comment] 2016-10-18 17:10
Throwing the below error in onFailure() call back method
javax.net.ssl.SSLHandshakeException: Handshake failed 

i'm using  below libraries
compile 'com.squareup.retrofit2:retrofit:2.1.0'
compile 'com.squareup.retrofit2:converter-gson:2.1.0'
compile 'com.google.code.gson:gson:2.6.2'

Any one of please help me on this..

**Comment by JohanOtto** [comment] 2018-07-24 16:09
Having similar problems - inspecting the SSLException reveals BAD_ALERT - any ideas?

**Comment by elong4321** [comment] 2020-03-18 03:52
I meet the same problem now, have you fix this ? please help~
