### ISSUE TITLE
Explicit termination method 'response.body().close()' not called

### ISSUE THREAD

**Issue by lizhangqu** [square/okhttp#3632] opened 2017-09-29 04:43 UTC
I got this log from logcat with okhttp 3.9.0

```
E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                     java.lang.Throwable: Explicit termination method 'response.body().close()' not called
                                                                         at dalvik.system.CloseGuard.open(CloseGuard.java:223)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at okhttp3.internal.platform.AndroidPlatform$CloseGuard.createAndOpen(AndroidPlatform.java:329)
                                                                         at okhttp3.internal.platform.AndroidPlatform.getStackTraceForCloseable(AndroidPlatform.java:144)
                                                                         at okhttp3.RealCall.captureCallStackTrace(RealCall.java:89)
                                                                         at okhttp3.RealCall.execute(RealCall.java:73)
                                                                         at com.weidian.thor.sample.download.DownloadActivity$7.call(DownloadActivity.java:180)
                                                                         at com.weidian.thor.sample.download.DownloadActivity$7.call(DownloadActivity.java:172)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                         at java.lang.Thread.run(Thread.java:764)
```

The test code is very easy. The method called in this order
>testDownloadWithOkHttp()->testCancelDownloadWithOkHttp()->testDownloadWithOkHttp()->download successfully

```
okhttp3.OkHttpClient okHttpClient = new okhttp3.OkHttpClient();
ExecutorService executorService = Executors.newFixedThreadPool(4);
FutureTask<?> downloadTask = null;

public FutureTask<?> testDownloadWithOkHttp() {
    FutureTask<Boolean> futureTask = new FutureTask<Boolean>(new Callable<Boolean>() {
        @Override
        public Boolean call() throws Exception {
            ReadableByteChannel fromChannel = null;
            FileChannel toChannel = null;
            try {
                okhttp3.Request.Builder builder = new okhttp3.Request.Builder();
                builder.url("http://of87ke26x.bkt.clouddn.com/1000n_shurufa_2.2.4_2017-09-25_10-39-20.apk");
                okhttp3.Response response = okHttpClient.newCall(builder.build()).execute();
                InputStream inputStream = response.body().byteStream();
                fromChannel = Channels.newChannel(inputStream);
                File file = new File("/sdcard/temp.apk");
                toChannel = new FileOutputStream(file).getChannel();
                long transferSize = toChannel.transferFrom(fromChannel, 0, Long.MAX_VALUE);
                if (transferSize != response.body().contentLength()) {
                    throw new IllegalStateException("not read all");
                }
                Log.i("download", "success");
                return true;
            } finally {
                if (fromChannel != null) {
                    try {
                        fromChannel.close();
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
                if (toChannel != null) {
                    try {
                        toChannel.close();
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        }
    });
    executorService.execute(futureTask);
    return futureTask;
}

public void testCancelDownloadWithOkHttp() {
    if (downloadTask != null) {
        try {
            downloadTask.cancel(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

I call testDownloadWithOkHttp() to download the file, then I cancel the task by call testCancelDownloadWithOkHttp(). now will happen a error, but I try catch it in testCancelDownloadWithOkHttp method. the error is

```
W/System.err: java.lang.IllegalStateException: Unbalanced enter/exit
W/System.err:     at okio.AsyncTimeout.enter(AsyncTimeout.java:73)
W/System.err:     at okio.AsyncTimeout$2.read(AsyncTimeout.java:235)
W/System.err:     at okio.RealBufferedSource.read(RealBufferedSource.java:46)
W/System.err:     at okhttp3.internal.http1.Http1Codec$AbstractSource.read(Http1Codec.java:352)
W/System.err:     at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:396)
W/System.err:     at okhttp3.internal.Util.skipAll(Util.java:175)
W/System.err:     at okhttp3.internal.Util.discard(Util.java:157)
W/System.err:     at okhttp3.internal.http1.Http1Codec$FixedLengthSource.close(Http1Codec.java:413)
W/System.err:     at okio.RealBufferedSource.close(RealBufferedSource.java:455)
W/System.err:     at okio.RealBufferedSource$1.close(RealBufferedSource.java:443)
W/System.err:     at java.nio.channels.Channels$ReadableByteChannelImpl.implCloseChannel(Channels.java:404)
W/System.err:     at java.nio.channels.spi.AbstractInterruptibleChannel$1.interrupt(AbstractInterruptibleChannel.java:166)
W/System.err:     at java.lang.Thread.interrupt(Thread.java:924)
W/System.err:     at java.util.concurrent.FutureTask.cancel(FutureTask.java:175)
W/System.err:     at com.weidian.thor.sample.download.DownloadActivity.testCancelDownloadWithOkHttp(DownloadActivity.java:216)
W/System.err:     at com.weidian.thor.sample.download.DownloadActivity$2.onClick(DownloadActivity.java:90)
W/System.err:     at android.view.View.performClick(View.java:6256)
W/System.err:     at android.view.View$PerformClick.run(View.java:24697)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:789)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
W/System.err:     at android.os.Looper.loop(Looper.java:164)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6541)

09-29 12:34:54.421 14466-14466/com.weidian.thor.sample W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

Then I call testDownloadWithOkHttp again. Wait about 1 minitues, the file has download successfully. Now will get **Explicit termination method 'response.body().close()' not called**

How can I fix it? And I would cancel it by FutureTask rather than **okhttp3.Call**. Thanks!

**Comment by yschimke** [comment] 2017-09-30 17:10
I don't think OkHttp is handling thread interrupts via FutureTask.cancel(true) particularly well here.  But I'm not sure it has been written to assume that thread interrupts can happen at any point.  So it may not be a bug that gets fixed within OkHttp.

OkHttp already provides mechanisms to cancel requests (Call.cancel()), if you can cancel the call instead of interrupting the thread you should avoid getting these warnings.  I'm not clear why you don't want to do that.

**Comment by yschimke** [comment] 2017-10-01 14:08
Duplicate of https://github.com/square/okhttp/issues/1902

**Closed by yschimke** 2017-10-01 14:08 UTC

**Comment by lizhangqu** [comment] 2017-10-02 02:41
@yschimke because I need to implements a common cancellable request but it's not depends on OkHttp API

**Comment by yschimke** [comment] 2017-10-02 04:52
OK, it is still a duplicate of #1902, so is there anything about this issue that means we need to have both issues open?

**Comment by yschimke** [comment] 2017-10-02 05:10
@lizhangqu as this may not get fixed in the timeframe you need, you could consider implementing non-standard cancellations through the Future API. This should stop the errors you are seeing and generally leave OkHttp connections in a better state than the current thread interrupt.

https://10kloc.wordpress.com/2013/12/24/cancelling-tasks-in-executors/

**Comment by lizhangqu** [comment] 2017-10-03 02:43
@yschimke thank you very much, I will have a try!
