### ISSUE TITLE
HttpLoggingInterceptor crashes when dealing with websockets

### ISSUE THREAD

**Issue by urandom** [square/okhttp#2848] opened 2016-09-12 10:18 UTC
Hello,

The current implementation (3.4.1) of HttpLoggingInterceptor always expects a response body to be present. That is not always the case. For example, when using okhttp-ws, the body of the response is null.

A NPE is thrown here, though there are plenty of other places where one will trigger as well:
https://github.com/square/okhttp/blob/413323f10d68e7581431b289971ec780cd0485a6/okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.java#L220

**Comment by JakeWharton** [comment] 2016-09-12 13:18
Dupe of #2811 and already fixed on master.

**Closed by JakeWharton** 2016-09-12 13:18 UTC
