### ISSUE TITLE
Custom verbs wont be allowed to have a request body

### ISSUE THREAD

**Issue by Cheesebaron** [square/okhttp#1549] opened 2015-04-08 09:36 UTC
All custom verbs will be refused to have a request body and building the request will throw a `IllegalArgumentException`.

https://github.com/square/okhttp/blob/master/okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpMethod.java#L32

https://github.com/square/okhttp/blob/master/okhttp/src/main/java/com/squareup/okhttp/Request.java#L233

Is it possible to get some way to override this behavior?

**Comment by JakeWharton** [comment] 2015-04-17 02:53
Dupe of #229.

**Closed by JakeWharton** 2015-04-17 02:53 UTC
