### ISSUE TITLE
Can we solve it quickly

### ISSUE THREAD

**Issue by xuxinjiang** [square/okhttp#6703] opened 2021-06-12 03:28 UTC
2021-06-11 14:29:34.350 30588-2935/com.hoo.qianbao E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.hoo.qianbao, PID: 30588
    java.lang.IllegalStateException: No deadline
        at okio.Timeout.deadlineNanoTime(Timeout.kt:56)
        at okio.AsyncTimeout$Companion.scheduleTimeout(AsyncTimeout.kt:238)
        at okio.AsyncTimeout$Companion.access$scheduleTimeout(AsyncTimeout.kt:201)
        at okio.AsyncTimeout.enter(AsyncTimeout.kt:54)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:331)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320)
        at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.java:242)
        at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.java:213)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:172)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

**Comment by xuxinjiang** [comment] 2021-06-12 03:30
How to solve this problem?

**Comment by xuxinjiang** [comment] 2021-06-12 03:30
![QQ截图20210612113016](https://user-images.githubusercontent.com/41047773/121763834-97980f00-cb71-11eb-86ff-94f3096765cf.png)
Doesn't that work

**Comment by yschimke** [comment] 2021-06-13 03:33
Dupe of https://github.com/square/okhttp/issues/6689

> All Android versions & devices? We've seen bugs like this that only occur on devices that have buggy VMs.

**Closed by yschimke** 2021-06-13 03:33 UTC
Labels: bug
