### ISSUE TITLE
Support instrumentation in HTTP engine

### ISSUE THREAD

**Issue by karthikrg** [square/okhttp#2011] opened 2015-11-18 22:55 UTC
We want to instrument timings for the following in HttpEngine:

1. TCP Connection time
2. DNS resolution time
3. SSL negotiation time

In order to get more granular metrics on the performance of our Android app in the field. HttpEngine currently is an internal class that does not offer any hooks for measuring these parameters. Can we get this support added please? 

Willing to help with a pull request.

**Comment by JakeWharton** [comment] 2015-11-18 22:56
Probably falls under what #270 is trying to accomplish.

**Comment by swankjesse** [comment] 2015-11-22 17:38
Duplicate of #270.

**Closed by swankjesse** 2015-11-22 17:38 UTC
