### ISSUE TITLE
recipes/Progress.java not working for android

### ISSUE THREAD

**Issue by KavithaFP** [square/okhttp#1892] opened 2015-10-01 00:11 UTC
I don't get any exceptions but don't see any progress or the downloaded file. On debugging I see the response object vanishes after HTTPEngine.java line 905. FYI, this recipe runs perfectly on Java with the given file. I have a basic activity with a button. The onClick handler of the button has the logic of Progress.java's "run" method.

**Comment by swankjesse** [comment] 2015-10-31 00:43
Is the problem that the logs aren't going where you want? You might want to replace the `System.out` calls with `Log.w` or similar.

If you can provide a test case to demonstrate the problem, please do. Otherwise I'm closing as cannot reproduce because it's unclear what action we can take here.

**Closed by swankjesse** 2015-10-31 00:43 UTC

**Comment by Danm72** [comment] 2015-11-24 01:34
I'm coming across the same problem. Having swapped system.out.print for log I still get nothing from the update method.

Debugging shows the constructor of the interceptor and request body are both called. But the content of the request body is never touched.

This is on Android.

Thanks, great framework by the way.

**Comment by Danm72** [comment] 2015-11-24 11:38
Figured out the problem was that the Progress.java example only seems to work for requests with ResponseBodys where as I wanted the progress of a GET. 

Using http://stackoverflow.com/questions/26114299/squares-okhttp-download-progress/26115161#26115161 swapping out the async task for enqueue and using the input stream from the response did the trick.
