### ISSUE TITLE
java.Util.NoSuchElementException in DiskLruCache

### ISSUE THREAD

**Issue by nwalters512** [square/okhttp#1804] opened 2015-08-11 23:16 UTC
I am unable to reproduce this exception, but I've seen it randomly occur several times while using my app.

    java.util.NoSuchElementException
            at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:349)
            at java.util.LinkedHashMap$ValueIterator.next(LinkedHashMap.java:370)
            at com.squareup.okhttp.internal.DiskLruCache.trimToSize(DiskLruCache.java:664)
            at com.squareup.okhttp.internal.DiskLruCache.access$200(DiskLruCache.java:88)
            at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:175)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by denversc** [comment] 2015-10-16 19:47
I just saw this too, and logged a duplicate issue (which I will close ASAP): #1932.  I've copied my description and analysis below.

In an Android app that I'm writing I got a ```NoSuchElementException``` thrown from ```DiskLruCache.trimToSize()``` when invoked from ```cleanupRunnable```; however, I would expect that trimToSize() would never cause such an exception to occur.

    FATAL EXCEPTION: OkHttp DiskLruCache
    java.util.NoSuchElementException
        at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:350)
        at java.util.LinkedHashMap$ValueIterator.next(LinkedHashMap.java:371)
        at com.squareup.okhttp.internal.DiskLruCache.trimToSize(DiskLruCache.java:664)
        at com.squareup.okhttp.internal.DiskLruCache.access$200(DiskLruCache.java:88)
        at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:175)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)

I think this exception is a symptom of a race condition.  This exception happened when I cancelled an upload in my Android app, which calls ```OkHttpClient.cancel(Object tag)```, which I believe schedules an asynchronous run of ```DiskLruCache.cleanupRunnable```.

All calls to ```trimToSize()``` are synchronized on the enclosing DiskLruCache instance... except when called from ```cleanupRunnable```.  This is suspicious, as perhaps the calls to trimToSize() from cleanupRunnable should also be synchronized on the DiskLruCache instance?

okhttp version on which this issue was discovered: com.squareup.okhttp:okhttp:2.4.0

Thanks!

**Comment by sfsheng0322** [comment] 2015-12-24 03:28
java.util.NoSuchElementException
	at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:79)
	at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:164)
	at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:283)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
	at com.squareup.okhttp.Call.getResponse(Call.java:286)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
	at com.squareup.okhttp.Call.access$100(Call.java:35)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:171)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)


why???

**Comment by dave-r12** [comment] 2016-03-21 00:42
I think this is a dupe of #2420.

**Comment by dave-r12** [comment] 2016-03-31 11:57
I believe this was fixed with #2421.

**Closed by dave-r12** 2016-03-31 11:57 UTC
Labels: bug
