### ISSUE TITLE
Possible enhancement: Allow setting request priorities

### ISSUE THREAD

**Issue by vinaysshenoy** [square/okhttp#1361] opened 2015-02-04 15:07 UTC
I've been using Volley with an OkHttp stack for a while now, but I've been wanting to switch to a pure OkHttp stack for a while now(streaming response bodies, interceptors, multipart requests, ease of integration are a few of the reasons).

One of the reasons I have held of on this change is because Volley has one feature that OkHttp doesn't have yet: support for prioritizing requests. Would such a feature be acceptable as a Pull Request if I implement it?

**Comment by swankjesse** [comment] 2015-02-04 21:00
This is a tricky feature to do generally. Is policy fixed or pluggable? Does the default policy starve low priority requests? When is priority enforced? Do we short circuit low priority calls that would benefit from the cache? Is the priority shared with the HTTP/2 server?

I'm reluctant to solve this partially, and solving it generally is a lot of work. I'd prefer to punt on this for now.

**Comment by vinaysshenoy** [comment] 2015-02-05 05:05
AH, got it. I didn't think of that.

Anyway, this is something I need and I feel it would be a good addition to
the library. I'll draft up a set of reqs for the feature(considering
whatever you've mentioned) and update this issue. If you're okay with them,
I can implement this and submit a PR whenever it's ready.


On Thu, Feb 5, 2015 at 2:31 AM, Jesse Wilson <notifications@github.com>
wrote:

> This is a tricky feature to do generally. Is policy fixed or pluggable?
> Does the default policy starve low priority requests? When is priority
> enforced? Do we short circuit low priority calls that would benefit from
> the cache? Is the priority shared with the HTTP/2 server?
>
> I'm reluctant to solve this partially, and solving it generally is a lot
> of work. I'd prefer to punt on this for now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/square/okhttp/issues/1361#issuecomment-72937939>.
>



-- 
Vinay S Shenoy
Android App Developer at Flipkart.com
+91-9538122356 | vinaysshenoy@gmail.com
LinkedIn : http://in.linkedin.com/in/vinaysshenoy

**Comment by swankjesse** [comment] 2015-02-06 04:57
Cool. I think we'll probably hold on priorities until we also make the backend async for HTTP/2. When things are async we suddenly get better control over which order tasks are completed.

**Comment by ansman** [comment] 2016-03-15 13:02
@swankjesse Is there a timeline for when the backend will be async?

**Comment by swankjesse** [comment] 2016-03-15 14:07
No timeline.

**Comment by iAviatorJose** [comment] 2016-09-15 06:49
@swankjesse is this feature implemented

**Comment by swankjesse** [comment] 2016-09-15 11:16
Not implemented.

**Comment by alexanderkjeldaas** [comment] 2017-01-25 11:27
I don't quite understand the worries cited above.  Couldn't the priority simply be forwarded to the HTTP/2 server and be interpreted by the server?

How the server interprets priorities is given by the HTTP/2 spec (they can be ignored), and whether requests are starved etc. is out of scope for the library.

The tcp socket buffer size is the only thing the client needs to have control of.

**Comment by swankjesse** [comment] 2017-01-26 04:26
OkHttp has a queue of pending requests not yet transmitted to the server. A good priority mechanism should probably influence the queue.

**Comment by 6bangs** [comment] 2017-08-08 14:59
For our use case, we only wanted new requests to be prioritized over old requests, specifically with regard to the `ready` deque (last in, first out). The easiest way to accomplish that was to change the `add` call in the `Dispatcher` to a `push` (specifically [this line](https://github.com/square/okhttp/blob/c70e35802e984e8b9bf3fbf1479deb37c0bdfa43/okhttp/src/main/java/okhttp3/Dispatcher.java#L132)).

This seems to be a more sensible default for many applications, if a real prioritization feature isn't on the roadmap for the foreseeable future.

**Comment by swankjesse** [comment] 2018-02-18 21:05
Duplicate of https://github.com/square/okhttp/issues/1361

**Comment by swankjesse** [comment] 2018-02-18 21:05
Duplicate of https://github.com/square/okhttp/issues/404

**Closed by swankjesse** 2018-02-18 21:05 UTC
Labels: enhancement
